### ISSUE TITLE
Reimbursement Part 1

### ISSUE THREAD

**Issue by warehousman** [edenlabllc/ehealth.api#1002]
BRD Design:
- [ ] Register LE
- [ ] Register Employee
- [ ] LE Deactivation
- [ ] Employee Deactivation
- [ ] Medications Import 
- [ ] Create Prescription (CR to be implemented)
- [x] Dispence Prescription (CR to be implemented)

SA Design:
- [x] Reimbursement Data model #998 artifact: https://edenlab.atlassian.net/wiki/x/AZoz
- [x] Register LE #700, artifact inside
- [x] Register Employee #742, artifact inside
- [x] LE Deactivation #704, artifact inside
- [x] Employee Deactivation #778, artifact inside
- [ ] Medications Import -  replaced with medications management
- [x] Create Prescription (CR to be implemented) #966, artifact inside
- [x] Dispence Prescription #1001, #1020 (CR to be implemented)

Development:
- [x] LE Data model #699
- [x] Employee DM #739
- [x] Register LE #700
- [x] Register Employee #742
- [x] LE Deactivation #704
- [x] Employee Deactivation #778
- [ ] Medications Management

Test:
n/a
