### ISSUE TITLE
Medication Dispenses

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#1020]
As a Pharmacy user  
I want be able to Create, Process or Reject Medication Dispenses
So that i can provide medications to a patient

- [x] Create Medication Dispense #1021
- [x] Process Medication Dispense #1022
- [x] Reject Medication Dispense #1044
- [x] AUTO Terminate Dispense #1073
- [ ] Get Medication Dispenses List #1045
- [x] Get Medication Dispense by ID #1046
- [x] Track status history #1074
