### ISSUE TITLE
Update administration Substance\innm\medications DM & WS

### ISSUE THREAD

**Issue by EdwardVoloshin** [edenlabllc/ehealth.api#1125]
According last ERD file:

- [x] change values into `medication_type` dictionary
- innm - > innm_dosage
-medication -> brand

- [x] rename & update entity `substances` -> `inns`
- sctid -> optional
- name_original -> add unique constraint

- [x] update `medications`
- delete `ingredients` attribute 

- [x] update `ingredients`
- rename `is_active_substance` -> `is_primary`
- rename `medication_id ` ->`parent_id` 
 - rename `substance_id` -> `innm_child_id ` (its for  medication_type = innm_dosage) 
 - rename `innm_id` -> `medication_child_id` (its for  medication_type = brand)

- [x] update & rename`program_medications` - > `programs_brands`
- rename `medication_id ` - > `brand_id`
 
Update names for WS:
- [x] `create_substance` - > `create_innm `

- [x] `create_innm` -> `create_innm_dosage`
- [x] `deactivate_innm` -> `deactivate_innm_dosage`
- [x] `get_innm_by_ID` -> `get_innm_dosage_by_ID`
- [x] `get_innms_list` -> `get_innm_dosages_list`

**Comment by PavelVesnin** [comment]
@EdwardVoloshin @AlexKovalevych @AlekzandrV 
Propose for ingredients related fields naming:
`substance_id` -> `innm_dosage_id`
`innm_id ` -> `brand_id`
`medication_id ` - do not rename, because its related to table `medication`

**Comment by PavelVesnin** [comment]
done
