### ISSUE TITLE
semi-blockchain fine tuning

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#1135]
- [x] seed shouldn't be stored on the declaration_request. Read the latest on demand (POST, GET) from `blocks` db – https://github.com/edenlabllc/ehealth.api/pull/1164.
- [x] exclude `is_active`from the block hash calculation – to be discussed with @AlekzandrV – https://github.com/edenlabllc/ops.api/commit/1d03cf04e6bdcc540dca2de802ab41c7dff3f8a7
- [x] add `patient_id` to the block hash calculation – https://github.com/edenlabllc/ops.api/commit/1d03cf04e6bdcc540dca2de802ab41c7dff3f8a7
- [x] `seed` should be also validated during the `signed content validation` process – https://github.com/edenlabllc/ehealth.api/pull/1179.
- [x] `seed` should be also validated against content in object storage during the [report generation process](https://github.com/edenlabllc/report.api/blob/e49e011c60a9e31e76ea2edf0e841b7111d39144/lib/report/billing/billings.ex#L209) – https://github.com/edenlabllc/report.api/pull/39. 
- [x] update validation procedure to protect possible block hash recalculation & update (aka "additional algorithm") https://github.com/edenlabllc/ops.api/pull/39
- [x] add numbers to blocks – https://github.com/edenlabllc/ops.api/pull/34
- [x] add versions to blocks – https://github.com/edenlabllc/ops.api/pull/35
- [x] notify if chain validation process did found a mismatch – https://github.com/edenlabllc/ehealth.api/issues/1135#issuecomment-333555819
- [x] keep a list of all failed blocks; when sending a notification about failed blocks, only inform about blocks that failed during the latest chain verification https://github.com/edenlabllc/ops.api/pull/37

**Comment by gmile** [comment]
Items 2 and 3 were done in https://github.com/edenlabllc/ops.api/commit/1d03cf04e6bdcc540dca2de802ab41c7dff3f8a7

**Comment by gmile** [comment]
Item 4 was done in https://github.com/edenlabllc/ehealth.api/commit/dca848c54738c960b6e422f33e6d92ea19cdb6bb

**Comment by lymychp** [comment]
@gmile  item 4 - should be part of the billing process generation.

**Comment by gmile** [comment]
@lymychp added two more items: add numbers + versions to blocks.

**Comment by gmile** [comment]
Added numbers and versioning:

* block numbers – https://github.com/edenlabllc/ops.api/pull/34
* block algorithm versioning https://github.com/edenlabllc/ops.api/pull/35

**Comment by gmile** [comment]
> seed shouldn't be stored on the declaration_request. Read the latest on demand (POST, GET) from blocks db

Done in https://github.com/edenlabllc/ehealth.api/pull/1164

**Comment by gmile** [comment]
Notifications are being made in 3 parts:

- [x] IL part https://github.com/edenlabllc/ehealth.api/pull/1173 – IL will be sending emails; **merged**
- [ ] OPS part  
- [ ] Configuration part:
    - [x] IL part – https://github.com/edenlabllc/ehealth.charts/commit/7f49d1a149027cc0366a1d1a47438511229b875e
    - [ ] OPS part – under way.

**Comment by gmile** [comment]
After implementing notifications I realized mismatched blocks will raise a notification EVERY time on subsequent verifications, after the initial one when the issue was first spotted, which is noisy may lead to people ignoring the notifications.

We should probably store all spotted mismatches in a separate table, and ignore them on subsequent verifications.

**Comment by gmile** [comment]
> seed should be also validated during the signed content validation process

Done in https://github.com/edenlabllc/ehealth.api/pull/1179

**Comment by lymychp** [comment]
>We should probably store all spotted mismatches in a separate table, and ignore them on subsequent verifications.

actually there should be immediate reaction to the mismatch event. Admin should fix it. One of the options is to restore from the backup.
But anyway storing mismatches is a good idea
