### ISSUE TITLE
Reimbursement Report

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#1157]
In order to be able to create and get Reimbursement Report next steps must be done:

- [x] Create WS spec [apiary](http://docs.uaehealthapi.apiary.io/reference/public.-reimbursement/reimbursement-report/get-reimbursement-report)
- [x] Create WS logic  [confluence](https://edenlab.atlassian.net/wiki/x/fwAIAg)
- [x] Make replication to report db #1156
- [x] Implement
- [ ] Deploy
- [x] Create test scenarios

**Comment by lymychp** [comment]
service should return link to download file. 
web-hook to inform that report is ready to download.
