### ISSUE TITLE
Portal Reimbursement

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#1161]
Add to portal statistics by Pharmacy, Pharmacy_employee and Medical_requests.

- [x] make replication to report db #1156
- [x] create and make replica for medication_requests_status_hstr #1203
- [x] update and add fields to existing endpoints [spec](http://docs.uaehealthapi.apiary.io/reference/internal.-portal-and-reports/mainstats/get-main-stats)
- [x] update front  [view](https://www.dropbox.com/s/4kumij098d6hd89/NSZ_landing.jpg?dl=0)

**Comment by danakonovalenko** [comment]
@AlexKovalevych only MSP and PHARMACIES with status 'ACTIVE' must be taken into account. Now 'CLOSED' legal_entities also are taken into account.
