### ISSUE TITLE
Medication Requests page for NHS admin

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#1174]
NHS admin must be able to get Medication Requests Lists by next filters
[design](https://www.dropbox.com/sh/58m6uga4zc2riw2/AAA7KmvhDcZFE8lMMepsoko9a?dl=0):
```
employee_id (exact)
person_id (exact)
status (case insensitive)
request_number (exact) - Public medication request human readable number 
created_from (exact)
created_to (exact)
division_id (exact)
medication_id (exact)
```
Filters also can be combined together (example edrpou & created_at, edrpou& innm_dosage_name)

Fields for grid:
```
- created_at
- medication_request_id
- request_number
- division_id
- medication_id
- person_id
- status
- details
```
Page with details [apiary](http://docs.uaehealthapi.apiary.io/reference/public.-reimbursement/medication-request/get-medication-request-by-id):

```
I. General Info
    id - b075f148-7f93-4fc2-b2ec-2d81b19a9b7b"
    status - "ACTIVE"
    request_number -"xxxx"
    created_at - "2017-08-17"
    started_at -"2017-08-17"
    ended_at -"2017-09-16"
    dispense_valid_from - "2017-08-17"
    dispense_valid_to -"2017-09-16"
II. Legal entity info
     id - "b075f148-7f93-4fc2-b2ec-2d81b19a9b7b"
     name - "Клініка Борис"
     edrpou": "5432345432"
     division_id: "d290f1ee-6c54-4b01-90e6-d701748f0851"
     division_name: "Бориспільське відділення Клініки Борис"
III. Employee info
     id - "d290f1ee-6c54-4b01-90e6-d701748f0851"
     first_name - "Петро"
     last_name - "Іванов"
     second_name - "Миколайович"
     birth_date - "1991-08-19"
IV. Person Info
     person_id - "b075f148-7f93-4fc2-b2ec-2d81b19a9b5a"
     last_name&fist_name_second_name - 'Іванов Петро Миколайович'
     tax_id - "3126509816"
     birth_date - "1991-08-19"
V. Medication info
      medication_id (actually shows innm_dosage_id) 
      innm_dosage.id: "4a63b858-c138-4921-9341-ae9e384bcbd6"(actually shows innm_id) 
      innm_dosage.name - "Аміодарон" (actually shows innm_name) 
      form: "PILL"
      dosage: "numerator_unit" &  "numerator_value"/ "denumerator_unit":& "denumerator_value"
      medication_qty - 10
VI. Medical program info
    id - "59781de0-2e64-4359-b716-bcc05a32c10f",
    name - program 'DOSTUPNI LIKI'"

**Comment by danakonovalenko** [comment]
@AlexKovalevych I added filter parameters to medication requests list. Please, update according to [apiary](http://docs.uaehealthapi.apiary.io/reference/public.-reimbursement/medication-request/get-medication-requests-list)

**Comment by danakonovalenko** [comment]
It was decided we can show some personal info in NHS admin. I added a new block Person Info after Employee Info

**Comment by danakonovalenko** [comment]
@kiurchv Comments:

***Медичні запити (change to Рецепти)***
- [ ] change id view and show full string
- [ ] in filter change: 
"За номером запиту" - "За номером рецепту"
"ID розподілу" to "ID підрозділу"
- [ ]  change headers in lists: 
"номером запиту" - "номер рецепту"
"ID філії" - "ID підрозділу"
- [ ] rename in detail page
ID запиту - ID рецепту
Номер медзапиту - номер рецепту
Дозвіл дійсний з/ Дозвіл дійсний з -  Відпуск дійсний з/ Відпуск дійсний по
Інформація про юридичну особу - Інформація про медичний заклад
ID особи - ID медичного закладу
ID філії/ ID підрозділу 
Назва філії - Назва підрозділу

***Рецепти (change to Відпуск рецепту)***

- [ ] change id view and show full string
- [ ] in filter change: 
"За ID мед запиту" - "За ID рецепту"
"За ID юр особи" - "За ID аптеки"
"За ID розподілу" to "За ID підрозділу"
"За датою виписки" - "За датою відпуску"
- [ ]  change headers in lists: 
"ID рецепту" - "ID"
"ID  мед запиту" - " ID рецепту"
"ID юр особи" - "ID аптеки"
"ID розподілу" - "ID підрозділу"
"Виписаний" - "Дата відпуску"

- [ ] rename in detail page
ID рецепту - ID відпуску рецепту
ID медзапиту - ID рецепту
Номер медзапиту - номер рецепту
Виписаний - Дата відпуску
Аптека. ID особи - ID аптеки

**Comment by danakonovalenko** [comment]
@kiurchv 
- [ ] delete tax_id from Person as we don't have that valued in response
- [ ] medication_qty was missed. Add medication_qty to V. Лікарський засіб "Кількість препарату"
- [ ] incorrect employee_id (now employee.party.id, must be employee.id)
- [ ] doesn't work search за номером рецепту (000-9EAX-XT7X-3115)
- [ ] search by division_id returns incorrect results
- [ ] search by medication_id returns incorrect result
- [ ] rename "за ID Торгової назви" to "за ID Лікарської форми"
- [ ] in liest headers rename  "ID Торгової назви" to  "ID Лікарської форми"

**Comment by danakonovalenko** [comment]
- [ ] change search by division_id to search by legal_enitity_id (за id медичного закладу)
- [ ] add legal_entity_id to grid (id медичного закладу)
