### ISSUE TITLE
Medication Dispense Page for NHS Admin

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#1176]
NHS admin must be able to get Medication Dispenses Lists by next filters:
[design](https://www.dropbox.com/sh/58m6uga4zc2riw2/AAA7KmvhDcZFE8lMMepsoko9a?dl=0)
```
id (exact)
medication_request_id (exact)
legal_entity_id (exact)
division_id (exact)
status (case insensitive)
dispensed_at (exact)
```

Filters also can be combined together (example division_id & status, dispensed_at& legal_entity_id)
```
Fields for grid:

- id
- medication_request_id
- legal_entity_id
- division_id
- status
- dispensed_at
- details
```
Page with details [apiary](http://docs.uaehealthapi.apiary.io/reference/public.-reimbursement/medication-dispense/get-medication-dispense-by-id):
```
I. General Info
    dispense_id - b075f148-7f93-4fc2-b2ec-2d81b19a9b7b
    status - "NEW"
    request_id - b075f148-7f93-4fc2-b2ec-2d81b19a9bc (link to page with medication request)
    request_number -"xxxx"
    dispensed_at - "2017-08-17"
II. Pharmacy info
     id - "b075f148-7f93-4fc2-b2ec-2d81b19a9b7b"
     name - "Аптека Доброго Дня"
     edrpou": "5432345432"
     division_id: "d290f1ee-6c54-4b01-90e6-d701748f0851"
     division_name: "Бориспільське відділення Аптеки Доброго Дня"
III. Pharmacist info
     id - "d290f1ee-6c54-4b01-90e6-d701748f0851"
     first_name - "Петро"
     last_name - "Іванов"
     second_name - "Миколайович"
IV. Person Info
     person_id - "b075f148-7f93-4fc2-b2ec-2d81b19a9b5a"
     last_name&fist_name_second_name - 'Іванов Петро Миколайович'
     tax_id - "3126509816"
     birth_date - "1991-08-19"
V. Medication info
     medication_id: "4a63b858-c138-4921-9341-ae9e384bcbd6"
     medication_name - "Аміодарон"
     manufacturer name - ПАТ \"Київський вітамінний завод\"
     form - "PILL"
     container - "numerator_unit" &  "numerator_value"/ "denumerator_unit":& "denumerator_value"
     medication_qty - 10
     sell_price - 18.65,
     sell_amount - 186.5,
     discount_amount - 150,
     reimbursement_amount - 450
VI. Medical program info
    id - "59781de0-2e64-4359-b716-bcc05a32c10f"
    name - program 'DOSTUPNI LIKI'"
```

**Comment by danakonovalenko** [comment]
@kiurchv It was decided we can show some personal info in NHS admin. I added a new block Person Info after Pharmacist Info

**Comment by danakonovalenko** [comment]
***Рецепти (change to Відпуск рецепту)***

- [ ] change id view and show full string
- [ ] in filter change: 
"За ID мед запиту" - "За ID рецепту"
"За ID юр особи" - "За ID аптеки"
"За ID розподілу" to "За ID підрозділу"
"За датою виписки" - "За датою відпуску"
- [ ]  change headers in lists: 
"ID рецепту" - "ID"
"ID  мед запиту" - " ID рецепту"
"ID юр особи" - "ID аптеки"
"ID розподілу" - "ID підрозділу"
"Виписаний" - "Дата відпуску"

- [ ] rename in detail page
ID рецепту - ID відпуску рецепту
ID медзапиту - ID рецепту
Номер медзапиту - номер рецепту
Виписаний - Дата відпуску
Аптека. ID особи - ID аптеки
