### ISSUE TITLE
Change WS: Get Medication request Requests List

### ISSUE THREAD

**Issue by EdwardVoloshin** [edenlabllc/ehealth.api#1218]
Need change parameters & logic WS
- remove `legal_entity_id`
- add `person_id`
- change implementation: 
      - use filter `person_id`
      - use filter `employee_id list` (all employee with `party_id` which gated from $.context.user_id)

- [x]  Update WS [spec](https://edenlab.atlassian.net/wiki/x/5gB1)
- [x]  Implement
- [x]  Deploy
- [x]  Improve test scenarios

**Comment by svetavedmed** [comment]
- [ ] no filter by person_id
