### ISSUE TITLE
NHS Admin Portal- Medications bugs - part 1

### ISSUE THREAD

**Issue by EdwardVoloshin** [edenlabllc/ehealth.api#1232]
INNMs - Get List
- [x] not found column `sctid`
- [x] search name `by name_original` - column name `...original name`

INNMs - Create
- [x] no visualisation creating errors

INNM - Detail
- [x] not found attr `id`
- [x] not found attr `sctid`
- [x] not found attr `is_active`
	
INNM_Dosage - Get list
- [x] in 'actions list' not found `deactivate`
- [x] not found column `is_active`
	 

INNM_Dosage - Detail
- [x] incorrect name `ingredients.name`
- [x] incorrect value `dosage` - 1 contains 10 MG (may be -  1 PILL contains 10 MG) - ***translate***
- [x] not found attr `form`
- [x] incorrect name `ingredients.name` at multi ingredients 
- [x] not found attr `ingredients.child_innm_id`	
- [x] not found attr `is_active`

INNM_Dosage - Create
- [x] incorrect values into `одиниці`
- [x] no visualisation creating errors

Medication - Get list
- [x] in 'actions list' not found `deactivate`
- [x] ??? what for `innm_id` column 
- [x] ??? why `form` containts `manufacturer`
- [x] `innm_id` - rename `innm_dosage_id`
- [x] not found search be innm_name
- [x] incorrect search by `innm_id` - `e7dcaab1-be07-47a5-a939-01921da189a1`

Medication - Detail
- [x] incorrect label `ID форми` (ID торгівельної назви)
- [x] incorrect label `Країна виробник` (Країна виробництва, Виробник) (Країна, Виробник)
- [x] not found attr `is_active`
- [x] not found attr `package_qty`
- [x] not found attr `package_min_qty`
- [x] incorrect name `ingredients.name`
- [x] incorrect name `ingredients.name` at multi ingredients 
- [x] not found attr `ingredients.child_medication_id`	
	

Medication - Create
- [x] not refresh list (innm_dosage) in ingredients after creating innm_dosage
- [x] no visualisation creating errors

**Comment by danakonovalenko** [comment]
Get list 
- [ ] search doesn't work in case you are on some page and add name in filter.
Steps to reproduce: 
 ```
choose any page and add filter parameter 
```
- [ ] make translation for FORM (in case of INNM_DOSAGE we show English and make search by English name, in case of MEDICATIONS we show Ukrainian name, but search by English name)

INNMs - Create
- [ ] delete ID and one doubled row with SCTID

INNM_Dosage Create
- [ ] Change units (одиниці) in additional ingredients (first one is correct)
- [ ] Return from Deactivate page to Detail Page, now to Create page

Medication Сreate
- [ ] Change units (одиниці) in ingredients 
- [ ] Show Details page after create
