### ISSUE TITLE
Declaration Verification

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#1233]
It must be added additional verification for next objects [create declaration request](http://docs.uaehealthapi.apiary.io/reference/public.-medical-service-provider-integration-layer/declaration-requests/create-declaration-request):
- [x]  "person".documents[]
        "confidant_person". documents_person[]
         - 1 item for 1 type (DICT - DOCUMENT_TYPE)
- [x] "person". phones[]
       "emergency_contact".phones[]
       "confidant_person". phones[]
       - 1 item for 1 type  (MOBILE/LAND_LINE) 
- [x] "person".authentication_methods[] - 1 item for 1 type  and one of OTP/OFFLINE. If inputed both of them - show 422 error - 'Must be one and only one authentication method.'  
- [x] "confidant_person" - max 2 items with different  "relation_type"('PRIMARY', 'SECONDARY'), PRIMARY is required
- [x] "confidant_person".documents_relationship[] -  1 item for 1 type  (DICT - DOCUMENT_RELATIONSHIP_TYPE)
