### ISSUE TITLE
Fraud detection

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#1248]
In order to be able to detect fraud and block/unblock users next steps must be done:

- [x] Fraud db developing and test  #1260
- [x] BI Tool deployed and connected #1385
- [x] Reports Configured #1386
- [x] Block/Unblock User (BE) #1246
- [x] Block/Unblock MSP (BE) #1247
- [ ] Block/Unblock MIS 
- [x] Block/Unblock users NHS admin portal #1273
- [x] Block/Unblock MSPs Mithril admin portal #1276

**Comment by danakonovalenko** [comment]
@warehousman @Eugene Yesakov 
Please, review fraud db and fraud services specifications and provide feedback

**Comment by lymychp** [comment]
@pzhuk [HW sizing](https://edenlab.atlassian.net/wiki/spaces/EH/pages/152502606/MS+Power+BI+HW+requirements)
technical specification and overall diagram has been updated
