### ISSUE TITLE
Legal entities verifications

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#1249]
Create and update legal entities [apiary](http://docs.uaehealthapi.apiary.io/reference/internal.-partner-relationship-management/legal-entities/create-legal-entity):

- [x] addresses: no more than one address with one type 'Registration/Residence'
- [x] phones: no more than one phone with one type 'Mobile/Land_line'

**Comment by danakonovalenko** [comment]
@ybod also must be verified:

- [ ] owner.phones: no more than one phone with one type 'Mobile/Land_line'
- [ ] owner.documents: no more than 1 item/ 1 type
