### ISSUE TITLE
Fraud DB

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#1260]
Make new fraud db
- [x] Fraud db and mapping description [specs](https://edenlab.atlassian.net/wiki/x/AQCBAg)
- [x] Data Mart Developing
- [x] Data Mart test

**Comment by lymychp** [comment]
@vsirius  create new pod
