### ISSUE TITLE
Block/Unblock users NHS admin portal 

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#1273]
- [ ] There is must be a new page on NHS admin portal for search users by party_id.
Fields to filter:
```
 - user_id
 - party_id
```
- [ ] Grid fields:
```
- id
- user_id
- party_id
- last_name&first_name&second_name
- birth_date
```
- [ ] In order to be able to do that new service `Get Party users list` must be created  [apiary](http://docs.uaehealthapi.apiary.io/reference/internal.-nhs-admin/party-users/get-users-by-party_id-list) #1395

- [x] "Black list users" paragraph should be added to NHS admin portal:
- `Black list users lists` page
Fields to filter:
```
 - id 
 - tax_id
 - is_active
```
- [x]  Grid fields:
```
- id
- tax_id
- is_active
- details
```
- [x]  `Details` page
```
- id
- tax_id
- [last_name&first_name&second_name
- birth_date] - array
- is_active
- delete from black list
```
- [x]  `Add users to black list` page
```
 - tax_id
```
After the users was added show the page with details (same data as for detail page)

**Comment by danakonovalenko** [comment]
design:
```
https://www.dropbox.com/s/3rbr1784w2j7x8k/NSZ_admin_Users_Black_list.png?dl=0
https://www.dropbox.com/s/hzji10rvryq9b8h/NSZ_admin_Users_Black_list_add.png?dl=0
https://www.dropbox.com/s/vkcywidosd0k3gr/NSZ_admin_Users_Black_list_details.png?dl=0
```

**Comment by danakonovalenko** [comment]
design for Black list users:
```
https://www.dropbox.com/s/3rbr1784w2j7x8k/NSZ_admin_Users_Black_list.png?dl=0
https://www.dropbox.com/s/hzji10rvryq9b8h/NSZ_admin_Users_Black_list_add.png?dl=0
https://www.dropbox.com/s/vkcywidosd0k3gr/NSZ_admin_Users_Black_list_details.png?dl=0
```
