### ISSUE TITLE
Block/Unblock MSPs Mithril admin portal

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#1276]
- [x] to page `http://mithril.dev.ehealth.world/users` add search by ID 
- [ ] update `List Users` [apiary](https://mithrilapi.docs.apiary.io/reference/0/users/list-users)
- [x] to page `http://mithril.dev.ehealth.world/clients` add search by filters:
```
 - name
 - user_id
 - is_blocked
``` 
-  [x] Add field to existing list view
 ```
 - is_blocked
```
- [x] to detail (`http://mithril.dev.ehealth.world/clients/{id}`) page add fields:
```
 - is_blocked
 - block_reason
```
- [x] with possibility to edit and update them
- [ ] update services related to Clients [apiary](https://mithrilapi.docs.apiary.io/reference/0/clients/get-clients)

**Comment by danakonovalenko** [comment]
@AlexKovalevych please, update services mentioned above

**Comment by danakonovalenko** [comment]
@ivchenkodima we have a problem with a button in case the client is already blocked and we want to unblock it
![Screen Shot 2017-11-14 at 9.52.15 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59a3d716beb217001ad204a7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226455f76b7191a371f117294f5e5a5edd3c4a4356bcbbd671f3e57862804e0ee4d03c0b75933512aabdd649b801bb23d81b84e7ea891dd2f42f67b6d5db1063474f4dcbed5727a19e41c95df74be74950ad153e63ef752431.png)

**Comment by ivchenkodima** [comment]
Done
