### ISSUE TITLE
Add `legal_entity_id` into `medication_requests`

### ISSUE THREAD

**Issue by EdwardVoloshin** [edenlabllc/ehealth.api#1317]
As a NHS admin 
I want get list MRs filter by legal_entity_id  
So that need add `legal_entity_id` into `medication_requests`.

- [x] change DB: add column `legal_entity_id` into `medication_requests`
- [x] migration DB: fill `legal_entity_id` for exists MRs
- [x] change WS logic `Create_MRR`: store `legal_entity_id` in DB
- [x] change logic all MR WS for prepare response: get `legal_entity_id`direct from DB
- [x] add new parameters `legal_entity_id` in WS `Get_MR_List`
------
- [x]  Update WS spec, update ERD
- [x]  Implement
- [x]  Deploy
- [x]  Improve test scenarios

**Comment by svetavedmed** [comment]
Don't have filters for `get MR list` by `legal_entity_id`
