### ISSUE TITLE
Public Name from Legal Entity request should be saved and reused

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#1331]
Each LE create/update request is signed with Digital Signature, where public name is available.
We have to save this property into LE database altogether with manually entered names (official,public, short).

For capitation reporting - there should be a flexible configurable option of name selection. Any of naming convention could be selected before building reports.

- [ ] save to the prm new name from the DS - legal_entity.full_name field
- [ ] manually entered name should be moved to new field - manual_name
- [ ] no migration for the existing LE
- [ ] Update client name on Mithril
