### ISSUE TITLE
NHS Admin Portal- Medications bugs - part 2

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#1344]
***Medical Program***

- [x] search is not correct
- [x] there is no Details page 
- [x] there is no Create program page

***Program Medications***

- [x] there is no search

Detail page 
- [x] in paragraph 'Торгова назва' incorrect dosage 
- [x] change 'Ціна' to 'Сума відшкодування'
- [x] no visualisation creating errors

**Comment by ivchenkodima** [comment]
https://github.com/edenlabllc/nhs.admin.web/pull/63

**Comment by danakonovalenko** [comment]
***Medical programs***
List page
- [ ] doesn't work search by name
- [ ] doesn't work search not from 1st page
- [ ] filter by active first, inactive at the end of list

Detail page
- [ ] change button name 'Деактивувати торгову назву' to 'Деактивувати медичну програму'
- [ ] after deactivate return to Detail page (to see that program was deactivated)

Create page
- [ ] after create now it is shown  'Сторінка не знайдена', should be Details page

***Program medications***

List page
- [ ] rename headers
Назва сполуки to Торгова Назва
Форма сполуки to Форма 
Кількість to Сума Відшкодування 
Активен to Активний
- [ ] delete from filter search by ID 
- [ ] rename filter by innm_id to за ID Лікарської форми (we send innm_dosage_id in URL)
- [ ] rename filter by МНН to за Назвою Лікарської форми (we send innm_dosage_name in URL)

Detail page
- [ ] after editing Повернутись до списку учасників програм don't return to List
- [ ] in editing show only one type Фіксована
- [ ] in Редагувати paragraph change 'Ціна' to 'Сума відшкодування'

Create page 
- [ ] change 'Ціна' to 'Сума відшкодування'
- [ ] тип must be set by default Фіксована (user don't input)
- [ ]  after editing Повернутись до списку учасників програм don't return to List
