### ISSUE TITLE
SMS delivery metrics (BE)

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#1374]
There are must be predefined metrics related to SMS process. In order to be able to calculate it we need to store counters and log info to verification.sms_logs
- [ ] delete from table verification.verifications fields gateway_id and gateway_status
- [ ] replicate to table verification.sms_log next data from verification.verifications (attempts_count=0) [confluence](https://edenlab.atlassian.net/wiki/x/t4JgBQ)
 - phone_number
 - body (fixed "VERIFICATION") 
 - gateway_id
 - gateway_status
 - inserted_at
- [ ] add to verification.sms_log fields:
- updated_at
- status_changed_at
- [ ] set up a job according to requirements [confluence](https://edenlab.atlassian.net/wiki/x/zoJgBQ)

**Comment by danakonovalenko** [comment]
status_changed_at must be taken from response
```
<status id="ид сообщения" date="Wed, 28 Mar 2007 12:35:00 +0300">
<state>Delivered</state>
</status> 
```
not the time of cron job

**Comment by danakonovalenko** [comment]
based on source of SMS add to table sms_logs column "type" - as for now: 'Verification' and 'Medication request'
