### ISSUE TITLE
Fraud Reports 

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#1386]
After BI is deployed and connecter reports must be configured and logic must be described.

- [x] Describe Logic on Confluence
- [x] Number of patients per doctor
- [x] Number of patients registered for the same phone number
- [x] Number and percentage of patients per doctor that have set offline authorization method
- [x] Number and percentage of patients per legal entity that have set offline authorization method
