### ISSUE TITLE
declaration review process is not showing expected documents

### ISSUE THREAD

**Issue by pzhuk** [edenlabllc/ehealth.api#1428]
На адмін порталі, в процесі перегляду декларації(або  деклараці на розгляді) ніколи не зрозуміло, чи була якась вимога завантажити скани документів.

Тобто, якщо документи потрібні були, але не були додані де-факто - в перегляді чи розгляді такої декларації все виглядатиме як нормале.

Наприклад, розгляд декларації для дитини, або людини з опікуном не показує 
- а ні наявного опікуна
- а ні вимог по документах

Фактично , не можна зробити висновок чи є всі необхідні підстави прияйняти чи відхилити такую декларацію в процесі розгляду.

Очікуване рішення:

адмін портал має показувати як список документів, які вимагалися, так і список документів які фактично були надані.

cc: @kmakarenko

**Comment by lymychp** [comment]
@pzhuk please provide information how the described case can be reproduced

For future tickets please try to follow the below template.
Thanks.
```
## Steps to Reproduce (Repro steps)
- [ ] environment or endpoint address
- [ ] preconditions if any
- [ ] sequence of actions that should be taken to reproduce the behavior.
- [ ] test data, requests examples, json files, curl requests, screenshots, etc

## Actual result
- [ ] response example or screenshot

## Expected result
- [ ] description of the expected system behavior.
```

**Comment by pzhuk** [comment]
@lymychp 

environment: prod
preconditions: declaration has been created with any of online/offline process AND some scans has been requested to be uploaded by user

Expected result: list of documents during the process requested MUST be seen on the NHS portal at declaration review page

Current result: declaration review process is not showing expected documents, so it's not possible to understand if user has uploaded everything which was requested!

**Comment by lymychp** [comment]
related to #1365
