### ISSUE TITLE
NHS admin review

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#1441]
In NHS admin portal next changes must be done:
- [x] МНН after create "Повернутися до списку МНН" must return to list
- [x] add button  "Повернутися до списк" to МНН detail page
- [x] add on the page "Create Торгова назва paragraph Ⅲ. Упаковка" the row "Контейнер"
- [x] increase width for the field Ⅲ. Упаковка Кількість
- [x] change holder from Дата закінчення сертифікату from dd/mm/yyyy to yyyy-mm-dd
- [x] rename Ⅲ. Сертифікат to Реєстраційне посвідчення
- [x] rename Торгова назва to Торгівельне найменування
- [x] rename "Дозвіл на відпуск рецептів" to "Дозвіл на створення рецептів"

**Comment by danakonovalenko** [comment]
- [ ] Create Торговельне найменування  Форма: form must be mapped and translated 
- [ ] add button "Повернутися до спискy" to МНН detail page
- [ ] rename Create Торговельне найменування  V. Реєстраційне посвідчення:  Номер сертифікату - Номер реєстраційного посвідчення
Дата закінчення сертифікату - Дата закінчення реєстраційного посвідчення
- [ ] close data picker after the date was chosen
