### ISSUE TITLE
 WS.Create User (Modification)

### ISSUE THREAD

**Issue by EdwardVoloshin** [edenlabllc/ehealth.api#1450]
WS.Create User

- [x] Create WS [spec](https://edenlab.atlassian.net/wiki/x/SwAZCQ)
- [x]  Implement
- [x]  Deploy
- [x]  Improve test scenarios

**Comment by svetavedmed** [comment]
1. The field `priv_settings` is empty for new users
2. If I create new user with 2fa_enable = FALSE, i still have a record in authentication_factors.
according to specs: If $.2fa_enable = FALSE - break

**Comment by PavelVesnin** [comment]
@svetavedmed deployed

**Comment by svetavedmed** [comment]
1. fixed
2. the same

**Comment by EdwardVoloshin** [comment]
- [ ] Please del `id` from `privilege_settings` after create user
- [ ] Don't work default value (from config) for 2FA

**Comment by EdwardVoloshin** [comment]
test passed
