### ISSUE TITLE
WS: UnBlockUser (new EP)

### ISSUE THREAD

**Issue by EdwardVoloshin** [edenlabllc/ehealth.api#1453]
WS: UnBlockUser (new EP)

- [x]  Create WS [spec](https://edenlab.atlassian.net/wiki/x/DgAaCQ)
- [x]  Implement
- [x]  Deploy
- [x]  Improve test scenarios

**Comment by EdwardVoloshin** [comment]
Test done.

**Comment by EdwardVoloshin** [comment]
- [ ] add logic: clear counters `{"otp_error_counter": 0, "login_error_counter": 0}`

**Comment by PavelVesnin** [comment]
@EdwardVoloshin deployed

**Comment by EdwardVoloshin** [comment]
clear counter fixed.

**Comment by EdwardVoloshin** [comment]
@PavelVesnin 
- [ ] add optional parameter `reason`+ add processing

**Comment by PavelVesnin** [comment]
@EdwardVoloshin deployed
