### ISSUE TITLE
WS: BlockUser (new EP)

### ISSUE THREAD

**Issue by EdwardVoloshin** [edenlabllc/ehealth.api#1454]
WS: BlockUser (new EP)

- [x]  Create WS [spec](https://edenlab.atlassian.net/wiki/x/EgAaCQ)
- [x]  Implement
- [x]  Deploy
- [x]  Improve test scenarios

**Comment by EdwardVoloshin** [comment]
Don't save `block_reason`

**Comment by EdwardVoloshin** [comment]
Reason save correctly.

**Comment by EdwardVoloshin** [comment]
Test done.

**Comment by EdwardVoloshin** [comment]
- [ ] with incorrect request body - WS return 500, need validate structure & return 422
`curl -X PATCH \
  https://dev.ehealth.world/admin/users/1e19d96d-c3fe-4df9-9a4e-9e44dfe69cdd/actions/block \
  -H 'authorization: Bearer dnpibWVPbld4bkg4aFBQRHJOVU9Odz09' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: 0600f3cf-d2dd-949c-f926-2484a9ebe54f' \
  -d '{
  "user" : [{}]
}'`
- [ ] add logic deactivate users token

**Comment by PavelVesnin** [comment]
@EdwardVoloshin deployed

**Comment by EdwardVoloshin** [comment]
@PavelVesnin - Im add comment ->  with all `grant_type`.

**Comment by PavelVesnin** [comment]
@EdwardVoloshin deployed

**Comment by EdwardVoloshin** [comment]
DONE
