### ISSUE TITLE
WS: Create Token (Modification)

### ISSUE THREAD

**Issue by EdwardVoloshin** [edenlabllc/ehealth.api#1455]
WS: Create Token (Modification)

- [x]  Create WS [spec](https://edenlab.atlassian.net/wiki/x/aAAZCQ)
- [x]  Implement
- [x]  Deploy
- [x]  Improve test scenarios

**Comment by EdwardVoloshin** [comment]
Add specs link at task.

**Comment by EdwardVoloshin** [comment]
- [ ] case- invalid password (need first increment counter, second check MAX & blocked). Now counter =2 & user is blocked.
- [ ] after unblock user & correct login - need clear (=0) `login_error_counter`. Now is still last value.
- [ ] add 2fa_access_token in logic process expiration token

**Comment by EdwardVoloshin** [comment]
- [ ] case "create_OTP" - set length OTP = OTP_LENGTH = 4. Now length OTP = 6
- [ ] case "verify_OTP" - send incorrect OTP: no incrementing counter in OTP user (`attempts_count`) + not blocked user

**Comment by EdwardVoloshin** [comment]
- [ ] 500 err. Case: Reset 2FA, call create_token(type=password), call create_token(type=authorize_otp). Response: `{"meta":{"url":"http://dev.ehealth.world/oauth/tokens","type":"object","request_id":"jt5br7l77ivvu0s28sg2qisu6qa0r2ba","code":500},"error":{"errors":{"detail":"Internal server error"}}}`

**Comment by PavelVesnin** [comment]
@EdwardVoloshin please, send example of request for 500 error.
Another cases fixed and deployed

**Comment by EdwardVoloshin** [comment]
- [ ] Case: Reset 2FA. Then call create_token(type=password). Then call create_token(type=**refresh_2fa_access_token**).   Response = 201 + `"urgent": {
        "next_step": "REQUEST_OTP"    },`.  Need return 422

**Comment by PavelVesnin** [comment]
@EdwardVoloshin fixes deployed

**Comment by EdwardVoloshin** [comment]
current tests & cases - done.

**Comment by EdwardVoloshin** [comment]
- [ ] add logic for `2fa_access_token` - not proxy scopes from payload into token.details (must be `"scopes": ""`)
- [ ] add handling processing : first validate user is block, then validate token expired.

**Comment by PavelVesnin** [comment]
@EdwardVoloshin deployed
