### ISSUE TITLE
 WS: Init User Factor (New EP)

### ISSUE THREAD

**Issue by EdwardVoloshin** [edenlabllc/ehealth.api#1459]
WS: Request User Factor

- [x]  Create WS [spec](https://edenlab.atlassian.net/wiki/x/PwAXCQ)
- [x]  Implement
- [x]  Deploy
- [x]  Improve test scenarios

**Comment by EdwardVoloshin** [comment]
add specs link

**Comment by EdwardVoloshin** [comment]
- [ ] after call WS - old token not terminated. See `exp_t` column:
`exp_t | id | name | value
-- | -- | -- | --
2017-12-23 14:19:56.000000 | 1cf6e64a-4e31-48e1-abe8-b184de967cb3 | 2fa_access_token | WjY0dFdXc1RqVUVadytVUTZrYlJOZz09
2017-12-23 14:11:40.000000 | d4aa787c-ba34-4af1-9843-0d4331643792 | 2fa_access_token | L0JIZDdNRkZKZGhETzM3bTJEVWw1UT09
`

**Comment by PavelVesnin** [comment]
@EdwardVoloshin deployed

**Comment by EdwardVoloshin** [comment]
tests passed

**Comment by EdwardVoloshin** [comment]
@PavelVesnin 
- [ ] in case problem with send SMS - return 424 err

**Comment by PavelVesnin** [comment]
I read about response codes in case, when external API doesn't respond correctly and decided to use 503 response code - it's better describes what's going on. 
So @EdwardVoloshin can change specs.

**Comment by PavelVesnin** [comment]
@EdwardVoloshin deployed
