### ISSUE TITLE
PROC: [AUTO] Terminate OTP (new PROC)

### ISSUE THREAD

**Issue by EdwardVoloshin** [edenlabllc/ehealth.api#1460]
PROC: [AUTO] Terminate OTP (new PROC)

- [x]  Create WS [spec](https://edenlab.atlassian.net/wiki/x/QwAXCQ)
- [x]  Implement
- [x]  Deploy
- [ ]  Improve test scenarios

**Comment by EdwardVoloshin** [comment]
- [ ] set status `EXPIRED` only for expired item in status = `NEW`

**Comment by PavelVesnin** [comment]
@EdwardVoloshin deployed

**Comment by EdwardVoloshin** [comment]
@PavelVesnin - incorrect work.
Still otp item in status `NEW` with expired_at yesterday.
<img width="847" alt="screen shot 2017-11-24 at 10 45 49 am" src="https://user-images.githubusercontent.com/30432256/33202312-c69210a0-d104-11e7-8499-dafd07c72d4b.png">

**Comment by EdwardVoloshin** [comment]
bug fixed
