### ISSUE TITLE
WS: Get user 2FA List (new EP)

### ISSUE THREAD

**Issue by EdwardVoloshin** [edenlabllc/ehealth.api#1461]
WS: Get user 2FA List (new EP)

- [x]  Create WS [spec](https://edenlab.atlassian.net/wiki/x/RwAXCQ)
- [x]  Implement
- [x]  Deploy
- [x]  Improve test scenarios

**Comment by EdwardVoloshin** [comment]
add Partial masked attribute `factor` in response,
 example: 
` "factor": "+38067*****67",`

**Comment by EdwardVoloshin** [comment]
- [ ] expected scope validation `authentication_factor:read`

**Comment by EdwardVoloshin** [comment]
test passed

**Comment by EdwardVoloshin** [comment]
@AlekzandrV must change GW config for same routines.
