### ISSUE TITLE
WS: Approve User Factor (new EP)

### ISSUE THREAD

**Issue by EdwardVoloshin** [edenlabllc/ehealth.api#1484]
WS: Approve User Factor

- [x]  Create WS [spec](https://edenlab.atlassian.net/wiki/x/SwFZCQ)
- [x]  Implement
- [x]  Deploy
- [ ]  Improve test scenarios

**Comment by EdwardVoloshin** [comment]
- [ ] incorrect OTP counter ... case:  when 2 time call Approve with bad otp value - I have attempts_counter = 2. Then I call Approve with good otp value - I have status otp = verified, but attempts_counter = 1!  (but in other cases I have verified+ attempts_counter = 3)
<img width="340" alt="screen shot 2017-11-23 at 4 07 53 pm" src="https://user-images.githubusercontent.com/30432256/33176825-19e0a600-d069-11e7-9cfa-1ac772d43a89.png">

**Comment by PavelVesnin** [comment]
@EdwardVoloshin deployed

**Comment by EdwardVoloshin** [comment]
tests passed
