### ISSUE TITLE
auth.ehealth/sign-in/: modify "login" page

### ISSUE THREAD

**Issue by EdwardVoloshin** [edenlabllc/ehealth.api#1485]
auth.ehealth/sign-in/: modify "login" page:
**Summary:**
- [x]  add button "змінити додатковий фактор авторизації"
- after call "POST Tokens" read response "urgent.next" and switching logic:
   - [x]  REQUEST_APPS - go to next page "Approvals" 
   - [x]  REQUEST_OTP - go to page "authorize with top"
   - [x]  REQUEST_FACTOR - go to separate process "request & approve factor"
- [x]  Create [spec](https://edenlab.atlassian.net/wiki/x/cYCSCQ) for FE task
- [x]  Create design layout
- [x]  Implement
- [x]  Deploy
- [x]  Test

**Comment by EdwardVoloshin** [comment]
done
