### ISSUE TITLE
mithril.admin: Modify "user-details" page

### ISSUE THREAD

**Issue by EdwardVoloshin** [edenlabllc/ehealth.api#1491]
mithril.admin: Modify "user-details" page : 

**group: user info**
- [x] add button "Block user"("Блокувати користувача") with call [WS Block+User](https://edenlab.atlassian.net/wiki/spaces/EH/pages/152698898/Block+User) with possibility input `block_reason` string
- [x] add button "Unblock user"("Розблокувати користувача") with call [WS Unblock+User](https://edenlab.atlassian.net/wiki/spaces/EH/pages/152698894/Unblock+User) 
- [x] add label "is_blocked info" (Користувач заблокований/Користувач розблокований)

**NEW group: Додаткові фактори аутентифікації**
- [x] add grid/list with call [WS Get+user+2FA+List](https://edenlab.atlassian.net/wiki/spaces/EH/pages/152502343/Get+user+2FA+List) with column (type, factor, is_active, updated_at, ACTIONs list)
- [x] add ACTION "Зкинути фактор" with call WS [Reset+User+2FA](https://edenlab.atlassian.net/wiki/spaces/EH/pages/152633434/Reset+User+2FA)
- [x] add ACTION "Вимкнути фактор" with call WS [Disable+User+2FA](https://edenlab.atlassian.net/wiki/spaces/EH/pages/152633426/Disable+User+2FA)
- [x] add ACTION "Ввімкунти фактор" with call WS [Enable+User+2FA](https://edenlab.atlassian.net/wiki/spaces/EH/pages/152633430/Enable+User+2FA)
- [x] add button "Create factor"("Створити фактор") with call WS [Create+User+2FA](https://edenlab.atlassian.net/wiki/spaces/EH/pages/152502331/Create+User+2FA) with type=`SMS`

**Comment by EdwardVoloshin** [comment]
reopen

**Comment by EdwardVoloshin** [comment]
All tasks & description insert into this task. 
Im killed task #1493 , #1492, & set size=6 for this task.

**Comment by EdwardVoloshin** [comment]
@ivchenkodima 
- [ ] rename `СМС` -> `SMS` on dialog create factor
- [ ] show date+**time** in column `оновлено` of factor table

**Comment by EdwardVoloshin** [comment]
done
