### ISSUE TITLE
Mithril : fix `refresh_token` power

### ISSUE THREAD

**Issue by EdwardVoloshin** [edenlabllc/ehealth.api#1535]
Now with non-expired `refresh_token` I could call any EP - its a gap on security.
I want fix this.  So that:
- [x]  remove all scopes (except `token:write`) from `token.details` for `refresh_token`
- [x]  at WS: Create_token implementation logic for case `refresh token` - seek scopes list not in `token.details`, but seek in `apps` for user_id+client_id

**Comment by EdwardVoloshin** [comment]
@PavelVesnin 
- [ ] after call: refresh_token() expect terminate "old" access_token

**Comment by EdwardVoloshin** [comment]
test passed
