### ISSUE TITLE
NHS portal content management admin panel

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#1564]
As a NHS PR manager
I want to be able to manage the content on NHS Portal without involvement of the software engineer
So that I can make it faster and cheaper.
[high-level description](https://docs.google.com/document/d/1QyS3oetSuCV1ViQ9wIUvHc8FY3hlEgHge67BZpXGELU/edit)

- [ ] Implement backend (#1611)
- [ ] Define database schema (#1614)
- [ ] Implement portal frontend (#1613)
- [ ] Implement admin frontend (#1612)

**Comment by lymychp** [comment]
not relevant anymore
