### ISSUE TITLE
Create employee request (no_tax_id)

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#1571]
- [ ] add field to prm.parties: 'no_tax_id' (boolean)
- [ ] If no_tax_id=true then generate upload URL
- [ ] Save documents to storage
- [ ] Check that at least one document was upload
[confluence](https://edenlab.atlassian.net/wiki/x/SKUO)

**Comment by PavelVesnin** [comment]
@danakonovalenko deployed

**Comment by svetavedmed** [comment]
1. with "no_tax_id": true can not register employee
request
```
curl -X POST \
  https://dev.ehealth.world/api/employee_requests \
  -H 'Authorization: Bearer cHlYUVE1bmI4SnRiV24zV3AwaE1GZz09' \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: 4a0ce955-147d-b7c4-6969-547d0ab6794b' \
  -H 'api-key: UXhEczJacXh3Ri9SUkc4enhHTVVpQT09' \
  -d '{
  "employee_request": {
    "position": "P2",
    "start_date": "2016-03-02",
    "status": "NEW",
    "employee_type": "DOCTOR",
    "division_id": "871bb964-6845-46cc-a598-126bc05b730c",
    "party": {
      "first_name": "dcdcd",
      "last_name": "cdcdc",
      "second_name": "cdscdsc",
      "birth_date": "1983-07-12",
      "gender": "MALE",
      "tax_id": "FF123456",
      "no_tax_id": true,
      "email": "svetavedmed+190@gmail.com",
      "documents": [
        {
          "type": "PASSPORT",
          "number": "120518"
        }
      ],
      "phones": [
        {
          "type": "MOBILE",
          "number": "+380503410870"
        }
      ]
    },
    "doctor": {
      "educations": [
        {
          "country": "UA",
          "city": "Київ",
          "institution_name": "Академія Богомольця",
          "issued_date": "2017-08-05",
          "diploma_number": "DD123543",
          "degree": "MASTER",
          "speciality": "Педіатр"
        }
      ],
      "qualifications": [
        {
          "type": "STAZHUVANNYA",
          "institution_name": "Академія Богомольця",
          "speciality": "Педіатр",
          "issued_date": "2017-08-05",
          "certificate_number": "2017-08-05"
        }
      ],
      "specialities": [
        {
          "speciality": "FAMILY_DOCTOR",
          "speciality_officio": true,
          "level": "FIRST",
          "qualification_type": "AWARDING",
          "attestation_name": "Академія Богомольця",
          "attestation_date": "2017-08-05",
          "valid_to_date": "2017-08-05",
          "certificate_number": "AB/21331"
        }
      ],
      "science_degree": {
        "country": "UA",
        "city": "Київ",
        "degree": "DOCTOR_OF_SCIENCE",
        "institution_name": "Академія Богомольця",
        "diploma_number": "DD123543",
        "speciality": "THERAPIST",
        "issued_date": "2017-08-05"
      }
    }
  }
}'
```
response
```
{
    "meta": {
        "url": "http://api-svc.il/api/employee_requests",
        "type": "object",
        "request_id": "e99adc4b-c90f-4a90-b8a5-87817d70fa57#141",
        "code": 422
    },
    "error": {
        "type": "validation_failed",
        "message": "Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.",
        "invalid": [
            {
                "rules": [
                    {
                        "rule": "format",
                        "params": [
                            "^[0-9]{10}$"
                        ],
                        "description": "string does not match pattern \"^[0-9]{10}$\""
                    }
                ],
                "entry_type": "json_data_property",
                "entry": "$.employee_request.party.tax_id"
            }
        ]
    }
}
```

**Comment by danakonovalenko** [comment]
when create OWNER through legal_entity request we always set no_tax_id=false.
If no_tax_id=true show validaition error 422 with message 'no_tax_id=true is not allowed for OWNER'
