### ISSUE TITLE
WS related to Party (no_tax_id)

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#1577]
Update all services related to Party (add field 'no_tax_id')
- [x] Create new party [apiary](https://uaehealthapi.docs.apiary.io/reference/internal.-partner-relationship-management/party/create-new-party)
- [x] Update Party [apiary](https://uaehealthapi.docs.apiary.io/reference/internal.-partner-relationship-management/party/update-party)
- [x] List Search for party [apiary](https://uaehealthapi.docs.apiary.io/reference/internal.-partner-relationship-management/party/search-for-party)
- [x] Get Party details [apiary](https://uaehealthapi.docs.apiary.io/reference/internal.-partner-relationship-management/party/get-party-details)

**Comment by PavelVesnin** [comment]
@danakonovalenko nothing to do
