### ISSUE TITLE
Portal CMS backend

### ISSUE THREAD

**Issue by kiurchv** [edenlabllc/ehealth.api#1611]
- [ ] Make proof-of-concept back-end
- [ ] Apply DB schema
- [ ] Implement authentication (mithril integration)
- [ ] Implement file handling (ael integration)

**Comment by lymychp** [comment]
not relevant anymore
