### ISSUE TITLE
Portal admin frontend

### ISSUE THREAD

**Issue by ivchenkodima** [edenlabllc/ehealth.api#1612]
General requrements: https://docs.google.com/document/d/1QyS3oetSuCV1ViQ9wIUvHc8FY3hlEgHge67BZpXGELU/edit

## 1. Scaffolding

- [x] Bootstrap
- [x]  Pages/Routes

## 2. Forms

- [x]  State handling
- [x]  Validation
- [x]  Inputs UI decoupling
- [x]  Custom inputs(Draft.js/Slate)

## 3. Static pages

- [x] Models list
- [x] Model create
- [ ] Model details

## 4. Parametric pages

- [x] List
- [x] Create
- [x] Details
- [x]  Dynamic queries
- [x]  Dynamic navigation
- [x]  Route hooks

## 5. UI components

- [x]  Layout, Nav
- [x]  Table / TableView
- [x]  Pagination(Decouple UI from logic)

## 6. Backend flow

- [x]  GraphQL querying
- [ ]  Authentication
- [ ]  File uploads

**Comment by lymychp** [comment]
not relevant anymore
