### ISSUE TITLE
 Implement portal frontend

### ISSUE THREAD

**Issue by ivchenkodima** [edenlabllc/ehealth.api#1613]
- [ ] Bootstrap frontend
- [ ] Setup pages and routing
- [ ] Migrate components from previous app
- [ ] Integrate data flow with API

**Comment by lymychp** [comment]
not relevant anymore
