### ISSUE TITLE
no_tax_id additional verifications

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#1638]
- [x] In Employee Request and Create legal_entity make field 'no_tax_id' optional (set false by default)
- [x] for Create legal_entity if 'no_tax_id'=true answer with 422 verification error 'no_tax_id must be false'
- [x] for Employee_request if no_tax_id=false check that tax_id has next pattern: ^[0-9]{10}$
- [x] for Employee_request if no_tax_id=true check that tax_id has next pattern: ^([0-9]{9}|[А-ЯЁЇIЄҐ]{2}\d{6})$
