### ISSUE TITLE
MPI candidates merge

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#1674]
- [ ] In the process of candidates merge (on MPI) there is no clear why few persons were merged, though they shouldn't have been.
example (on prepared)
```
select * from persons
where id in('232e9dd7-0930-4e60-bc71-21b552e78583', 
'016a6c63-18e5-48c6-88d2-83e7ddecdb6d')
;
```
-   [ ] after the candidates were merged only one should have status='active'. the rest must have status='inactive'. As for now the status remains the same.

**Comment by gmile** [comment]
For ease of debugging, here are the records in question:

```
select tax_id, first_name, last_name, second_name, birth_date, documents, national_id, phones from persons where id in('232e9dd7-0930-4e60-bc71-21b552e78583', '016a6c63-18e5-48c6-88d2-83e7ddecdb6d');
-[ RECORD 1 ]---------------------------------------------------------
tax_id      |
first_name  | Сергій
last_name   | Закусило
second_name | Євгенович
birth_date  | 2007-12-18
documents   | [{"type": "BIRTH_CERTIFICATE", "number": "11111111111"}]
national_id |
phones      | [{"type": "MOBILE", "number": "+380965992121"}]
-[ RECORD 2 ]---------------------------------------------------------
tax_id      |
first_name  | Діана
last_name   | Закусило
second_name | Петрівна
birth_date  | 2017-11-11
documents   | [{"type": "BIRTH_CERTIFICATE", "number": "456789"}]
national_id |
phones      | [{"type": "MOBILE", "number": "+380639368040"}]

```

**Comment by gmile** [comment]
Fixes in https://github.com/edenlabllc/mpi.api/commit/4a0621fcee9bc64e47bfc9d09a0a862802d33fd2 and https://github.com/edenlabllc/mpi.api/commit/ad7607bbf93bd0477063e003a66bd4a41e6c2412 respectively.

@danakonovalenko this is deployed on dev. Please, test and re-open the issue if needed.

**Comment by danakonovalenko** [comment]
- [ ] 2 candidates with score=0.6 were merged 
```
select * from persons
where id in('cb1b1cd0-7f40-4719-a320-fb24cc5403fa', 'ea5e6d59-3f93-40f5-b312-4ff0f359572f')
```
- [ ] there is a duplication in field `"merged_ids"`
```
select merged_ids from persons
where id ='9473f00a-d9be-412c-ad0a-69aff38be03a'
```
- [ ] in case `person1` was merged with `person2` field merged_ids for person2 must be `[id_person1]`
and if after that `person2` was merged with `person3` - merged_ids for person3 must be `[id_person1, id_person2]`

**Comment by gmile** [comment]
- [x] 2 candidates with score=0.6 were merged – **fixed**
- [x] there is a duplication in field "merged_ids" – **can't reproduce**
- [x] <s>in case `person1` was merged with `person2` field merged_ids for person2 must be `[id_person1]`
and if after that `person2` was merged with `person3` - merged_ids for person3 must be `[id_person1, id_person2]`</s> no need to do this, as discussed
