### ISSUE TITLE
Change Password design FE

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#1700]
As a user I want steps to change password to be more clear.
For this we need to inform user about each step of change password flow (this steps must be in color and easy to read) (depends on flow there are 2 or 4 screen for the user)

 - [x] `Крок 1: введіть електронну адресу та старий пароль`
change `ВХІД У СИСТЕМУ EHEALTH` to `Авторизація для зміни пароля`
- [x] `Крок 2: введіть номер телефону`
- [x] `Крок 3: введіть код, що прийшов на телефон`
- [x] `Крок 4: введіть новий пароль та підтверідть його`
