### ISSUE TITLE
Update Legal Entity Model

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#1721]
- [x]  review Legal Entity data model
- [x] updated [apiary](https://uaehealthapi.docs.apiary.io/reference/public.-medical-service-provider-integration-layer/legal-entities/create/update-legal-entity), json schemas:
- [ ] need to add optional  fields
``` 
 - website
 - receiver_funds_code
 - archive: (array) 
     - date
     - place
 - beneficiary
```

**Comment by PavelVesnin** [comment]
@danakonovalenko deployed

**Comment by danakonovalenko** [comment]
There is no fields in response:
```
"updated_by": "53d781f1-8a32-484c-8b13-b82659e03f22",
        "updated_at": "2018-01-22T13:13:44.335366",
        "type": "MSP",
        "status": "ACTIVE",
        "short_name": "Лимич Медікал",
        "public_name": "Лимич Медікал",
        "phones": [
            {
                "type": "MOBILE",
                "number": "+380979134223"
            }
        ],
        "owner_property_type": "STATE",
        "nhs_verified": true,
        "name": "Клініка Лимич Медікал",
        "mis_verified": "NOT_VERIFIED",
        "medical_service_provider": {
            "licenses": [
                {
                    "what_licensed": "реалізація наркотичних засобів",
                    "order_no": "К-123",
                    "license_number": "fd123443",
                    "issued_date": "1991-08-19",
                    "issued_by": "Кваліфікацйна комісія",
                    "expiry_date": "1991-08-19",
                    "active_from_date": "1991-08-19"
                }
            ],
            "accreditation": {
                "order_no": "fd123443",
                "order_date": "1991-08-19",
                "issued_date": "1991-08-19",
                "expiry_date": "1991-08-19",
                "category": "FIRST"
            }
        },
        "legal_form": "140",
        "kveds": [
            "86.10",
            "81.21",
            "47.73"
        ],
        "is_active": true,
        "inserted_by": "53d781f1-8a32-484c-8b13-b82659e03f22",
        "inserted_at": "2017-12-01T13:25:29.121230",
        "id": "c8aadb87-ecb9-41ca-9ad4-ffdfe1dd89c9",
        "email": "lymychp@gmail.com",
        "edrpou": "3160405192",
        "addresses": [
            {
                "zip": "02090",
                "type": "REGISTRATION",
                "street_type": "STREET",
                "street": "вул. Ніжинська",
                "settlement_type": "CITY",
                "settlement_id": "fb5e6f07-0c2d-4c5c-8bc5-f0b86bb94494",
                "settlement": "ЧУГУЇВ",
                "country": "UA",
                "building": "15",
                "area": "ХАРКІВСЬКА",
                "apartment": "23"
            }
        ]
```
though they are in database
![Screen Shot 2018-01-22 at 3.16.46 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59a3d716beb217001ad204a7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226456f16b7191a37bf1132d4f5b595ecc3c4a4356bcbbd671f3e57862804e0ee4d03c0b75933512aabdd649b801bb23d81b84e7ea891dd2f42f67b6d5db1063474f4dcbed5727a19e41c95df74de74f52a4173365e5752431.png)

**Comment by PavelVesnin** [comment]
@danakonovalenko what request?

**Comment by danakonovalenko** [comment]
``` "request_id": "a5793e90-9348-4770-9adc-1b8b03fe5cdb#9599"```

**Comment by PavelVesnin** [comment]
I'm asking about cURL of request. 
Add cURL when you posting invalid response, please

**Comment by danakonovalenko** [comment]
request curl:
```
curl -X PUT \
  https://dev.ehealth.world/api/legal_entities \
  -H 'authorization: Bearer dW1raDd2TkdZdVZYSklnU0V0WGxqZz09' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'edrpou: 3160405192' \
  -H 'postman-token: ac594928-3fb9-8b49-1791-365063aa7f47' \
```

**Comment by PavelVesnin** [comment]
@danakovalenko deployed
