### ISSUE TITLE
Review Declaration Data Model

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#1722]
Update declaration model according to new requirements:
- [ ] add preferable way of communication with a patient (phone, email) 
- [ ] clarify what to do with authentication methods 
- [ ] review doctor information in declaration (tax_id, birth_date)
- [ ] add declaration termination reason
