### ISSUE TITLE
Declaration Request Flow changes

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#1725]
According to new requirements current Declaration Request flow must be reviewed and changed:
- [x] Review Declaration Data Model #1722
- [x] Declaration Request Offline (attach documents)  #1723
- [x] Declaration Digital Signature #1724
