### ISSUE TITLE
Append only logs

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#1727]
To improve security next tasks must be done:
- [ ] audit log must be stored separately with limited access to it and without right to change or delete them
- [ ] logs must be archived and not deleted

**Comment by Troush** [comment]
– [ ] Create new google cloud account for Audit Logs dump

**Comment by gmile** [comment]
So as far as I understand, here's the plan:

- [ ] create a new Google account,
- [ ] bootstrap a blank new VM instance (or kubernetes),
- [ ] install a PostgreSQL on that instance,
- [ ] create "big audit log DB" database,
- [ ] in "big audit log DB", create tables that reflect respective audit tables from select microservices (list to be determined),
- [ ] (?) setup log replication from source audit table to respective destination audit table,
  - via native psql mechanisms, or via a script,
- [ ] create a "log_db_archive" bucket,
- [ ] setup daily "big audit log DB" data dump into "log_db_archive" bucket,
- [ ] setup daily test scripts to verify "log DB" data dumps.

Regarding item with ? symbol above: now that we are keeping all audit logs separately, does it makes sense to keep original audit tables? Since security of audit logs in question is of high importance (e.g. stored on separate account with only a single admin having access to it), leaving source audit tables mean that operations team or developers still have access to them.

I think it would make much more sense to give microservices direct write access to "big audit log DB", to only respective tables on the target, e.g. create several dedicated users with `GRANT INSERT` on respective audit tables:

 - pro: in this case audit logs will no longer be stored alongside other tables in the microservice's 
DB,
  - con: microservice application logic will not be able to rely on audit_tables anymore (due to lack of `GRANT SELECT`).

**Comment by gmile** [comment]
We decided to go with PostgreSQL.

Main arguments:

* PostgreSQL provides ACID guarantees,
* PostgreSQL will allow for granular permission control (e.g. we will grant only write access to 
microservices that desire to write audit logs),
* PostgreSQL is much less resource intensive,
* we have more expertise with PostgreSQL than with Elasticsearch, meaning:
  * we know how to do backups of any kind (daily full backups; incremental backups),
  * we know how to do master/slave fault-tolerance,
  * we know how to quickly perform backup-restore procedures.

Unanswered questions:
* in case PostgreSQL with audit log is not available, what do we do? Possible answer:
    1. use failover mechanism:
        * setup a Master/Slave replication of Audit DB; in case of Master failure or un-availability,  and 
automatically switch to a 
        * temporary write to local database,
        * once the original Master/Slave is up, copy the data from local audit_log DB to remote audit_log DB,
    2. stop the service entirely, until the incident is resolved (as we cannot operate without writing to audit_log).

**Comment by gmile** [comment]
@danakonovalenko the general approach & architecture was discussed, and we've been ready to do this for a while now but there's something missing.

Can you please specify the following:

* which of our databases have audit logs?
* are audit logs in question have all info we intent to store?

**Comment by gmile** [comment]
Let's simplify this task for now, and archive Elasticsearch logs instead. This will allows us to see who exactly did the request, which should allow us to do forensics.
