### ISSUE TITLE
Employee Request Data Model

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#1728]
Update employee according to new requirements:

- [ ] `employee_status` (candidate, employee, contract)
- [x] `archived_at` (data)
- [ ] `employee_details` ([{"phone":"+380501234567","email":"example@email.com"},{},..,{}])
- [x] `fte_rate`

Open question:
- [ ] (open question) to approve Employee Request must be signed with digital signature by HR
- [ ] (open question) employee-division connection

**Comment by Troush** [comment]
- [ ] `fte_rate` - model ?

**Comment by lymychp** [comment]
@danakonovalenko are the questions still open?

**Comment by lymychp** [comment]
@looks like it's not
