### ISSUE TITLE
Merge Party and MPI

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#1731]
As was discussed Party must be merged with mpi and only one source of person should be.

- [ ] find out which services will be influenced by such change
- [ ] design and change erd
- [ ] change specs for related WSes (if needed)

**Comment by lymychp** [comment]
it has been decided not to merge.
@danakonovalenko please provide link to the updated erd.

**Comment by danakonovalenko** [comment]
The description of updated ERD can be found here [spec](https://edenlab.atlassian.net/wiki/x/KQFcFg)
