### ISSUE TITLE
Cabinet

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#1736]
Patients Cabinet
	Processess:
		SignUp
		SignIn
		Add mail
		Update MPI
		Recovery/Renew password
		Find Doctor/Clinic/Division
		Create Declaration Request
		Terminate Declaration
		UC: Get Declaration Status/Details
	        Email SignUp - won't do
		Add/Delete list of users - one user<->one person
	Specs.:
	Dev.:

Make WS and pages for Cabinet for:
-  [x] Cabinet SignUp parent of #1788
-  [x] Cabinet SignIn via Email parent of #1789 
-  [x] Cabinet SignIn via DS parent of #1944
-  [x] authorization (Cabinet Auth via BankID #1733) - postponed
-  [x] update personal info (Update personal info via Cabinet parent of #1738)
-  [x] add patients info (Add personal info via Cabinet parent of #1743)
-  [x] make/view/terminate declaration (Declaration Request Cabinet parent of #1734)
-  [x] Find Doctor/Clinic/Division Search for a Doctor parent of #1892
-  [x] Change 2FA via Cabinet parent of #1926
