### ISSUE TITLE
Add working hours to divisions

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#1737]
All division has to be registered with working hours. 
Th information should be visible on portal map, and list of division

- [x] Change spec for division_request
- [x] Add new field to db`working_hours`
- [x] implement changes according to spec BE
- [x] Add info to division list on the portal FE
- [ ] Add info to the map
- [ ] test implementation

**Comment by Troush** [comment]
- [ ] Preferable data struct %{"mon" => [[8, 18]]}. Think about it

**Comment by Troush** [comment]
- [ ] Add to `report.db` and `api` for this fields
