### ISSUE TITLE
Add personal info via Cabinet 

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#1743]
After the person was registered and authorized must be a service which allows to get patients info (in order to be able to make declaration request later):

- [x] design WS which allows to get patients info
- [x] implement
- [x] test

- [x] Get person details parent of #1917
- [x] get personal info parent of #1918

**Comment by danakonovalenko** [comment]
- [ ] Get person details #1917
- [ ] get personal info #1918

**Comment by svetavedmed** [comment]
done
