### ISSUE TITLE
Cancelled declaration_request with person w/o tax_id

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#1751]
original request https://github.com/ehealth-ua/api-spec/issues/213

## Steps to Reproduce (Repro steps)

- [ ] POST https://api.ehealth.world/api/declaration_requests
- [ ] Створюємо декл.реквест для користувача без ІПН 63a3128c-cbbf-4398-a5ba-2598cf83f80e , не підтверджуємо його і потім зразу ж створюємо для іншого також без ІПН 6e2c79f5-b699-472e-969a-2ebee0700aa8. У них різні ПІБ, дати народження і стать. В результаті створення другої переша стає CANCELLED employee_id a1d9ddf1-8cab-4671-80e0-811f5a63df8d
[Запит і відповідь по 63a3128c-cbbf-4398-a5ba-2598cf83f80e.txt](https://github.com/ehealth-ua/api-spec/files/1635036/63a3128c-cbbf-4398-a5ba-2598cf83f80e.txt)
[Запит і відповідь по 6e2c79f5-b699-472e-969a-2ebee0700aa8.txt](https://github.com/ehealth-ua/api-spec/files/1635037/6e2c79f5-b699-472e-969a-2ebee0700aa8.txt)

## Actual result
- [ ] 63a3128c-cbbf-4398-a5ba-2598cf83f80e - перейшла в статус CANCELLED 

## Expected result
- [ ] 63a3128c-cbbf-4398-a5ba-2598cf83f80e - залишилась в статусі NEW 
------------------------
Can reproduce on DEV

Should add new validation for persons w/o tax_id
```
WHERE 
  IL_DB.declaration_requests.data.declaration_request.person.first_name = :($.declaration_request.person.first_name)
  AND IL_DB.declaration_requests.data.declaration_request.person.last_name = :($.declaration_request.person.last_name)
  AND IL_DB.declaration_requests.data.declaration_request.person.birth_date = :($.declaration_request.person.birth_date)
  AND IL_DB.declaration_requests.data.declaration_request.legal_entity_id = :($.declaration_request.legal_entity_id)
  AND IL_DB.declaration_requests.data.declaration_request.employee_id = :($.declaration_request.employee_id)
  AND IL_DB.declaration_requests.status IN ('NEW', 'APPROVED'))
```
[spec](https://edenlab.atlassian.net/wiki/spaces/EH/pages/983335/IL.Create+declaration+request)

**Comment by svetavedmed** [comment]
done on dev
