### ISSUE TITLE
Cabinet SignUp - selfregistration

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#1788]
## Sub-tasks:

- [x] BP Diagram (https://edenlab.atlassian.net/wiki/x/CoBcFQ)
- [x] BP Description
- [x] BP Review

## Key features:

- [ ] FE Screen flow (https://marvelapp.com/7i06dia/screen/38555501)
- [ ] FE DS applet
- [x] Send notification email (https://edenlab.atlassian.net/wiki/x/GIAeGQ)
- [x]  Validate link from email (https://edenlab.atlassian.net/wiki/x/JYEfGQ)
- [x]  Get Users by tax_id (https://edenlab.atlassian.net/wiki/x/zQEdGQ)
- [x] SignUp Form Data (https://edenlab.atlassian.net/wiki/x/uYIeGQ)
- [x] Phone/OTP verification
- [x] Check email is unique
- [x] Create User/Password
- [x] Create MPI

**Comment by danakonovalenko** [comment]
- [ ] fix cases where expected result doesn't match real one. Test case [here](https://edenlab.atlassian.net/wiki/x/BwAoHg)
