### ISSUE TITLE
Cabinet SignIn

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#1789]
## Sub-tasks:

- [x] BP Diagram (https://edenlab.atlassian.net/wiki/x/z4CzGQ)
- [x] BP Description
- [x] BP Review

## Key features:

- [ ] Login/Password form (https://marvelapp.com/7i06dia/screen/38278066)
- [x] DS as second factor - postponed
- [x] Investigate DS patterns - postponed
- [ ] Authenticate  (https://edenlab.atlassian.net/wiki/x/2IGyGQ)
- [ ] Generate token
- [x] Read-only scope - won't do
