### ISSUE TITLE
Declaration flow update

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#1792]
## Tasks:

- [x] BP Diagram Update
- [x] BP Description Update
- [x] BP Review

## Key features:
- [x] Modify online deduplication mechanism #1791 
- [ ] Invalidate tax_id for existing patients with the same tax_id [spec](https://edenlab.atlassian.net/wiki/spaces/EH/pages/1056471/Private.Create+or+update+Person)
~- [ ] Send email with registration link~
