### ISSUE TITLE
Enrich Party Profile

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#1799]
Additional Information (except speciality officio) from Employee Request must be stored to prm.parties and each time when receive employee request it must be updated. However speciality officio must be stored to prm.employees
Also add additional optional fields to Employee_request.party:
```
- about_myself (string, optional)
- working_experience (number, optional)
```
- [x] update specs
- [x] update json schemas
- [ ] change related WS
- [x] improve test scenarios
