### ISSUE TITLE
Current / ongoing OPS work

### ISSUE THREAD

**Issue by gmile** [edenlabllc/ehealth.api#1819]
A list of current and on-going OPS work.

1. **PostgreSQL incident postmortem work**:
	- [x] added script to export data for integrity verification,
	- [x] start an email chain with postgresql developers for get in-depth understanding of the issue,
	- [x] write an incident resolution protocol to be followed strictly in case of emergency,
	- [x] attempt at extracting stacktrace from PostgreSQL core dump,
	- [x] test backups restoration process, automatically. For every database in cluster do the following: https://github.com/edenlabllc/ehealth.api/issues/1822
		- every day pick a random point in time,
		- restore backup onto a fresh new DB,
		- make a rudimentary check that all restored tables match original tables: compare timestamps + total amount of records up to the point in time,
	- [x] add backups monitoring:
		- [x] setup `statsd_exporter` to proxy `pghoard` statsd-style metrics to prometheus https://github.com/edenlabllc/ehealth.api/issues/1820,
		- [x] evaluate metrics provided by `pghoard`; if they are not enough, add custom metrics and check:
			- new backup was created,
			- total amount of base backups is expected (e.g. 24 or whatever the number is for a particular environment),
			- size of backups is sane (e.g. a new backup is not orders of magnitude smaller than previous backup),
	- [x] add data consistency monitoring
		- every hour, maybe more often, send a metric to prometheus: compare the amount of signed `declaration_requests` + `declarations`,
	- [x] revisit pghoard backups, ensure they are working,
		- [x] determine why pghoard sometimes is not able to copy backups off-site,
		- [x] fix pghoard network flood issue.

3. **Revamp cluster CRON jobs**. Cron misconfiguration may potentially have a dramatic impact on cluster performance. To prevent the of cron misconfiguration in future, we must increase and promote cron visibility to the team. To do this, we will extract current CRON jobs from across the services in cluster, turning them into kubernetes `cronjob` objects configured and stored as yaml configs. Cron formulae, logs, success statuses, last run timestamps will become available for inspection from a consolidated place by running `kubectl get cronjobs`. This task involves:
	- [ ] gather a list of CRONs across all services in cluster,
	- [ ] expose an API endpoint to trigger desired action,
	- [ ] wipe CRON code from applications (simplify code & tests),
	- [ ] write & deploy kubernetes cron objects to cluster.

4. **Logging**

	Kong work:
	
	- [x] investigate why kong eats so much memory,
	- [x] re-implement kong logging:
		- [x] write new kong config (e.g. enginx config),
		- [x] deploy kong with up-to-date config,
		- [x] update fluentd parse config,
	- [ ] revisit POST/PUT/PATCH logging implementation on IL, verify that its working properly
	
	ElasticSearch + fluentd work:
	
	- [x] develop and test a quickfix: in case of any urgent issue with logging, remove old ES indicies
	- [x] research `fluentd` configuration options; tune configuration (increase buffer size and decrease logs flush rate), deploy updated configuration on all clusters
	- [x] log retention:
		- [ ] agree on the log retention perdiod,
		- [ ] setup cron job to delete logs older than retention perdiod.
	
4. **Monitoring**

	- [x] create basic monitoring alerts:
		- [x] via email
		- [x] via telegram
	- [ ] create custom Prometheus monitoring deshbo^ard https://github.com/edenlabllc/ehealth.api/issues/1841
		- [ ] determine what needs to be present on the dashboard,
		- [ ] set the dashboard up.
	- [x] setup Prometheus exporter for PostgreSQL server metrics from all DBs, https://github.com/edenlabllc/ehealth.api/issues/1821
	- [x] Split all monitoring workload into a separate node:
		- [x] evaluate node costs,
		- [x] setup new node,
		- [x] update monitoring tools configs to always deploy to the new node.
		
5. **Cluster tiding**

	- [x] set upper resource limits on all pods.

6.  **Deploy  and Testing postgresql streaming replication**

       -  [ ] Deploy streaming replication minikube\dev env
https://github.com/edenlabllc/ehealth.api/issues/1840

**Comment by lymychp** [comment]
@gmile I suppose, it can be closed now
