### ISSUE TITLE
Doctor Limits BE

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#1838]
as a NHS Admin 
i want doctors have a limit of possible declaration
so that they were not overloaded 

- [x] add flag on declaration `overlimit`: boolean, optional [Apiary](https://uaehealthapi.docs.apiary.io/#reference/public.-medical-service-provider-integration-layer/declaration-requests) 
- [x] add properties to party - properties: {"declaration_amount": n-1, "declaration_limit": 2000} [Apiary](https://uaehealthapi.docs.apiary.io/#reference/public.-medical-service-provider-integration-layer/employee-requests)
- [x] Add declaration_count and declaration_limit to reports.parties
- [x] implement logic [spec](https://edenlab.atlassian.net/wiki/x/JgEnFw)

**Comment by svetavedmed** [comment]
1. reports.parties.declaration_count starts from 0, should start from 1

**Comment by svetavedmed** [comment]
2. "overlimit" always saved to DB as null
should be true or false
