### ISSUE TITLE
Search for a Doctor

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#1892]
- [x]  Add to party 2 optional fields from employee_request:
```
about_myself
working_experience
```
- [x] update 
[Get Employees Details](https://uaehealthapi.docs.apiary.io/reference/public.-medical-service-provider-integration-layer/employees/get-employee-details)
[Deactivate Employee](https://uaehealthapi.docs.apiary.io/reference/public.-medical-service-provider-integration-layer/employees/deactivate-employee)
[Create Employee Request](https://uaehealthapi.docs.apiary.io/reference/public.-medical-service-provider-integration-layer/employee-requests/create-employee-request)
[Get Employee Request by ID](https://uaehealthapi.docs.apiary.io/reference/public.-medical-service-provider-integration-layer/employee-requests/get-employee-request-by-id)
- [x] Replicate those fields to report db
- [x] Make new WS [Search for a Doctor](https://edenlab.atlassian.net/wiki/x/zgNtGQ)

**Comment by danakonovalenko** [comment]
Delete from response fields declaration_limit, declaration_count and change to  "is_avaliable": true or false.

**Comment by danakonovalenko** [comment]
@AlexKovalevych please, instead of one EP make one additional WS and modify response for the current one
- [ ] Search Employees [apiary](https://uaehealthapi.docs.apiary.io/reference/internal.-portal-and-reports/employees/search-employees)
- [ ] Search Employee Details [apiary](https://uaehealthapi.docs.apiary.io/reference/internal.-portal-and-reports/employees/search-employee-details)

**Comment by danakonovalenko** [comment]
@AlexKovalevych please, actualize responds according to spec [Search Employees](https://uaehealthapi.docs.apiary.io/reference/internal.-portal-and-reports/employees/search-employees) and [Search Employee Details](https://uaehealthapi.docs.apiary.io/reference/internal.-portal-and-reports/employees/search-employee-details)
