### ISSUE TITLE
Declaration autotermination

### ISSUE THREAD

**Issue by warehousman** [edenlabllc/ehealth.api#190]
As a NHS
I want the declarations to be terminated according to the configured logic
- [x] children become adults
- [x] expiry date achieved
So that  I won't pay money for this.

Acceptance criteria:
- [x] calculate the expiry date of the declaration on the creation
when declaration has reached end_date, status should be changed to `closed`.
