### ISSUE TITLE
Files migration to on-premise DC (object storage)

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#1902]
Acceptance criteria: files from all the buckets in preprod/prod has been migrated to new DC.
- [x] LE signed content 
- [x] declarations signed content
- [x] reports 
- [x] declaration_requests scanned documents

**Comment by gmile** [comment]
@lymychp this is done:

```
$ mc ls denovo
[2018-03-08 13:26:35 EET]     0B capitation-reports-preprod/
[2018-03-16 10:26:55 EET]     0B declaration-requests-preprod/
[2018-03-15 16:46:43 EET]     0B declarations-preprod/
[2018-03-16 12:49:33 EET]     0B fonts/
[2018-03-14 20:41:25 EET]     0B legal-entities-preprod/
[2018-03-15 16:50:28 EET]     0B medication-request-requests-preprod/
[2018-03-15 14:08:14 EET]     0B testing/
$
```
(ignore the `0B`)

**Comment by lymychp** [comment]
should be migrated on prod as well)

**Comment by gmile** [comment]
@lymychp ah, true

**Comment by lymychp** [comment]
done on prod as well
