### ISSUE TITLE
eHealth Deployment to on-premise DC (preprod, prod)

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#1905]
acceptance criteria:
- [x] Create and Encrypt ISCSI block storage disk for minio. 
- [x] Create ISCSI block storage disk for pg_hoard backups.
- [x] Develop and Test step-by-step data migration process from prod to denovo env .

 - [x] all the services of eHealth app has been deployed to preprod cluster. All the tests from postman collection has been passed.
 - [x] all the services of eHealth app has been deployed to prod cluster. All the tests from postman collection has been passed.

**Comment by lymychp** [comment]
[postman test results](https://github.com/edenlabllc/ehealth.api/files/1875355/eHealth_PreProd_Capitation.txt)
