### ISSUE TITLE
Full-scale rollout performance preparation.

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#1907]
As a NHS 
I want to be sure that system is able to support below numbers during the sign-up capitation company:
```
- до 1 липня в системі буде 2міл декларацій, до 1січня2019 - 10 міл.
- пікові навантаження - 1міл укладених декларацій на місяць, 100к декларацій на день.
```
so that I can sleep well

Tasks
______
- [x] design testing methodology to check that system can support 100k declarations created during one day.
- [x] develop test scripts
- [ ] run tests and analyze results

**Comment by gmile** [comment]
Testing methodology focuses on determining RPS for the following main "happy path" API calls:

* create declaration request,
* sign declaration request,
* create legal entity,

All scripts are here: https://github.com/edenlabllc/performance_testing/tree/denovo

First results:

* create declaration request – we handle **20 requests per seconds**.

**Comment by gmile** [comment]
@AlexKovalevych @vsirius let's post subsequent testing results here.

**Comment by lymychp** [comment]
@AlexKovalevych please add the last performance test results

**Comment by gmile** [comment]
See full results in attachment: [requests_1521902534.535073.csv.zip](https://github.com/edenlabllc/ehealth.api/files/1941710/requests_1521902534.535073.csv.zip). At the moment of testing, with our current tools & methodology we we're able to achieve **33.65 requests per second** on average, peaking at **45 requests per second**.
