### ISSUE TITLE
Create declaration request online

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#1909]
Implement service according to [spec](https://uaehealthapi.docs.apiary.io/#reference/internal.-cabinet/cabinet/create-declaration-request-online) and [logic](https://edenlab.atlassian.net/wiki/spaces/EH/pages/436732204/Create+declaration+request+online)

Key features:
- [x] New group (scope) of routes `/api/cabinet`
- [x] New IL plug to validate cabinet scopes
- [x] Request data with person_id instead of full person dataset
- [x] Default (const) value for current_authorization_method

**Comment by danakonovalenko** [comment]
@AlexKovalevych please, fix bugs according to [test cases](https://edenlab.atlassian.net/wiki/x/OwB6Hw)
