### ISSUE TITLE
Update dependencies versions

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#1910]
- [x] nhs.auth.web
- [x] nhs.admin.web
- [x] nhs.portal.web
~- [ ] mithril.web~
~- [ ] uaddresses.web~

**Comment by ephor** [comment]
updated all dependencies except those that break projects
