### ISSUE TITLE
Get declarations list by patient

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#1919]
As a patient
I want see all my actual and previous declarations in cabinet
So that I see my declaration history

- [x] [Get declarations list by patient](https://edenlab.atlassian.net/wiki/x/IAAFGg)

**Comment by progsmile** [comment]
That's done

**Comment by progsmile** [comment]
Please test it before closing

**Comment by svetavedmed** [comment]
- [ ] wrong message for get declaration list w/o scopes
- [ ] add filters by division_name (like) and legal_entity_name (like)
- [ ] it should be forbidden to get declaration list with different tax_id in user and person

**Comment by progsmile** [comment]
Regarding this task:
`- add filters by division_name (like) and legal_entity_name (like)`

For implementing so, we would query ids from `prm.divisions`, `prm.legal_entities`, than will go to `ops.declarations`
Previously we discussed with @AlexKovalevych that it has some troubles because of too many ids can be fetched.. But still we can implement it. Alex what do you think?

**Comment by progsmile** [comment]
`wrong message for get declaration list w/o scopes`
Scopes have been already set [here](https://github.com/edenlabllc/ehealth.charts/blob/master/kong-dev.yml#L1106)

**Comment by danakonovalenko** [comment]
- [ ] as for now division for response is taken from employees, however it must be taken from declarations (as for employee division is optional field). In case whether employees.division_id is null we receive 500 error in response
