### ISSUE TITLE
Get Declaration Status/Details by patient

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#1920]
As a patient 
I want see details of all my declarations in cabinet
So that I could check my declaration any time

- [x] [Get Declaration Status/Details](https://edenlab.atlassian.net/wiki/x/tAGxGQ)

**Comment by ybod** [comment]
https://github.com/edenlabllc/ehealth.api/pull/1929

**Comment by svetavedmed** [comment]
- [ ] add to response 
- person.documents
```
"documents": [
        {
          "type": "PASSPORT",
          "number": "120518",
          "issued_by": "Рокитнянським РВ ГУ МВС Київської області",
          "issued_at": "2017-02-28"
        }
      ],```
- division.status
```"status": "ACTIVE",```

**Comment by svetavedmed** [comment]
- [ ] it should be forbidden to get declaration details for another person
```
check if users.person_id=$.declarations.person_id
in case error return 403
```

**Comment by svetavedmed** [comment]
500 if i try to get declaration for another person
```
{meta: {url: "http://api-svc.il/api/cabinet/declarations/927e63b2-8240-4a11-a9df-d4e09e7037d3",…},…}
error:{errors: {detail: "Internal server error"}}
errors:{detail: "Internal server error"}
meta:{url: "http://api-svc.il/api/cabinet/declarations/927e63b2-8240-4a11-a9df-d4e09e7037d3",…}
code:500
request_id:"cfd85ed3-9c8f-4685-bde8-b3dba929cf83#8383"
type:"object"
url:"http://api-svc.il/api/cabinet/declarations/927e63b2-8240-4a11-a9df-d4e09e7037d3"
```

**Comment by svetavedmed** [comment]
- [ ]  should be impossible to get declaration details with different tax_ids in user and person
