### ISSUE TITLE
Cabinet Sign in via DS

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#1944]
Design Sub-tasks:

- [x] BP Diagram (https://edenlab.atlassian.net/wiki/x/z4CzGQ)
- [x] BP Description
- [x] WS Description
- [ ] BP/WS Review

UI Design:
- [x] Login/Password form (https://marvelapp.com/7i06dia/screen/39713325)

Development sub-tasks:

- [ ] Generate nonce [apiary](https://uaehealthapi.docs.apiary.io/reference/internal.-cabinet/cabinet/get-nonce)
- [ ] Authenticate [confluence](https://edenlab.atlassian.net/wiki/x/bQB5Gw)
- [ ] Generate access token
