### ISSUE TITLE
Update Operational Documentation

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#1946]
To update the below documents if needed
- [x] system set up from scratch
- [x] new release deployment process
- [x] back-up/restore DB
- [x] back-up/restore file storage
- [x] etc..

**Comment by gmile** [comment]
@lymychp backup restore documentation will be done as part of #1947

**Comment by gmile** [comment]
We'll break this into two parts:

- [ ] system set up from scratch - @gmile @vsirius 
- [ ] new release deployment process - @gmile
- [ ] back-up/restore file storage - @gmile
- [ ] back-up/restore DB - @vsirius

**Comment by gmile** [comment]
New release deployment process is done as section 6 of "E-Health Specifications"

**Comment by gmile** [comment]
"System set up from scratch" was added as a section 5 of "E-Health Specifications"

**Comment by gmile** [comment]
"back-up/restore DB" is added as section 4 of "E-Health Specifications"

**Comment by gmile** [comment]
"back-up/restore file storage" exited in a preliminary form under section 7, "Disaster recovery plan". It will be filled with details during implementation.
