### ISSUE TITLE
BackUps configuration 

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#1947]
Set up, configure and test the backup procedures for
* DB
* file storages

Tasks:
- [x] implement and configure all the backup mechanisms
- [x] test backup monitoring mechanisms
- [x] test restore mechanisms

**Comment by gmile** [comment]
Let's compile a list of things to backup:

- [x] normal DBs,

  - [ ] update documentation about postgresql backups - @vsirius,

- [ ] implement elasticsearch backups - @gmile,

   - [ ] write docs,

- [ ] implement minio backups @gmile,

   - [ ] write docs,

- [ ] implmenet prometheus backups @gmile,

   - [ ] write docs,

**Comment by gmile** [comment]
I've added description of backup generation/restoration process of elasticsearch and PG to the "E-Health Specifications" doc.

minio / prometheus backups are currently planned, hence are out of scope of this issue. I've added a respective TODOs in the doc it self.
