### ISSUE TITLE
Cabinet Sign Up FE

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#1950]
As a part of oauth develop FE process of registration patients via Cabinet as described in [confluence](https://edenlab.atlassian.net/wiki/x/CoBcFQ)
pages for:
- [ ] Send notification email [confluence](https://edenlab.atlassian.net/wiki/x/GIAeGQ)
- [ ] Validate Link from Email [confluence](https://edenlab.atlassian.net/wiki/x/JYEfGQ)
- [ ] Registration form (MPI/User Create/Update) [confluence](https://edenlab.atlassian.net/wiki/x/uYIeGQ)

**Comment by danakonovalenko** [comment]
This issue was moved to edenlabllc/ehealth.web#3
