### ISSUE TITLE
add fields for declaration form

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#1962]
- [x] бажаний спосіб зв'язку -> mpi.persons.preferred_way_communication
- [x] орган видачі документу -> person.document.issued_by
- [x] дата видачі документу -> person.document.issued_at
- [x] Спеціалізація лікаря -> employee.specialities.speciality
- [x] person.confidant_person.primary.documents_person.issued_by
- [x] person.confidant_person.primary.documents_person.issued_at
- [x] person.confidant_person.primary.documents_relationship.issued_by
- [x] person.confidant_person.primary.documents_relationship.issued_at
- [x] person.confidant_person.secondary.documents_person.issued_by
- [x] person.confidant_person.secondary.documents_person.issued_at
- [x] person.confidant_person.secondary.documents_relationship.issued_by
- [x] person.confidant_person.secondary.documents_relationship.issued_at
- [x] номер декларації -> declaration_number
- [x] Унікальний номер запису в Єдиному державному демографічному реєстрі -> person.national_id
