### ISSUE TITLE
Case insensitive login (email) in auth

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#1978]
https://github.com/ehealth-ua/api-spec/issues/255

Our Auth system makes case sensitive match during registration and authorization. This causes the following issues:
- [x] user can be registered twice with the same email (`test@email.com`, `TEST@EMAIL.COM`)
- [x] user can't login to system with correct email in different spelling

Proposed solution:
- [x] Modify registration flow (create user flow) - convert user login (email) to lowercase and work with lowercase only
- [ ] Modify authorization flow - convert user login (email) to lowercase and work with lowercase only
- [ ] Auth FE - ?? only lowercase characters (or convert to lowercase)
- [ ] Modify reset password flow - put user login (email) to lowercase
- [ ] Auth FE - ?? only lowercase characters (or convert to lowercase)
- [ ] Merge duplicated user records
- [ ] Update all user records in Mithril - convert user login (email) with lowercase

**Comment by danakonovalenko** [comment]
- [ ] Case insensitive login (email) migration #2009

**Comment by danakonovalenko** [comment]
- [ ]  in response for legal_entity_id create request and employee create request  convert email to lowercase and work with lowercase only
