### ISSUE TITLE
national_id improvements

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#2043]
- [ ] copy the `national_id` values from the documents to 'national_id` field
- [ ] change create person logic: in case if there is a document with the `national_id` type, store it's number to the person.national_id filed
~- [ ] national_id should be unique~

---------
Future: change the search algorithm - use national_id.

**Comment by marinakr** [comment]
- [ ] set national on create/update from documents if national id is nil
- [ ] run migration as separate  application, add indexes
- [ ] add option search by national id

**Comment by svetavedmed** [comment]
changes for national_id will be done in #2916 and #2641
