### ISSUE TITLE
Prod deployment (Sprint 20)

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#2054]
# deployment preparation checklist
- [x] prepare [release notes](https://github.com/ehealth-ua/api-spec/pull/256) that should include list of all the tickets or PRs that are going to be delivered with this release. 
- [x] prepare all the release specific chekpoints: what should be checked in addition to the postman collection tests for this specific release
- [x] prepare all the DB scripts that should be executed and that were not included in the migrations (configurations, scopes, etc.)
- [x] create PR with the new version of API specs in the repo https://github.com/ehealth-ua/api-spec

# todo checklist that should be used for any eHealth deployment

- [x] define required versions of repo to the destination env. @AlekzandrV please check
```
report_api - latest
ehealth.api - latest
mpi.api - latest
event_manager_web - latest
ael_api - latest
digital_signature_api - latest
man_api - latest
mithril_api - stable !!!
ops - 1.133.1
uaddresses - latest
otp_verification_api - latest
nhs.auth.web - prod version!!!
nhs.portal.web - latest
nhs.admin.web -latest
uaddresses.web - latest
```
- [x] apply the required versions of repo to the destination env.
  - [x] ehealth.api
  - [x] prm.api
  - [x] mpi.api
  - [x] annon
  - [x] ael_api
  - [x] digital_signature_api
  - [x] man_api
  - [x] mithril_api
  - [x] ops
  - [x] uaddresses
  - [x] otp_verification_api
  - [x] nhs.auth.web
  - [x] nhs.portal.web 
  - [x] nhs.admin.web 
  - [x] man.web
  - [x] uaddresses.web 
~- [ ] IL.dictionaries - add/update if any. IDs should be the same.~
~- [ ] PRM.global_parameters - add/update if any. IDs should be the same~
~- [ ] uaddresses - add/update records if any. IDs should be the same~
~- [ ] GW.apis - migrate config~
~- [ ] GW.apis - Exclude temp dev routes~
~- [ ] GW.plugins~
- [x] Mithril config
~- [ ] client_types - add/update if any changes.~
~- [ ] roles - add/update if any changes.~
~- [ ] tokens - generate new tokens with new scopes in case if new endpoints are released~
  ~- [ ] approvals - generate or copy MIS approvals~
- [x] man templates - will be updated via migration
~- [ ] DS - migrate certificates if any~

# post-release check-list
- [x] cluster metrics
- [x] service metrics
- [x] API health-checks
- [x] merge PR with the new version of API specs in the repo https://github.com/ehealth-ua/api-spec
- [x] login/sanity check of NHS admin
- [x] login/sanity check of UAddresses admin
- [x] manual sanity check of new deployed features (should be taken from the Release Notes)
- [x] check backups
- [x] check logs in kibana
- [x] check graphana monitoring metrics
- [x] check reports and fraud DB replication status
  - [x] overall replication status
  - [x] every table status
- [x] check dictionaries
  * document_type
  * streets
  * register_type
  * declaration limit
- [x] check scopes
- [x] check division stats

**Comment by lymychp** [comment]
deployed to prod
