### ISSUE TITLE
External API requests monitoring dashboard

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#2067]
set up new dashboard with the API monitoring charts
- [ ] **x axis**: time-series (1-10 minutes), **y axis**: count requests blended by API endpoint
- [ ] **x axis**: time-series (1-10 minutes), **y axis**: average requests duration blended by API endpoint
- [ ] **x axis**: time-series (1-10 minutes), **y axis**: average requests duration blended by http response code
- [ ] **x axis**: count or % of HTTP response codes, **y axis**: API endpoint. 
- [ ] **x axis**: time-series (1-10 minutes), **y axis**: count of HTTP response codes. Filter all the 5xx requests

**Comment by gmile** [comment]
@lymychp can we close this now?
