### ISSUE TITLE
Fraud DB for reimbursement

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#2120]
Add new data to Fraud DB for reimbursement reports

- [ ] Fraud db and mapping description [specs](https://edenlab.atlassian.net/wiki/spaces/EH/pages/42008577/1.+Fraud+Detection+DB#id-1.FraudDetectionDB-Tablesforreimbursement)
- [ ] Data Mart Developing
- [ ] Data Mart test

**Comment by svetavedmed** [comment]
- [ ] medication_requests - without verification_code
