### ISSUE TITLE
NHS portal

### ISSUE THREAD

**Issue by warehousman** [edenlabllc/ehealth.api#213]
- [ ] About NHS
- [x] Infographics re Reform
- [x] MSP map
- [x] List of MIS
- [x] prepare specs for all the missed services
- [x] add integration with real services
- [ ] prepare browser requirements
- [ ] test?

**Comment by lymychp** [comment]
7 sp - testing

**Comment by alexeybondarenko** [comment]
@warehousman, @lymychp i've decomposed this task:
#387
#386
#385
#384
#383
#382
#381
#380
