### ISSUE TITLE
check uniqueness of declaration_number

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#2131]
As declaration_number is randomly generated symbols and that is a probability of generation similar numbers, additional check for uniqueness of declaration number should be added.

- [x] change specification [declaration_request_create](https://edenlab.atlassian.net/wiki/spaces/EH/pages/983335/IL.Create+declaration+request#IL.Createdeclarationrequest-Generatehumanreadabledeclarationnumber), [declaration_request_sign](https://edenlab.atlassian.net/wiki/spaces/EH/pages/1108579/IL.Sign+declaration+request#IL.Signdeclarationrequest-Validatehumanreadabledeclarationnumber)
- [x] add search on declaration_request_create
- [x] add check on declaration_request_sign
- [ ] test implementation

**Comment by svetavedmed** [comment]
closed only with local tests
