### ISSUE TITLE
Compensation Group

### ISSUE THREAD

**Issue by warehousman** [edenlabllc/ehealth.api#219]
As NHS admin
I want 
 - [ ] Based on declaration parameters via Gandalf Compensation group should be calculated and stored in the billing table after billing process.
- [ ] legal_entity.edrpou for every declaration record from the billing report should be compared with the edrpou from the declaration signed content.validation result (true/false) should be stored in the billing table.
So that 
- [ ] I can easily manage compensation group calculation logic without deployment
- [ ] I can be sure that data for the capitation report are consistent and hasn't been changed

**Comment by lymychp** [comment]
gndf api call to calculate compensation group:
```
$ curl -u CLIENT_ID:CLIENT_SECRET -H 'X-Application: 58eca20fe79e8563e803dc18' https://api.gndf.io/api/v1/tables/59775b4ee79e854e482b045b/decisions \
  -d '{"mountain_group":false,"age":23}'
```
