### ISSUE TITLE
Update contract request by nhs

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#2190]
As NHS Admin signer I want to change contract request before changing status so that it would be with all necessary information

- [ ] [confluence](https://edenlab.atlassian.net/wiki/x/cIA3Hw), [apiary](https://uaehealthapi.docs.apiary.io/#reference/contracts/contract-request/update-contract-request-by-nhs-signer)
- [ ] implement
- [ ] test

**Comment by danakonovalenko** [comment]
- [ ] add validation for nhs_payment_method: DICTIONARY - CONTRACT_PAYMENT_METHOD

**Comment by danakonovalenko** [comment]
- [ ] to avoid additional fields the json scheme on Update Contract request must be added
[update_contract_request_request.txt](https://github.com/edenlabllc/ehealth.api/files/2077455/update_contract_request_request.txt)
