### ISSUE TITLE
Approve contract request by NHS

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#2196]
As NHS I want change status of contract to Approve So that it could be singed in future

- [x] [specification](https://edenlab.atlassian.net/wiki/spaces/EH/pages/524353572/Approve+contract+request+by+NHS), [apiary](https://uaehealthapi.docs.apiary.io/#reference/contracts/contract-request/approve-contract-request-by-nhs)

- [x] implementation
- [x] test

**Comment by danakonovalenko** [comment]
-  [ ] remove from data
 - updated_by
 - updated_at
- inserted_at
- inserted_by  
- [ ] data and response of Get contract Request by ID must be in the same order as now they never match each other.

**Comment by danakonovalenko** [comment]
it's possible to approve contract_request with contract_number that belongs to only TERMINATED contract (there is no VERIFIED contract with such number, same validation as on Create Contract Request)

Request
```curl -X PATCH \
  https://api.dev.asclepius.com.ua/api/contract_requests/64a9e663-31f8-4e52-b39c-96e7f4b23ebc/actions/approve \
  -H 'api-key: UXhEczJacXh3Ri9SUkc4enhHTVVpQT09' \
  -H 'authorization: Bearer OWN5bi9FdEs0R1NhSDhRK0Z0T1lBQT09' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: cfeec348-352f-61c3-1a6e-946092acf539'
```
Response
```200```

Expected response
``` "error": {
        "type": "request_malformed",
        "message": "There is no active contract with such contract_number",
        "invalid": [
            {
                "rules": [
                    {
                        "rule": "json"
                    }
                ],
                "entry_type": "request"
            }
        ]
    }
```
