### ISSUE TITLE
Sign Contract Request by NHS 

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#2211]
Representer of NHS must be able to sign Contract Request. In order to do that we need WS implement according [logic](https://edenlab.atlassian.net/wiki/x/rIBAHw) and [spec](https://uaehealthapi.docs.apiary.io/reference/contracts/contract-request/sign-contract-request-by-nhs)
- [ ] implement
- [ ] improve test scenarios

**Comment by danakonovalenko** [comment]
@AlexKovalevych please  fix [test cases](https://edenlab.atlassian.net/wiki/x/FIESIg) with incorrect actual result:
- [ ] SCR_NHS2  - case when token belong to some client_id which is not nhs_legal_entity_id. Error message - 'Invalid client id'
- [ ] SCR_NHS6 - compare to contract_requests.id.data
- [ ] SCR_NHS10 - same check as for Create Contract request: check if there is verified (update) or none  (create) contract with such contract_number. if there is/are only terminated contracts with such contract_number return an error `There is no active contract with such contract_number`
- [ ] SCR_NHS11 - same check as for Create Contract request: check that if contractor_employee_divisions are in request, than there is no contract with such contract_number

**Comment by danakonovalenko** [comment]
- [ ] SCR_NHS10 - same check as for Create Contract request: check if there is verified (update) or none (create) contract with such contract_number. if there is/are only terminated contracts with such contract_number return an error There is no active contract with such contract_number
same logic as on Create Contract Request must be implemented

**Comment by danakonovalenko** [comment]
it's possible to approve contract_request with contract_number that belongs to only TERMINATED contracts (there is no VERIFIED contract with such number, same validation as on Create Contract Request)

Response
200

Expected response
```
        "type": "request_malformed",
        "message": "There is no active contract with such contract_number",
        "invalid": [
            {
                "rules": [
                    {
                        "rule": "json"
                    }
                ],
                "entry_type": "request"
            }
        ]
    }
```
