### ISSUE TITLE
Test Cabinet api

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#2213]
Test BE
- [x] parent of #1862 Sign Up Step 1 [test cases](https://edenlab.atlassian.net/wiki/x/BwAoHg), [test cases](https://edenlab.atlassian.net/wiki/x/ngAqHg)
- [x] parent of #1798 Sign In with Email [test cases](https://edenlab.atlassian.net/wiki/x/R4DLHg)
- [x] parent of #1944 Sign In with DS - [test cases](https://edenlab.atlassian.net/wiki/x/AQDYHg)
- [x] parent of #1898 Update MPI [test cases](https://edenlab.atlassian.net/wiki/x/iQDoHg)
- [x] parent of #1918 Get personal info [test cases](https://edenlab.atlassian.net/wiki/x/qwCzHg)
- [x] parent of #1917 Get personal details [test_cases](https://edenlab.atlassian.net/wiki/spaces/EH/pages/516325377/Get+person+details+tests)
- [x] parent of #1892 Search Clinic/Doctor [test cases](https://edenlab.atlassian.net/wiki/x/lwB2Hw)
- [x] parent of #1909 Create declaration requests [test cases](https://edenlab.atlassian.net/wiki/x/OwB6Hw)
- [x] parent of #1925 Terminate declaration [test cases](https://edenlab.atlassian.net/wiki/x/dYB6Hw)
- [x] parent of #1920 Get declaration details [test cases](https://edenlab.atlassian.net/wiki/x/CQB4Hw)
- [x] parent of #1919 Get declarations list [test cases](https://edenlab.atlassian.net/wiki/x/GoB6Hw)
- [x] parent of #2347 Approve declaration request online [test cases](https://edenlab.atlassian.net/wiki/x/fwBSIg)
- [x] parent of #2358 Get Declaration Requests list via Cabinet
- [x] parent of #2359 Get Declaration Requests Details via Cabinet

Test FE
- [x] parent of [#3](https://github.com/edenlabllc/ehealth.web/issues/3) Sign Up Step 1 [test cases](https://edenlab.atlassian.net/wiki/x/BwAoHg), [test cases](https://edenlab.atlassian.net/wiki/x/ngAqHg)
- [x] parent of [#4](https://github.com/edenlabllc/ehealth.web/issues/4) Sign In with Email - [test cases](https://edenlab.atlassian.net/wiki/x/R4DLHg)
- [x] parent of [#5](https://github.com/edenlabllc/ehealth.web/issues/5) Sign In with DS [test cases](https://edenlab.atlassian.net/wiki/x/AQDYHg)
- [x] parent of [#6](https://github.com/edenlabllc/ehealth.web/issues/6) Cabinet Sign In FE 
- [x] parent of [#7](https://github.com/edenlabllc/ehealth.web/issues/7) Search Clinic/Doctor [test cases](https://edenlab.atlassian.net/wiki/x/lwB2Hw)
- [x] parent of [#8](https://github.com/edenlabllc/ehealth.web/issues/8) Update MPI [test cases](https://edenlab.atlassian.net/wiki/x/iQDoHg)
- [x] parent of [#8](https://github.com/edenlabllc/ehealth.web/issues/8) Get personal details [test_cases](https://edenlab.atlassian.net/wiki/spaces/EH/pages/516325377/Get+person+details+tests)
- [x] parent of [#10](https://github.com/edenlabllc/ehealth.web/issues/10) Cabinet Home Page
- [x] parent of [#11](https://github.com/edenlabllc/ehealth.web/issues/11) Create declaration requests [test cases](https://edenlab.atlassian.net/wiki/x/OwB6Hw)
- [x] parent of [#13](https://github.com/edenlabllc/ehealth.web/issues/13) Terminate declaration [test cases](https://edenlab.atlassian.net/wiki/x/dYB6Hw)
- [x] parent of [#12](https://github.com/edenlabllc/ehealth.web/issues/12) Get declarations list [test cases](https://edenlab.atlassian.net/wiki/x/GoB6Hw)
- [x] parent of [#9](https://github.com/edenlabllc/ehealth.web/issues/9) View/Update 2FA via Cabinet
- [x] Reset psw through Cabinet parent of #2362
- [x] Change 2FA via Cabinet parent of #1926

**Comment by danakonovalenko** [comment]
- [ ] Reset psw through Cabinet #2362
- [ ] Change 2FA via Cabinet #1926

**Comment by svetavedmed** [comment]
- [ ] Changes on Sign-up
