### ISSUE TITLE
Dashboard for MSP

### ISSUE THREAD

**Issue by warehousman** [edenlabllc/ehealth.api#224]
As MSP employe i want to know basic stats from E-Health
- [x] Approve dashboards #397 #417 #418 #419 #420
- [x] Stats by regions #432
- [x] Stats by division #437
- [x] Main stats #434
- [x] Declarations Histogram stats #435
- [x] Division map #438

**Comment by mmiliaieva** [comment]
Front:
https://www.dropbox.com/s/4kumij098d6hd89/NSZ_landing.jpg?dl=0
https://www.dropbox.com/s/7is0q17zb1ifn9n/NSZ_landing_2.jpg?dl=0
https://www.dropbox.com/s/7is0q17zb1ifn9n/NSZ_landing_2.jpg?dl=0
