### ISSUE TITLE
Get Contract List 

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#2243]
- [x] specification ([apiary](https://uaehealthapi.docs.apiary.io/reference/contracts/contracts/get-contracts-list), [confluence](https://edenlab.atlassian.net/wiki/x/YoCIHw))
 - [x] implementation
 - [x]  test

**Comment by danakonovalenko** [comment]
please add route {{host}}/api/contracts? to kong with scope contract:read

**Comment by danakonovalenko** [comment]
- [ ] filter by nhs_signer_id doesn't work. return all contracts in response

**Comment by lymychp** [comment]
@danakonovalenko please test and close

**Comment by danakonovalenko** [comment]
- [ ]  GET ` https://api.dev.asclepius.com.ua/api/contracts \` return 63 entries, however there are 32 contracts in DB
