### ISSUE TITLE
Audit Trail

### ISSUE THREAD

**Issue by warehousman** [edenlabllc/ehealth.api#228]
@Peter please add description here
- [ ] unauthorized data changes
- [x] unauthorized access to cluster

- [x] Logs should be stored outside the cluster. Cluster admin shouldn't be able to change it.
- [ ] define what should be included in the external logs
- [ ] configure logs transfer

**Comment by AndrewDryga** [comment]
> Logs should be stored outside the cluster. Cluster admin shouldn't be able to change it.

At the moment, logs are stored in Google Cloud Logger. Access to them is restricted by IAM policies. Cloud Logger won't let you delete them, however, retention time depends on a subscription plan, up to 30 days.

Migration to private cloud we will need to re-evaluate options (ELK stack or third-party services, eg. loggly).

> unauthorized access to cluster

Managed by IAM and RBAC policies.

**Comment by kmakarenko** [comment]
Could you please link the tasks on GitHub related to this task so that they could be included artefacts to the report.

**Comment by lymychp** [comment]
https://github.com/Nebo15/ehealth.k8s
