### ISSUE TITLE
Contract Request Details FE

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#2373]
NHS SIGNER admin must be able to see the details of contract request using admin portal 

- [ ] UI design according to confluence is [here](https://www.dropbox.com/sh/wpxhr013qbteird/AABaHBvZ-IQ9SiJcvIDzC4bua?dl=0&preview=NSZ_Contract_requests_details.png) 
 - [ ] implementation [confluence](https://edenlab.atlassian.net/wiki/x/ZIA3Hw)  and [apiary](https://uaehealthapi.docs.apiary.io/reference/public.-contracts/contract-request/get-contract-request-details)
- [ ] definition list
- [ ] form
- [ ] signer
- [ ] test

**Comment by svetavedmed** [comment]
- [ ] preview of the contract does nor show updated fields

**Comment by ephor** [comment]
@svetavedmed Ready for test
