### ISSUE TITLE
Approve/Decline contract request by NHS FE

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#2374]
After viewing details NHS signer admin must be able to approve / decline Contract Request. 
Screen flow is next
get details - > approve/decline with status reason -> sign (sign json) - > return to detail page
link to design here (TBD)
 - [x]  implement according to logic [approve](https://edenlab.atlassian.net/wiki/x/JABBHw)/[decline](https://edenlab.atlassian.net/wiki/x/LYBCHw)
- [ ]  test

**Comment by svetavedmed** [comment]
- [ ] decline of Decline does not work
```
app.js?f8b67a54a4e353af4899:1 Uncaught TypeError: Cannot read property 'setState' of undefined
    at value (app.js?f8b67a54a4e353af4899:1)
    at Object.r (app.js?f8b67a54a4e353af4899:1)
    at o (app.js?f8b67a54a4e353af4899:1)
    at Object.s [as executeDispatchesInOrder] (app.js?f8b67a54a4e353af4899:1)
    at p (app.js?f8b67a54a4e353af4899:1)
    at m (app.js?f8b67a54a4e353af4899:1)
    at Array.forEach (<anonymous>)
    at r (app.js?f8b67a54a4e353af4899:1)
    at Object.processEventQueue (app.js?f8b67a54a4e353af4899:1)
    at r (app.js?f8b67a54a4e353af4899:1)
value @ app.js?f8b67a54a4e353af4899:1
r @ app.js?f8b67a54a4e353af4899:1
o @ app.js?f8b67a54a4e353af4899:1
s @ app.js?f8b67a54a4e353af4899:1
p @ app.js?f8b67a54a4e353af4899:1
m @ app.js?f8b67a54a4e353af4899:1
r @ app.js?f8b67a54a4e353af4899:1
processEventQueue @ app.js?f8b67a54a4e353af4899:1
r @ app.js?f8b67a54a4e353af4899:1
handleTopLevel @ app.js?f8b67a54a4e353af4899:1
i @ app.js?f8b67a54a4e353af4899:1
perform @ app.js?f8b67a54a4e353af4899:1
batchedUpdates @ app.js?f8b67a54a4e353af4899:1
i @ app.js?f8b67a54a4e353af4899:1
dispatchEvent @ app.js?f8b67a54a4e353af4899:1
```

**Comment by ephor** [comment]
@svetavedmed Ready for test

**Comment by svetavedmed** [comment]
- [ ] reload page after decline and approve
- [ ] check nhs fields before "approve", in case one or more empty msg "Не всі поля заповнені. Заповніть будь-ласка поля"
- [ ] fill update fields in case they are not empty
