### ISSUE TITLE
Contract Requests for NHS admin portal (FE)

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#2376]
Contract request
- [x] Contract Request list FE parent of #2372
- [x] Contract Request Details FE parent of #2373
- [x] Approve/Decline contract request by NHS FE parent of #2374
- [x] SIGN Contract Request by NHS FE parent of #2375
- [x] error handling parent of edenlabllc/ehealth.web#82
- [x] add documents to contracts admin parent of edenlabllc/ehealth.web#101

Contracts
- [x] Get contract by ID parent of edenlabllc/ehealth.web#83
- [x] Get contract list parent of edenlabllc/ehealth.web#84
- [x] Terminate contract by NHS Admin parent of edenlabllc/ehealth.web#122

[design](https://www.dropbox.com/sh/wpxhr013qbteird/AABaHBvZ-IQ9SiJcvIDzC4bua?dl=0&preview=NSZ_Contract_requests_details.png)

tasks
- [x] Contract print form missing fields parent of edenlabllc/ehealth.web#130
- [x] Approve/Decline contract request by NHS parent of edenlabllc/ehealth.web#129
- [x] Use dictionary for medical_service in Admin portal parent of edenlabllc/ehealth.web#125

**Comment by svetavedmed** [comment]
- [ ] parent of edenlabllc/ehealth.web#148
