### ISSUE TITLE
Update Employees in Contract 

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#2389]
HR must be able to manage employees which belong to contract through one side signed content. According to this the WS must be implemented
- [x] [apiary](https://uaehealthapi.docs.apiary.io/reference/public.-contracts/contracts/public.-update-contract-employees) / [confluence](https://edenlab.atlassian.net/wiki/x/GAC1Hw) 
- [x] implementation
- [ ] test

**Comment by IrinaRevutska** [comment]
@AlexKovalevych , 
I am trying to update employee using legal entity owner access token but I am getting 404:
```
{
    "meta": {
        "url": "http://api-svc.il/api/employees/29a46a6f-02f7-43a6-8f98-3a9af8cf5add",
        "type": "object",
        "request_id": "1fc6a41d-17bf-44d5-8b6d-b520c575c5ee#23532",
        "code": 404
    },
    "error": {
        "type": "not_found"
    }
}
```
cURL
```
curl -X PUT \
  https://api.dev.asclepius.com.ua/api/employees/29a46a6f-02f7-43a6-8f98-3a9af8cf5add \
  -H 'Authorization: Bearer c21PaytxYitwSjI1MDRPNldva0xvUT09' \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: 7079b6bb-2bc0-46a1-9228-b79de2082dc3' \
  -H 'api-key: UXhEczJacXh3Ri9SUkc4enhHTVVpQT09' \
  -d '{
  "no_tax_id": false,
  "legal_entity_id": "fac8fe24-bf38-4f05-875b-59cdb5a258aa",
  
  "employee_type": "DOCTOR",
  "position": "P1",
  "start_date": "2018",
  "end_date": "2018",
  "status": "NEW"
}'
```

**Comment by svetavedmed** [comment]
- [ ] fill update fields in case they are not empty

**Comment by IrinaRevutska** [comment]
Did you add route to kong?
Got 404:
```
{
    "message": "no API found with those values"
}
```
```
curl -X PATCH \
  https://api.dev.asclepius.com.ua/api/contracts/ac07fb8c-6ad6-4366-8232-af7ee712a11a/employees/actions/update \
  -H 'Authorization: Bearer aDlKY2lhQXFTakVrdXA4WEowUEZ0Zz09' \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: 89eca7ca-fbd7-4893-8ab5-60be0145ffbd' \
  -H 'api-key: UXhEczJacXh3Ri9SUkc4enhHTVVpQT09' \
  -d '{
  "signed_content": "eyJlbXBsb3llZSI6DQogICAgew0KICAgICAgICAiaWQiOiAiYTM4MDk5YTgtYjM1Mi00Y2ZkLTliNGEtODliNjBmM2U0YjBhIiwNCiAgICAgICAgInN0YWZmX3VuaXRzIjogMSwNCiAgICAgICAgImRlY2xhcmF0aW9uX2xpbWl0IjogMTIwMCwNCiAgICAgICAgImRpdmlzaW9uX2lkIjogIjU5NDY4ZmI2LWJkYTQtNDFkNS1hZmU2LWI1MmZlODJkYWIwMCINCiAgICB9DQp9",
  "signed_content_encoding": "base64"
}
```

**Comment by danakonovalenko** [comment]
on dev and demo I receive same kind of error
```
{
    "meta": {
        "url": "http://api.dev.asclepius.com.ua:8000/api/contracts/2ef9f91f-ac79-474c-862c-c73b8c74b0a6/actions/update",
        "code": 403,
        "request_id": "cfd85ed3-9c8f-4685-bde8-b3dba929cf83#32635",
        "type": "object"
    },
    "error": {
        "message": "ACL: No matching rule was found for path /api/contracts",
        "type": "forbidden"
    }
}
```

**Comment by AlexKovalevych** [comment]
The endpoint is `/api/contracts/:id/employees/actions/update`

**Comment by danakonovalenko** [comment]
```
Check division belongs to legal_entity and division.status='active'. 
in case of error return 422  error view $divisions ('Division must be active and within current legal_entity')
```
As for now it's possible to update with division in status='closed'

**Comment by danakonovalenko** [comment]
As for now if I'm trying to deactivate employee, still one more row for this employee will be created with end_date. In order to deactivate employee current active employee in contract must be found and deactivated (by  $contract_id + $employee_id +$division_id and end_date=null. For such row set end_date=now()::date+time)

in this case request must be:
```
{ 
"employee_id": "09106b70-18b0-4726-b0ed-6bda1369fd52", 
"division_id": "6eb6123a-b3ce-4d27-ad3a-f6e3fb3ef1a1",
"is_active":false
}
```

**Comment by danakonovalenko** [comment]
according to spec
for deactivation and update
- [ ] Check employee belongs to legal entity
- [ ] Check divisions belongs to legal_entity

for update/add new
- [ ] Employee from employee_divisions has employee_type='DOCTOR', status='APPROVED'
- [ ] Check divisions belongs to contractor_divisions
- [ ] Check divisions.status='active'

for deactivate
- [ ] Check there is an ACTIVE employee ( $contract_id + $employee_id +$division_id and end_date=null)

**Comment by marinakr** [comment]
@danakonovalenko  should we return error 409 conflict if check divisions.status='active' and check employee belongs to legal_entity?
