### ISSUE TITLE
Upload documents (Contract Request)

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#2420]
1. Create Contract Request:
- [ ] ~change status from `NEW` to `DRAFT`~
- [x] For each field $.statute and $equipment_agreement
```
Generate URL's with type contract_request.{$.contract_request_id.$statute}
Generate URL's with type contract_request.{$.contract_request_id.$equipment_agreement}
```
- [x] in response add links to download those documents:
```
  "statute":"url1"
  "equipment_agreement":"url2"
```
- [x] test

~2. Approve Uploaded Documents by MSP~
-  [ ] ~[spec](https://edenlab.atlassian.net/wiki/x/wACxIg) /  [apiary](https://uaehealthapi.docs.apiary.io/reference/public.-contracts/contract-request/approve-uploaded-documents-for-contract-request-by-msp)~
- [ ] ~implement~
- [ ] ~test~

Replaced by #2502
~3. Get Documents by Contract Request ID~
- [ ] ~[spec](https://edenlab.atlassian.net/wiki/x/34CwIg) / [apiary](https://uaehealthapi.docs.apiary.io/reference/public.-contracts/contract-request/get-contract-request-documents)~
- [ ] ~implement~
- [ ] ~test~
