### ISSUE TITLE
Rename document to upload in contract request

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#2480]
Rename `equipment_agreement` document to `additional_document`

Initialize contract request
- [x] Rename document URL in response from `equipment_agreement_url` to `additional_document_url`

Create contract request
- [x] Rename attribute `equipment_agreement_md5` to `additional_document_md5`

Get contract request details
- [x] Rename document URL in response from `equipment_agreement` to `additional_document`

JSON Schema
- [x] Update schema
