### ISSUE TITLE
Medication request qualify 

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#2484]
- [x]  I'm trying to prequalify signed medication request with nhs_token and as a result receive *`500 Error`*
```
curl -X POST \
  https://api.dev.asclepius.com.ua/api/medication_requests/35e83906-74e0-4332-9adc-ed982e244a93/actions/qualify \
  -H 'authorization: Bearer cHhZSjh0d0hJZG11cUpUZ0FsL3k0UT09' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: a82e0b9f-0b83-123e-0440-8c9f3f6d9d7a' \
  -d '{
  "programs": [
    {
      "id": "580a631c-f2cb-4d0b-8247-69bda40e8c0a"
    }
  ]
}'
```
- [x] *`500 error`* on Get medication requests list and Get medication requests by ID
 ```
curl -X GET \
  https://api.dev.asclepius.com.ua/api/medication_requests \
  -H 'api-key: UXhEczJacXh3Ri9SUkc4enhHTVVpQT09' \
  -H 'authorization: Bearer cHhZSjh0d0hJZG11cUpUZ0FsL3k0UT09' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: 54076492-6e4a-6e4c-6c98-06c9ed6c37a2'
```
- [ ] pharmacist doesn't have a scope to prequalify medication request
```
{
    "meta": {
        "url": "http://api.dev.asclepius.com.ua:8000/api/medication_requests/
35e83906-74e0-4332-9adc-ed982e244a93/actions/qualify",
        "code": 403,
        "request_id": "1fc6a41d-17bf-44d5-8b6d-b520c575c5ee#16771",
        "type": "object"
    },
    "error": {
        "message": "Your scope does not allow to access this resource. 
Missing allowances: medication_request:details",
        "type": "forbidden"
    }
}
```
- [ ] doctor can't get medication request list 
```
{
    "meta": {
        "url": "http://api.dev.asclepius.com.ua:8000/api/medication_requests",
        "code": 403,
        "request_id": "1fc6a41d-17bf-44d5-8b6d-b520c575c5ee#16777",
        "type": "object"
    },
    "error": {
        "message": "Your scope does not allow to access this resource. Missing allowances: medication_request:read",
        "type": "forbidden"
    }
}
```

**Comment by danakonovalenko** [comment]
on demo
- [ ] Get Medication Request by ID dev/demo
```
curl -X GET \
  https://api.demo.asclepius.com.ua/api/medication_requests/b5585bfb-c784-42be-8daf-ceb181c37af9 \
  -H 'api-key: d036273f779b1741dcf0' \
  -H 'authorization: Bearer V0Qzd3NVL0IxOHYyWXNMSVdwdk1yZz09' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: 0bfebf91-b51a-f142-8266-2db413d8494d'
```
object employee.division is empty
<img width="412" alt="screen shot 2018-06-27 at 3 43 21 pm" src="https://user-images.githubusercontent.com/31403196/42003563-e0f4062c-7a20-11e8-8ad2-0e538e07aff5.png">

**Comment by lymychp** [comment]
@AlexKovalevych please assign task

**Comment by danakonovalenko** [comment]
@AlekzandrV 
I retested with correct token,
- [ ] still as a doctor I can't have medication_requests list, however medication request by ID works correctly:
***Get medication requests list***
*Request*
```
curl -X GET \
  https://api.dev.asclepius.com.ua/api/medication_requests \
  -H 'api-key: UXhEczJacXh3Ri9SUkc4enhHTVVpQT09' \
  -H 'authorization: Bearer UU55TmUrWHdIOUloVUVRQUdLMEl0QT09' \
  -H 'cache-control: no-cache' \
  -H 'postman-token: 6299aa31-d37a-f838-617d-70c7d17bf0db'
```
*Response*
```
{
    "meta": {
        "url": "http://api.dev.asclepius.com.ua:8000/api/medication_requests",
        "code": 403,
        "request_id": "cfd85ed3-9c8f-4685-bde8-b3dba929cf83#35884",
        "type": "object"
    },
    "error": {
        "message": "Your scope does not allow to access this resource. Missing allowances: medication_request:read",
        "type": "forbidden"
    }
}
```
***Get medication requests by id***
*Request*
```curl -X GET \
  https://api.dev.asclepius.com.ua/api/medication_requests/c137b931-34c4-4d20-a73d-40dca1145a09 \
  -H 'api-key: UXhEczJacXh3Ri9SUkc4enhHTVVpQT09' \
  -H 'authorization: Bearer UU55TmUrWHdIOUloVUVRQUdLMEl0QT09' \
  -H 'cache-control: no-cache' \
  -H 'postman-token: 11fc829f-e8a2-b626-1ef9-f1bca6ead3d2'
```
*Response*
200+ response
- [ ] I'm trying to dispense medication request, which is active
```
curl -X POST \
  'https://api.dev.asclepius.com.ua/api/medication_dispenses?code=2189' \
  -H 'api-key: UXhEczJacXh3Ri9SUkc4enhHTVVpQT09' \
  -H 'authorization: Bearer NnoyNVJ2K0lRczlzdFcyRExyZFF3QT09' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: e7b0577b-aa16-3cbd-5298-60c1cd1ddb3b' \
  -d '{
"medication_dispense":{
    "medication_request_id": "c137b931-34c4-4d20-a73d-40dca1145a09",
    "dispensed_at": "2018-07-10",
    "division_id": "1965b218-21fd-428f-a5e1-5b90042ee268",
    "medical_program_id": "caee115b-90a4-4550-b62f-939536b04980",
    "dispensed_by":"Воронин Сергей Павлович",
    "dispense_details": [
      {
      "medication_id": "518d4d3e-508a-4f49-a4bc-6e5d92c1068e",
      "medication_qty": 10,
      "sell_price": 15,
      "sell_amount": 150,
      "discount_amount": 150
      }
    ]
  }
}'
```
and receive response
```
{
    "meta": {
        "url": "http://api-svc.il/api/medication_dispenses",
        "type": "object",
        "request_id": "cfd85ed3-9c8f-4685-bde8-b3dba929cf83#35889",
        "code": 409
    },
    "error": {
        "type": "request_conflict",
        "message": "Medication request is not active"
    }
}
```

**Comment by AlekzandrV** [comment]
@danakonovalenko 

Problem 1
According to [Scopes Model](https://edenlab.atlassian.net/wiki/spaces/EH/pages/2004415/Scopes+model) you must have medication_request:read scope to get list and medication_request:details to get by ID. Your token contains only medication_request:details - so service respond correctly

Problem 2
For the same request i receive
```
{
  "meta": {
    "url": "http://api-svc.il/api/medication_dispenses",
    "type": "object",
    "request_id": "e9520d7b-eaed-4698-a50b-580e3b4895e4#39003",
    "code": 409
  },
  "error": {
    "type": "request_conflict",
    "message": "Medical program is not active"
  }
}
```
and this correct because this program is not active.
BUT! This is incorrect medical_program_id for this medication_request. In DB stored another medical_program_id (`580a631c-f2cb-4d0b-8247-69bda40e8c0a`)
