### ISSUE TITLE
Login/signup documentation

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#2549]
There should be a sequence diagram that describes the technical process and interaction of all the FE and BE components (auth FE, cabinet FE, IL, mithril, kong, etc), different tokens generation during the below processes: 
- [x] login using email
  - [x] 2FA
- [ ] login using DS
  - [ ] 2FA
- [x] forgot pswrd
- [x] change pswd
- [ ] sign-up using DS
- [ ] change 2FA
- [ ] reset auth method
@AlekzandrV @svetavedmed @PavelVesnin @kiurchv FYI

**Comment by ivchenkodima** [comment]
https://edenlab.atlassian.net/wiki/spaces/EH/pages/142377058/2-Factor+Authentication

**Comment by ivchenkodima** [comment]
[OAuth 2 flow with 2-Factor Authentication.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5922fcd2d1adc26f61f2e896/125516c66e82c728ace21e0d46c7b58f378ac3fbcfefb34cb31de79d3d4e67216422a228648af1689e576f090a010af512091b1da3a79b37b4f67e2fd00958a9c3674d71cf3c40f8b9d717bc07bf74dd4885b7bfd918c1b96b26b699935d7c4f5b4cd6a2047ff5db59c24af74ceb4c50a7103761e77e3e754f94166761.txt)
![OAuth 2 flow with 2-Factor Authentication.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5922fcd2d1adc26f61f2e896/125516c66e82c728ace21e0d46c7b58f378ac3fbcfefb34cb31de79d3d4e67216422a228648af1689e576f090a010af512091b1da3a79b37b4f67e2fd00958a9c3674d71cf3c40f8b9d717bc07bf74dd4885b7bfd918c1b96b26b699935d7c4f5b4cd6a2047ff5db59c24af743eb4c50a7103761e77f347d45971b6761.png)

**Comment by ivchenkodima** [comment]
[Forgot_Change Factor Flows.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5922fcd2d1adc26f61f2e896/125516c66e82c728ace21e0d46ce9b88248d9796ace1be4da358b0b22845337c3b4485277f92f06af3006b1300051bff054a5556f9f0887af2b76978895a0eb9876a5f75c56e45ade9d41cee13a632c91edbe2e3d7158abd7f37ed998e46341f001b8afe5f34a99d49cb5df259ac.txt)
![Forgot_Change Factor Flows.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5922fcd2d1adc26f61f2e896/125516c66e82c728ace21e0d46ce9b88248d9796ace1be4da358b0b22845337c3b4485277f92f06af3006b1300051bff054a5556f9f0887af2b76978895a0eb9876a5f75c56e45ade9d41cee13a632c91edbe2e3d7158abd7f37ed998e47341f001b8afe5f34a99d4fcb5af459ac.png)
