### ISSUE TITLE
New declaration_request creation API

### ISSUE THREAD

**Issue by ehealthua-tech** [edenlabllc/ehealth.api#2641]
Первым этапом следует изменить форму декларации согласно данного документа: 
https://github.com/edenlabllc/ehealth.api/files/2232849/declaration.1.pdf

Вторым этапом рассмотреть возможности изменения в API
Нова декларації (у редакції від 29.05.18) призводить до деяких змін в API.
Було зроблено порівняльну таблицю та визначено пункти, що потребують змін в API (позначено червоним кольором в стовпцях F, G)
https://docs.google.com/spreadsheets/d/1fm1Ddpc1sYsPGjLzu7DA7y43V68ggdloyDi08sCriCI/edit#gid=0

**Comment by lymychp** [comment]
нова форма декларації [declaration (1).pdf](https://github.com/edenlabllc/ehealth.api/files/2232849/declaration.1.pdf)

**Comment by svetavedmed** [comment]
API changes
- [ ] add field "national_id" - json schema
- [ ] make registration address optional - json schema
- [ ] make confidant_person birth_date optional - json schema

**Comment by lymychp** [comment]
should be api v2

**Comment by marinakr** [comment]
@AlekzandrV  @svetavedmed  So, now create declaration online from cabinet should be updated to described task, or use two versions of api? Also, can you provide json schema on create declaration online and I can check responses  in test according to this schema

**Comment by svetavedmed** [comment]
json schema for create declaration request online - https://github.com/edenlabllc/ehealth.api/blob/develop/apps/core/specs/json_schemas/declaration_request/declaration_request_create_online.json

**Comment by svetavedmed** [comment]
- [ ] add confidant_person.preferred_way_communication and confidant_person.email to MAN

**Comment by svetavedmed** [comment]
- [ ] in case more then one person found, the las one should be saved to declaration_request.mpi_id

example: person with tax_id='3378115538', birth_date='1999-12-19'
there are three active person in DB with such parameters: 46bc69fd-2fb9-4d2f-bec2-f1c9a9e32da5, af919404-5f4e-4a61-b147-7eae04265fd2
But the new one is created
