### ISSUE TITLE
Tune OPS database properly and check it

### ISSUE THREAD

**Issue by marinakr** [edenlabllc/ehealth.api#2701]
1) Tune postresql.config file: shared buffers, work mem, maintenance work mem, ensure max connections is correct for  applications, ensure OS kernel resources is enough, etc

2) Fill tables with data (size of tables should be equal or bigger than size tables in prod) and
 check query plans for actual queries based on index scans only, check performance operations like insert/update

Before start it make sense add ```pg_stat_statements``` and store statistic of queries to know statistic about most frequency queries, most slow queries and make checks with this queries

- [ ] create extention analyze queries (query statistic)
- [ ] save queries and create load based on this queries on test database to reproduce real load
- [ ] optimize postgresql.conf
- [ ] optimize slow queries

Links:
https://wiki.postgresql.org/wiki/Tuning_Your_PostgreSQL_Server
http://www.varlena.com/GeneralBits/Tidbits/annotated_conf_e.html
https://www.postgresql.org/docs/current/static/kernel-resources.html
https://wiki.postgresql.org/wiki/Index_Maintenance
Usage of statistic example: https://www.geekytidbits.com/performance-tuning-postgres/

**Comment by marinakr** [comment]
https://github.com/docker-library/postgres/issues/422

**Comment by marinakr** [comment]
Probably the problem is in docker. 
Local machine: 
1. Postgres installed and running on target system  from brew, 960504 records in table - query time 0.5 seconds
2. Postgres running in docker, 960504 records in table - query time 2-11 seconds

**Comment by marinakr** [comment]
random_page_cost = 0.1 #real cost of reading data on our discs (at least on dev), no seq scans

**Comment by marinakr** [comment]
https://wiki.postgresql.org/wiki/Lock_Monitoring -ensure no blocking queries

**Comment by marinakr** [comment]
Same query with same parameters runs few times in one second? 
Query time: 3.9s (very slow)
```"query": "SELECT count('*') FROM (SELECT d0.\"id\" AS \"id\", d0.\"employee_id\" AS \"employee_id\", d0.\"person_id\" AS \"person_id\", d0.\"start_date\" AS \"start_date\", d0.\"end_date\" AS \"end_date\", d0.\"status\" AS \"status\", d0.\"signed_at\" AS \"signed_at\", d0.\"created_by\" AS \"created_by\", d0.\"updated_by\" AS \"updated_by\", d0.\"is_active\" AS \"is_active\", d0.\"scope\" AS \"scope\", d0.\"division_id\" AS \"division_id\", d0.\"legal_entity_id\" AS \"legal_entity_id\", d0.\"declaration_request_id\" AS \"declaration_request_id\", d0.\"seed\" AS \"seed\", d0.\"reason\" AS \"reason\", d0.\"reason_description\" AS \"reason_description\", d0.\"overlimit\" AS \"overlimit\", d0.\"declaration_number\" AS \"declaration_number\", d0.\"inserted_at\" AS \"inserted_at\", d0.\"updated_at\" AS \"updated_at\" FROM \"declarations\" AS d0 WHERE ((d0.\"is_active\" = $1) AND (d0.\"legal_entity_id\" = $2)) AND (d0.\"status\" = ANY($3))) AS s0",
      "params": [
        "true",
        "c81f4869-8c82-4336-b769-987b8383c252",
        [
          "active"
        ]
      ],
      "log_type": "persistence",
      "duration": 3390.253,
      "decode_time": 0.084```
Time: 01:22:11.346, 18.08.2018
id: 
j5n8SWUB-Cfe-g5VOU_u 
1pj7SWUB-Cfe-g5VzuDu
AZn8SWUB-Cfe-g5Vob7L
u5n8SWUB-Cfe-g5VY3ti
0Zn8SWUB-Cfe-g5VeZGw
eJn8SWUB-Cfe-g5VHjk7
pZn8SWUB-Cfe-g5VTWXl
Mpj7SWUB-Cfe-g5Vu84t
A5n7SWUB-Cfe-g5V9g3I
0Zn8SWUB-Cfe-g5VeZGw
YZn8SWUB-Cfe-g5VCiN4
This is either kibana display method of one query or this query was launched 10 times ?

**Comment by marinakr** [comment]
add https://www.postgresql.org/docs/current/static/auto-explain.html auto explain on every query runs more that 3s(output plan of queries to postgres logs)

**Comment by marinakr** [comment]
update postgres config with actual number of connections and updated parameters according to real connection numbers

**Comment by marinakr** [comment]
![Screen Shot 2018-08-24 at 12.37.46 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b17be631b90030011a0d281/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6456f76b7191a379ed0c2856415b48bc21254d58eeb9cb74fce36f34985619e8d86c0e20c76819afbe874be906ba21881cd1b7eddc4f91fa2137a5dad11b61435c52dcbd4f3fb2984cc259f348e44c51a2163260e370356e0a.png)
-------------------------------------------------------------------------------------------------------------------------
Після ~2 днів відносно швидшої роботи пошуку декларацій по legal_entity_id відсортованих по inserted_at за параметрами статусу повернувся до повередньої екстремально повільної швидкості (сягає 6-15 секунд), отже поверхнева оптимізація побудовою індексів   та розширенням параметрів пам"яті не дала результатів, можливі причини:
1. 
  Екстремально повільні запити є нечастими  по відношенню до загального потоку запитів і виконуються з тим самим планом що і для швидких запитів, при низькому завантаженні диска, що неявно може  свідчити про lock-и запитів. Явних блокуючих  операцій системою не виконується.
Можлива причина:
```
DB_POOL_SIZE: "50"
```
Database pool size зависокий
З документації https://wiki.postgresql.org/wiki/Number_Of_Database_Connections
"A formula which has held up pretty well across a lot of benchmarks for years is that for optimal throughput the number of active connections should be somewhere near ((core_count * 2) + effective_spindle_count)" 
Тобто в випадку 8 ядер це приблизно 
```
17
```
. Або використовувати зовнішні пулери коннектів ([Документація](https://wiki.postgresql.org/wiki/Tuning_Your_PostgreSQL_Server), max_connections)
"Pg will usually complete the same 10,000 transactions faster by doing them 5, 10 or 20 at a time than by doing them 500 at a time. Determining exactly how many should be done at once varies by workload and requires tuning."
Статті про пострегс пул коннектів - 
https://developer.bring.com/blog/tuning-postgres-connection-pools/
"В противном случае эти connection’ы будут друг другу мешать и будут все время проводить в ожидании"
https://m.habr.com/company/oleg-bunin/blog/319018/ - актуально і  про автовакуум і enable_seqscan.
DB_POOL_SIZE = 50 - не критично висока кількість, і це не єдина проблема.
Проте зменшення DB_POOL_SIZE і max_connection_number дозволяє еквівалентно збільшувати work_mem для запиту 

2. B-TREE index 
Зараз пошук по  B-TREE index

```
"declarations_legal_entity_inserted_at_index" btree (legal_entity_id, inserted_at)
plan
->  Index Scan using declarations_legal_entity_inserted_at_index on declarations d0  (cost=0.56..66183.53 rows=15569 width=405)
            Index Cond: (legal_entity_id = $2)
            Filter: ((is_active = $1) AND ((status)::text = ANY ($3)))
```
"Слабые стороны B-Tree индексов:∙ занимают много места на диске. Индекс по уникальным Integer-ам,к примеру, весит в два раза больше аналогичной колонки (т.к. хра-нятся ещё и RowId);∙ при постоянной записи дерево начинает хранить данные разреженно(сразу после построения они могут лежать очень плотно), и время доступа увеличивается за счёт увеличения объёма дисковой информации. Поэтому B-Tree индексы требуют присмотра и периодическо-го перепостроения (REBUILD) ([Книга](https://postgresql.leopard.in.ua/html/), розділ 3.1 "Типи індексів")
"
REBUILD - блокуюча операція, неблокуючий варіант - складати новий індекс по тим же колонкам, старий видаляти після побудови нового.
Зауваження - 1)  Потрібно також деталізувати індекс і зменшити фільтри додавши   status третім полем в індекс, і будувати частково по активним деклараціям
```
CREATE index CONCURRENTLY IF NOT EXISTS declarations_legal_entity_inserted_at_status_active_ix  ON declarations (legal_entity_id, inserted_at desc, status) where is_active;
```
Попередній після цього видалити
```
DROP INDEX CONCURRENTLY IF  EXISTS
         declarations_legal_entity_inserted_at_index;
```
Тоді план запиту виключно індекс сканування відповідних записів без подальшої фільтрації після зчитування з таблиці
```
 Limit  (cost=29.30..29.30 rows=1 width=247) (actual time=0.647..0.666 rows=80 loops=1)
   ->  Sort  (cost=29.28..29.30 rows=5 width=247) (actual time=0.638..0.649 rows=130 loops=1)
         Sort Key: inserted_at DESC
         Sort Method: top-N heapsort  Memory: 92kB
         ->  Index Scan using declarations_legal_entity_status_active on declarations d0  (cost=0.56..29.22 rows=5 width=247) (actual time=0.047..0.411 rows=377 loops=1)
               Index Cond: ((legal_entity_id = 'e74e349d-4470-4e2d-af41-7de69acffd69'::uuid) AND ((status)::text = ANY ('{active,pending_verification}'::text[])))
```
В випадках коли індекс містить багато записів з legal_entity_id що відповідає умовам пошуку але status aбо is_active не відповидає це значно прискорить пошук.
Але  повністю не вирішить проблему, бо в будь-якому випадку  індекс потребуватиме часту періодичну перебудову, тому що навіть на SSD дисках доступ по індексу виконується довше ніж до таблиці,а після значної кількості оновлених записів файл індексу "розпливеться"

 Автовакууми 
Обрати вищу частоту автовакуумів вже після пунктів 1 і 2

**Comment by marinakr** [comment]
- [ ] random_page_cost  = 1
На практиці в нашому середовищі для бази OPS зчитувати індекс швидше, ніж сканити таблцицю чи будувати хеш-функції
Для оптимізації планів треба на приблизно на добу знизити параметр до 1 (зараз 1.1) 
random_page_cost  = 1 в файлі конфігу і перезавантажити конфіг (select pg_reload_conf()) Запроси з хешем (бітмап сканами) після індексу де достатьно index only scan мають  обрати коррекний план з  index only scan
