### ISSUE TITLE
Composite

### ISSUE THREAD

**Issue by IrinaRevutska** [edenlabllc/ehealth.api#2805]
As a Doctor  
I want to be able to submit visit data to eHealth DB  
So all the patient medical data would be stored in one central component and could be reused by another medical provider or NHS to provide better quality of care  

- [x] Submit Visit Package parent of #2809 
- [ ] Submit Visit Package advanced parent of #2930
- [ ] Create Observations, AIs, Immunizations via Composite parent of #3032
