### ISSUE TITLE
Encounter

### ISSUE THREAD

**Issue by IrinaRevutska** [edenlabllc/ehealth.api#2813]
As a Doctor  
I want to be able to view encounters
So that I can study history of interactions between patient end medical service providers 

and cancel encounters 
So that  I can fix my mistakes  (in case entered in error)

- [x] Create parent of #2930
- [ ] Get parent of #2812
- [ ] Dismiss parent of #2831
