### ISSUE TITLE
Remove declaration_limit, declaration_count from declaration side

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#2863]
As declaration_limit is moved to contracts (#2715) it should not be checked on declaration approve

- [ ] remove `overlimit` from [employee_create](https://uaehealthapi.docs.apiary.io/#reference/public.-medical-service-provider-integration-layer/employee-requests/create-employee-request), employee in DB and create migration
- [ ] remove `overlimit` from employee_create json_schema
- [ ] declaration_count, declaration_limit from responses
- [get employee list](https://uaehealthapi.docs.apiary.io/#reference/public.-medical-service-provider-integration-layer/employees/get-employees-list)
- [get employee by ID](https://uaehealthapi.docs.apiary.io/#reference/public.-medical-service-provider-integration-layer/employees/get-employee-details)
- [deactivate employee](https://uaehealthapi.docs.apiary.io/#reference/public.-medical-service-provider-integration-layer/employees/deactivate-employee)
- [ ] remove declaration_limit validation from [Approve declaration request](https://edenlab.atlassian.net/wiki/x/syIQ)
```
Check doctor's limit
Get employee.id from declaration request
get party for employee_id
Find all employees in status= 'APPROVED' for the party. Count all declaration in status='active' for these employees. 
If amount of declaration for party >= parties.declaration_limit and declaration.overlimit is not true
return error 422 - This doctor reaches his limit and could not sign more declarations 
```
- [ ] remove declaration_count from report.party DB, create migration
- [ ] do not increment/decrement declaration on report.party according to number of declarations for employees

P.S. we should inform MISes about these changes

**Comment by warehousman** [comment]
All Done - Documentation should be adjusted
