### ISSUE TITLE
Cabinet Safari v10.1 testing 

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#2886]
As a registered in cabinet patient I want to find a doctor using search page
- [x]  - if input settlement name the result is shown for a very short period and then returns to default result and show it
- can't find by doctor's name or division's name as input fields are auto cleared
- search by doctor's speciality doesn't work

- [ ] placeholder and input text are covering each other as in screenshot 
![image 3](https://user-images.githubusercontent.com/31403196/43640944-8354842a-972a-11e8-81d3-9b38d940ba5f.png)

- [ ] after first input all next changes will be shown with error  'incorrect input'

<img width="663" alt="screen shot 2018-08-03 at 2 44 50 pm" src="https://user-images.githubusercontent.com/31403196/43641325-e4f8fc8c-972b-11e8-875f-ac2f90816cd6.png">

**Comment by kiurchv** [comment]
blocked by edenlabllc/ehealth.web#183
