### ISSUE TITLE
Reimbursement NHS admin portal bugs

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#2890]
- [x] *Create program medication page*
there is no program list in drop down list (not found value)
- [x] fix page pointer 
- [x] change birth_date to age on *medication request details* and *medication dispense details* pages
- [x] fix medication dispense details page
<img width="586" alt="screen shot 2018-08-06 at 1 16 46 pm" src="https://user-images.githubusercontent.com/31403196/43711365-1d315fc6-997b-11e8-959c-2144bfda3f84.png">

**Comment by danakonovalenko** [comment]
from fields with input type 'number' hide right bar
<img width="158" alt="screen shot 2018-08-09 at 6 18 23 pm" src="https://user-images.githubusercontent.com/31403196/43908664-36f802a6-9c01-11e8-9d64-1c582b166183.png">
