### ISSUE TITLE
Change capitation report details for merged legal entities

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#3131]
Change capitation report view policy:
- [ ] merge_from_legal_entity sees only its own report
- [ ]  merge_to_legal_entity can see its own contracts and contracts of connected to it merge_from_legal_entity
- [X] nhs admin can see all contracts
- [ ] replicate `releated_legal_entitites` to reports
[get capitation report details](https://edenlab.atlassian.net/wiki/x/BABZIw)
[apiary](https://uaehealthapi.docs.apiary.io/#reference/public.-medical-service-provider-integration-layer/capitation-reports/get-capitation-report-details)

**Comment by marinakr** [comment]
eplicate releated_legal_entitites to reports @dhlebnikov1

**Comment by svetavedmed** [comment]
capitation_report_details is not filtered by legal_entity

**Comment by marinakr** [comment]
@svetavedmed any news?

**Comment by svetavedmed** [comment]
- [ ] 500 on get report details by wrong report_id
request
```
curl -X GET \
  'https://api.dev.asclepius.com.ua/api/capitation_report_details?report_id=00b1b4c7-4f01-4525-bce9-2e82c68c88361' \
  -H 'Authorization: Bearer NjJsZnlXeWtmWG5kZlh4YjFnUEMzQT09' \
  -H 'Postman-Token: 2fdd2bc2-b3b3-4446-90f7-04d1f56d760e' \
  -H 'api-key: ejJ1VWFqZlNUUlpmMWNIMmc0YTB1UT09' \
  -H 'cache-control: no-cache'
```
response
```{
    "error": {
        "errors": {
            "detail": "Internal server error"
        }
    },
    "meta": {
        "code": 500,
        "request_id": "7d1fc753-0047-4aa7-babf-a667cb1402ef#7967",
        "type": "object",
        "url": "http://api-svc.il/api/capitation_report_details"
    }
}
```
