### ISSUE TITLE
Update contract request assignee rest API

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#3224]
As NHS admin I want to be able to assign Contract Requests to NHS employees using NHS admin legacy.
In order to do that rest WS must be implemented based on

 - [x] [confluence](https://edenlab.atlassian.net/wiki/x/X4FLJw)
 - [x] [apiary](
https://uaehealthapi.docs.apiary.io/reference/public.-contracts/contract-request/private.-assign-contract-request-by-nhs-employee)
 - [x]  add field assignee_id to il.contract_request
 - [x] for Update/Approve/Decline check contract_request.status=IN_PROCESS (as for now status=NEW)
- [x] implement
- [ ] test

**Comment by danakonovalenko** [comment]
```
{
    "meta": {
        "url": "http://api.dev.asclepius.com.ua:8000/api/contract_requests/c346c469-1554-43fe-8708-68da843c14fb/actions/assign",
        "code": 403,
        "request_id": "5386d3e9-0d55-41ba-bb61-f06ec599f5d1#11866",
        "type": "object"
    },
    "error": {
        "message": "ACL: No matching rule was found for path /api/contract_requests",
        "type": "forbidden"
    }
}
```

**Comment by danakonovalenko** [comment]
please, male some changes according to [test cases](https://edenlab.atlassian.net/wiki/x/yQDlJw)

**Comment by danakonovalenko** [comment]
I can add DISMISSED employee as assigner. Must be fixed
