### ISSUE TITLE
Get Contract Details GraphQL

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#3245]
As NHS admin I want to be able to get Contract Details using new admin portal.
So, we need to implement it using graphql
- [x] [confluence](https://edenlab.atlassian.net/wiki/x/MoCeHw) / [schema]() / features
- [x] implement 
- [ ] test

**Comment by danakonovalenko** [comment]
things to be changed or fixed:
- [ ] instead of `contractRequestId` we should use `contractRequest:ContractRequest`
- change in both schema and implementation
- [ ] `parentContract` can be null. Now I receive error `Cannot return null for non-nullable field`
- change in schema `parentContractId` to `parentContract:Contract`
- [ ] `attachedDocuments` return null response
