### ISSUE TITLE
Reports on medical_event collection

### ISSUE THREAD

**Issue by Troush** [edenlabllc/ehealth.api#3274]
- [ ] Create MongoDB ODBC Connection to Power BI on Dev

- [ ] Create Reports with DEV PowerBI

- [ ] Deploy on prod

- [ ] Run test reports on PROD

**Comment by Troush** [comment]
As we already deployed mongodb connector. @danakonovalenko or @IrinaRevutska can proceed with generating reports.
