### ISSUE TITLE
Create contract_request: Apply different JSON Schema depending on contract_type

### ISSUE THREAD

**Issue by IrinaRevutska** [edenlabllc/ehealth.api#3358]
- [x] Add contract_type to capitation version of a contract_request/contract (Ira)
- [x] Create JSON schema for reimbursement version of contract_request (Ira)
- [x] Apply new JSON schemas and validate JSON on post contract_request based on contract_type according to [spec](https://edenlab.atlassian.net/wiki/spaces/EH/pages/523960439/Create+Contract+Request#CreateContractRequest-Inputparameters), save contract_type to DB ([DataModel](https://edenlab.atlassian.net/wiki/spaces/EH/pages/523960362/Contract+Data+model),)
[Apiary](https://uaehealthapi.docs.apiary.io/#reference/public.-contracts/contract-request/public.-create-contract-request)

**Comment by svetavedmed** [comment]
- [ ] for contract create get contractor_legal_entity_id from tokens. Set contractor_legal_entity_id = client_id
- [ ] for reimbursement contracts validate contractor_owner_id has 'PHARMACY_OWNER' employee_type. And for capitation contracts -- 'OWNER' employee_type

**Comment by svetavedmed** [comment]
- [ ] Create CR with   "type": "capitation"
I can send json fot CR with  "type": "capitation" to /api/contract_requests/reimbursement/{id}. Nevertheless contract will be created with type REIMBURSEMENT, so maybe we do not need to send type in payload
- [ ] create reimbursement CR with correct previous_request_id
repo steps
request - [CCR30.txt](https://zube.io/files/edenlabllc/59907ff3c61f0bcf8eeb14144678e4c9-ccr30.txt)
response
```
{"error":{"invalid":[{"entry_type":"request","rules":[{"rule":"json"}]}],"message":"previous_request_id does not exist","type":"request_malformed"},"meta":{"code":422,"request_id":"716dadd1-ecf0-4b65-ae77-612f44399e2b#12760","type":"object","url":"http://api-svc.il/api/contract_requests/reimbursement/7228644d-a5a5-4dab-a276-f46511656de8"}}%
```
- [ ] error 500 with contractor_divisions="453e5c68-4761-4266-ab0e-36515881d421"
request - [CCR31.txt](https://zube.io/files/edenlabllc/d68fe785f943d0a26c1e0519e1adf919-ccr31.txt)
response
```
{"status":500,"request_id":"716dadd1-ecf0-4b65-ae77-612f44399e2b#12818","path":"/api/contract_requests/reimbursement/7228644d-a5a5-4dab-a276-f46511656de8","method":"POST","log_type":"http","handler":"Elixir.EHealth.Web.ContractRequestController#create","duration":2693.213,"date_time":"2018-12-12T14:27:04Z","api_version":"*/*"}
```

**Comment by PavelVesnin** [comment]
@svetavedmed 
Contract request by id `7228644d-a5a5-4dab-a276-f46511656de8` (previous_request_id in [request](https://zube.io/files/edenlabllc/59907ff3c61f0bcf8eeb14144678e4c9-ccr30.txt)) does not exist in 
 database. 
So it's expected behavior

**Comment by svetavedmed** [comment]
- [ ] for reimbursement contracts documents should be optional

**Comment by svetavedmed** [comment]
- [ ] i can see any links no matter if there are documents or not
- [ ] error on approve CR by NHS for update reimbursement contract by new contract request. "contract_number": "0000-35MM-M000"

**Comment by PavelVesnin** [comment]
links and approve fixed

**Comment by svetavedmed** [comment]
- [ ] [on create](https://uaehealthapi.docs.apiary.io/#reference/public.-contracts/contract-request/public.-create-contract-request) move to fixed links only document that are mentioned in json
