### ISSUE TITLE
Make license_number required for Pharmacy on create LE

### ISSUE THREAD

**Issue by IrinaRevutska** [edenlabllc/ehealth.api#3370]
- [x] Try it on JSON Schema level
Result: It works but the error is not readable enough:
```
Message:
JSON does not match schema from 'else'.
Schema path:
#/else/else
```
- [ ]  Make it on application level

+ example on confluence (IRA)

**Comment by svetavedmed** [comment]
- [ ] 500 on create legal_entity
```
{
    "error": {
        "type": "internal_error"
    },
    "meta": {
        "code": 501,
        "request_id": "7d1fc753-0047-4aa7-babf-a667cb1402ef#4497",
        "type": "object",
        "url": "http://api-svc.il/api/legal_entities"
    }
}
```
