### ISSUE TITLE
Show is_active attribute in employee responses

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#3391]
As a MPS HR
I want to see current employee(OWNER) state
So that i can correctly manage my employees

Update the following responses. Add _**is_active**_ attribute:
- [ ] [Get employee details](https://uaehealthapi.docs.apiary.io/#reference/public.-medical-service-provider-integration-layer/employees/get-employee-details) 
- [ ] [Deactivate employee](https://uaehealthapi.docs.apiary.io/#reference/public.-medical-service-provider-integration-layer/employees/deactivate-employee)
- [ ] [Get employee ID by employee request ID](https://uaehealthapi.docs.apiary.io/#reference/public.-medical-service-provider-integration-layer/employee-requests/get-employee-id-by-employee-request-id)

**Comment by svetavedmed** [comment]
is duplicated by #3389
