### ISSUE TITLE
Release 8.8 to demo

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#3421]
# New release deployment preperation checklist
- [x] prepare [release notes](https://github.com/ehealth-ua/api-spec/pull/561)
- [x] prepare all the release specific chekpoints: what should be checked in addition to the postman collection tests for this specifica release @svetavedmed @IrinaRevutska 
- [x] prepare all the DB scripts that should be executed and that were not included in the migrations (configurations, scopes, etc.)
- [x] create PR with the new version of API specs in the repo https://github.com/ehealth-ua/api-spec

# todo checklist that should be used for any eHealth deployment

- [x] define required versions of repo to the destination env.
- [x] prepare releases of all repos for the demo env. @AlexKovalevych 
~- [ ] IL.dictionaries - add/update if any. IDs should be the same.~
- [x] PRM.global_parameters - add/update if any. IDs should be the same
- [x] uaddresses - add/update records if any. IDs should be the same
- [x] GW.apis - migrate config
  - [ ] GW.apis - Exclude temp dev routes
- [x] Mithril config
  - [ ] client_types - add/update if any changes.
  - [ ] roles - add/update if any changes.
  - [ ] user_roles - for admin fronts
  - [ ] clients for mithril.admin, nhs.admin, uaddresses.admin
  - [ ] tokens - generate new tokens with new scopes in case if new endpoints are released
  - [ ] approvals - generate or copy MIS approvals
- [x] man templates - add/update if any. IDs should be the same
- [x] DS - migrate certificates if any
- [x] NHS admin config
  - [ ] set/change configuration values in case if new configuration is added or system is deployed to new environment firtst time

# post-release check-list (WIP)
- [x] cluster metrics
- [x] service metrics
- [x] API health-checks
- [ ] merge PR with the new version of API specs in the repo https://github.com/ehealth-ua/api-spec
- [x] login/sanity check of NHS admin
- [x] login/sanity check of UAddresses admin
- [x] manual sanity check of new deployed features (should be taken from the Release Notes)
- [x] check backups
- [ ] check logs in kibana
- [ ] check graphana monitoring metrics
- [ ] check reports and fraud DB replication status
  - [ ] overall replication status
  - [ ] every table status
- [ ] check dictionaries
- [ ] check scopes
- [ ] check that mpi.persons triggers is enabled
