### ISSUE TITLE
Add Employee Type

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#3440]
We need to implement Employee Type according to [schema](
https://github.com/edenlabllc/ehealth.schema/blob/master/__schema__/employees.graphql)

**Comment by danakonovalenko** [comment]
next steps should be done or fixed:
- [ ] update EmployeeType schema
- [ ] add 2 employee types (to filter values) - `HR` and `NHS`
- [ ] when I try to get employeeType in response 500 is received, must be fixed
- [ ] add fields `insertedAt`, `updatedAt` to EmployeeType

[test cases](https://edenlab.atlassian.net/wiki/x/BIB2K)
