### ISSUE TITLE
Reimbursement contracts

### ISSUE THREAD

**Issue by IrinaRevutska** [edenlabllc/ehealth.api#3447]
As NHS a want to be able to create contracts with pharmacies in order to implement reimbursement program.

Decided to use already implemented contracts as a base and divide it into two types: capitation & reimbursement

~ Tasks~
- [ ] Split and apply JSON schemas for all contract\contract request endpoints, redisign BE logic
parent of edenlabllc/ehealth.api#3358
parent of edenlabllc/ehealth.api#3360
parent of edenlabllc/ehealth.api#3361
parent of edenlabllc/ehealth.api#3448

parent of edenlabllc/ehealth.api#3449

parent of edenlabllc/ehealth.api#3450

parent of edenlabllc/ehealth.api#3451

parent of edenlabllc/ehealth.api#3453

parent of edenlabllc/ehealth.api#3522

parent of edenlabllc/ehealth.api#3523

parent of edenlabllc/ehealth.api#3524

parent of edenlabllc/ehealth.api#3521

parent of edenlabllc/ehealth.api#3518

parent of edenlabllc/ehealth.api#3599

parent of edenlabllc/ehealth.api#3601

- [ ] New validation on create LE type pharmacy
parent of edenlabllc/ehealth.api#3370
- [ ] New validations on dispense
parent of edenlabllc/ehealth.api#3359
- [ ] Remove reimbursment contracts from capitation reports
parent of edenlabllc/ehealth.api#3362
- [ ] New FE logic, design

parent of edenlabllc/ehealth.api#489

parent of edenlabllc/ehealth.api#487

parent of edenlabllc/ehealth.api#486

parent of edenlabllc/ehealth.api#485

parent of edenlabllc/ehealth.api#490

parent of edenlabllc/ehealth.api#491

parent of edenlabllc/ehealth.api#492
