### ISSUE TITLE
Update contract_request: Apply different JSON Schema depending on contract_type

### ISSUE THREAD

**Issue by IrinaRevutska** [edenlabllc/ehealth.api#3448]
- [x] Add contract_type [Apiary](https://uaehealthapi.docs.apiary.io/#reference/public.-contracts/contract-request/private.-update-contract-request-by-nhs-signer)
- [x] Validate that nhs_contract_price is empty in case of reimbursement contract [spec](https://edenlab.atlassian.net/wiki/spaces/EH/pages/523731056/Update+Contract+Request+by+NHS) (p.4.a)
- [x] Validate that contract_type on update == contract_type on create [spec](https://edenlab.atlassian.net/wiki/spaces/EH/pages/523731056/Update+Contract+Request+by+NHS) (p.3)

[DataModel](https://edenlab.atlassian.net/wiki/spaces/EH/pages/671252546/Contract+Reimbursment+version+Data+model)

**Comment by lymychp** [comment]
agreed to add json-schema
