### ISSUE TITLE
LE approve new. GraphQL

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#3469]
- [x] add mutations
   - nhs_reviewed = true
   - nhs_verified = false
   - comment
- [x] change logic for 
   - comment - could be set only after nhs_reviewed = true
   - [deactivate LE](https://uaehealthapi.docs.apiary.io/#reference/public.-medical-service-provider-integration-layer/legal-entities/deactivate-legal-entity) - could be changed only after nhs_reviewed = true
   - [verify LE by NHS](https://uaehealthapi.docs.apiary.io/#reference/public.-medical-service-provider-integration-layer/legal-entities/verify-legal-entity-by-nhs) - could be changed only after nhs_reviewed = true
- [x] change get LE by nhs' add new fields 
   - comment
   - nhs_reviewed with filters

**Comment by progsmile** [comment]
add `nhs_verified = false`

**Comment by svetavedmed** [comment]
- [ ] add nhsReview to get LE list with ordering nhsReview_ASC, nhsReview_DESC [PR](https://github.com/edenlabllc/ehealth.web/pull/507/files)

**Comment by svetavedmed** [comment]
- [ ] add nhsReview to get LE list with ordering nhsReview_ASC, nhsReview_DESC [PR](https://github.com/edenlabllc/ehealth.web/pull/507/files)

**Comment by svetavedmed** [comment]
- [ ] add nhsReview to get LE list with ordering nhsReview_ASC, nhsReview_DESC [PR](https://github.com/edenlabllc/ehealth.web/pull/507/files)

**Comment by svetavedmed** [comment]
- [ ] should be forbidden to set "nhsReviewed": false by NHS. Only on update legal_entity "nhsReviewed" flag should (and it is) set to false.
