### ISSUE TITLE
LE approve new

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#3470]
as NHS admin I want to review legal_entity with tracking statuses of reviewing and approving so that I know if legal_entity is created correctly or should be changed

BE
- [ ] LE approve new. Rest. parent of #3468
- [ ] LE approve new. GraphQL. parent of #3469

FE
- [ ] LE approve new. GraphQL. parent of #463

**Comment by svetavedmed** [comment]
- [ ] Change section Verification in Admin panel. parent of edenlabllc/ehealth.web#588
- [ ] deactivate roles for dismissed employee on deactivate LE. parent of #3791
