### ISSUE TITLE
Release 8.8 to prod

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#3531]
related to #3489 
# New release deployment preperation checklist
- [x] prepare [release notes](https://github.com/ehealth-ua/api-spec/pull/561)
- [x] prepare all the release specific chekpoints: what should be checked in addition to the postman collection tests for this specifica release @svetavedmed @IrinaRevutska 
- [x] prepare all the DB scripts that should be executed and that were not included in the migrations (configurations, scopes, etc.)
- [x] create PR with the new version of API specs in the repo https://github.com/ehealth-ua/api-spec

# todo checklist that should be used for any eHealth deployment

- [x] define required versions of repo to the destination env.
- [x] prepare releases of all repos for the demo env. @AlexKovalevych 
~- [ ] IL.dictionaries - add/update if any. IDs should be the same.~
- [x] PRM.global_parameters - add/update if any. IDs should be the same
- [x] uaddresses - add/update records if any. IDs should be the same
- [x] GW.apis - migrate config
  - [x] GW.apis - Exclude temp dev routes
- [x] Mithril config
  - [x] client_types - add/update if any changes.
  - [x] roles - add/update if any changes.
  - [x] user_roles - for admin fronts
  - [x] clients for mithril.admin, nhs.admin, uaddresses.admin
  - [x] tokens - generate new tokens with new scopes in case if new endpoints are released
  - [x] approvals - generate or copy MIS approvals
  - [x] run connections script
- [ ] man templates - add/update if any. IDs should be the same
- [x] DS - migrate certificates if any
- [x] NHS admin config
  - [x] set/change configuration values in case if new configuration is added or system is deployed to new environment firtst time
 - [x] deploy casher

# post-release check-list (WIP)
- [x] cluster metrics
- [x] service metrics
- [x] API health-checks
- [x] merge PR with the new version of API specs in the repo https://github.com/ehealth-ua/api-spec
- [x] login/sanity check of NHS admin
- [x] login/sanity check of UAddresses admin
- [x] manual sanity check of new deployed features (should be taken from the Release Notes)
  - [x] check DS check
  - [x] check mithril connections
- [x] check backups
- [x] check logs in kibana
- [x] check graphana monitoring metrics
- [x] check reports and fraud DB replication status
  - [x] overall replication status
  - [x] every table status
- [x] check dictionaries
- [x] check scopes
- [x] check that mpi.persons triggers is enabled
