### ISSUE TITLE
GQL API for Admin Panel v.2 for Capitation Contacts v.3

### ISSUE THREAD

**Issue by warehousman** [edenlabllc/ehealth.api#3553]
FrontEnd: https://github.com/edenlabllc/ehealth.web/issues/502

- [x] Contract Request list GraphQL GraphQL parent of #3226

- [x] Get Contract Request Details GraphQL parent of #3227  
- [x] Update Contract Request GraphQL parent of #3228  
- [x] Approve Contract Request GraphQL parent of #3229  
- [x] Decline Contract Request GraphQL parent of #3230

- [x] Get Printout content by contract request ID GraphQL parent of #3231

- [x] Sign Contract Request GraphQL parent of #3232

- [x] Contract Request Sign by NHS add Digital Stamp parent of #3233  
- [x] Assign Contract Request GraphQL parent of #3239

- [x] Get Contract Details GraphQL parent of #3245  
- [x] Get Contract List GraphQL parent of #3246  
- [x] Terminate Contract GraphQL parent of #3247

- [x] Add rawContractRequest field to ContractRequest type parent of #3461

**Comment by danakonovalenko** [comment]
parent of Contract Demo Comments #495
