### ISSUE TITLE
Merge Legal entities Process 

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#3557]
- [x] Merged legal entities table parent of 3140
- [x] Create related legal entities parent of #3113
- [x] Get children legal entity by NHS parent of  #3115
- [x] Prolongate contract for merged legal entities parent #3129
- [x] Get legalEntityMergeJobs #3251 
- [x] Merge legal entities token expiration #3320
