### ISSUE TITLE
Release 8.9 prod preparations

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#3829]
Action items now:
* check all the migrations that should be released @AlexKovalevych 
* prepare env. vars for preprod/prod @vsirius
- [x] ME plan
    - [x] check CEPH preprod @IrinaRevutska 
    - [x] set up CEPH on prod @vsirius
    - [x] create ME preprod test collection @IrinaRevutska 
    - [x] test preprod - run collection @IrinaRevutska 
    - [x] migrate patients to MongoDB in advance plan @AlexKovalevych 
    - [x] migrate to new kafka plan @vsirius
        - [x] test kafka cluster on dev @vsirius
        - [x] update charts - set up new kafka endpoints @vsirius
    - [x] mongodb
        - [x] smoke testing (10 pkg, observations, conditions) @IrinaRevutska 
- [x] ehealth.api
    - [x] check migrations@AlexKovalevych 
    - [x] prepare env. vars. @vsirius
