### ISSUE TITLE
Release 8.11 to demo

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#4011]
# New release deployment preperation checklist
- [x] prepare release notes that should include list of all the tickets or PRs that are going to be delivered with this release. 
    - [x] [ehealth.api](https://github.com/edenlabllc/ehealth.api/milestone/42) 
    - [x] [ehealth.web](https://github.com/edenlabllc/ehealth.web/milestone/20)
- [ ] prepare all the release specific chekpoints: what should be checked in addition to the postman collection tests for this specific release @danakonovalenko @IrinaRevutska @AlekzandrV @svetavedmed 
- [ ] prepare all the DB scripts that should be executed and that were not included in the migrations (configurations, scopes, etc.) @AlekzandrV @AlexKovalevych
- [ ] create PR with the new version of API specs in the repo 
     - [x] [api-spec](https://github.com/ehealth-ua/api-spec/pull/565)
     - [x] [medical_events.specs](https://github.com/ehealth-ua/medical_events.specs/pull/2)
- [ ] prepare the chart env. values for demo @dhlebnikov1 
- [ ] prepare strategy for all the mass migrations that should be performed with the release @vsirius @AlexKovalevych 
    - [ ] IL - add new field
    - [ ] mpi - migrate addresses to new tables

# todo checklist that should be used for any eHealth deployment

- [x] define required versions of repo to the destination env.
  - [x] ehealth.web
  - [x] BE services
- [x] apply the required versions of repo to the destination env.
  - [ ] ehealth.api
  - [ ] mpi.api
  - [ ] ael.api
  - [ ] digital_signature.api
  - [ ] man.api
  - [ ] mithril.api
  - [ ] ops.api
  - [ ] uaddresses.api
  - [ ] otp_verification.api
  - [ ] ehealth.web
~~- [ ] IL.dictionaries - add/update if any. IDs should be the same.~~
- [x] PRM.global_parameters - add/update if any. IDs should be the same
~~- [ ] uaddresses - add/update records if any. IDs should be the same~~
- [x] GW.apis - migrate config
  - [ ] GW.apis - Exclude temp dev routes
- [x] GW.plugins
- [x] Mithril config
  - [ ] client_types - add/update if any changes.
  - [ ] roles - add/update if any changes.
  - [ ] user_roles - for admin fronts
  - [ ] clients for mithril.admin, nhs.admin, uaddresses.admin
  - [ ] tokens - generate new tokens with new scopes in case if new endpoints are released
  - [ ] approvals - generate or copy MIS approvals
- [x] man templates - add/update if any. IDs should be the same
- [x] DS - migrate certificates if any
- [x] NHS admin config
  - [ ] set/change configuration values in case if new configuration is added or system is deployed to new environment firtst time

# post-release check-list (WIP)
- [x] cluster metrics
- [x] service metrics
- [x] API health-checks
- [x] merge PR with the new version of API specs in the repo https://github.com/ehealth-ua/api-spec
- [x] login/sanity check of NHS admin
- [x] sanity check of [nhs.portal](https://portal.ehealth.gov.ua/)
- [x] manual sanity check of new deployed features (should be taken from the Release Notes)
- [x] check backups
- [x] check logs in kibana
- [x] check graphana monitoring metrics
- [x] check reports and fraud DB replication status
  - [ ] overall replication status
  - [ ] every table status
- [x] check dictionaries
- [x] check scopes
