### ISSUE TITLE
Process merge request

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#4032]
As NHS admin reviewer of manual merge requests after merge candidate was assign to me I want to make decision on it.

There possible decision I can make are:
- POSTPONE
- MERGE / SPLIT / TRASH (final decisions) 

After merge request reach some amount of final decisions based and final decision is `MERGE` using Kafka declaration and person must be deactivated

In order to do that we need to implement mutation base on [logic](https://edenlab.atlassian.net/wiki/x/qIBVKg)  and schema

- [ ] implement
- [ ] [test cases](https://edenlab.atlassian.net/wiki/x/IQCrKg)

**Comment by svetavedmed** [comment]
- [ ] error on Postpone merge request

![Screen Shot 2019-02-11 at 9.14.49 AM.png](https://zube.io/files/edenlabllc/f309fe047d40b9e97977cabdc28817f1-screen-shot-2019-02-11-at-9-14-49-am.png)

**Comment by svetavedmed** [comment]
- [ ] in case i do not have merge requests in status NEW i still receive 'canAssignNew: false'
![Screen Shot 2019-02-11 at 9.29.49 AM.png](https://zube.io/files/edenlabllc/f990b54157a7814425abca6107a967b9-screen-shot-2019-02-11-at-9-29-49-am.png)

**Comment by svetavedmed** [comment]
- [ ] no record in audit_log_deduplication

**Comment by PavelVesnin** [comment]
@svetavedmed [PR](https://github.com/edenlabllc/mpi.api/pull/220) with audit_log implementation waiting for review

**Comment by PavelVesnin** [comment]
@svetavedmed audit log deployed on dev

**Comment by svetavedmed** [comment]
- [ ] in case there were three decisions with POSTPONE, I have a final decision in `manual_merge_candidates` with status PROCESSED and decision POSTPONE. 
It should not be a final decision POSTPONE
![Screen Shot 2019-02-25 at 12.27.54 PM.png](https://zube.io/files/edenlabllc/9abd885863e84efadab678c0046077dc-screen-shot-2019-02-25-at-12-27-54-pm.png)

**Comment by svetavedmed** [comment]
- [ ] after person was merged and deactivated no information in merged_ids

**Comment by PavelVesnin** [comment]
@svetavedmed merged_ids it's technical debt https://zube.io/edenlabllc/e-health/c/5399
