### ISSUE TITLE
Admin Panel Reimbursement contract fixes UAT

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#4086]
Only for Reimbursement contracts and Contract requests
- [x] rename 'Відділеня' to 'Підрозділи'
- [x] do not show mountain group for divisions
- [x] translate nhs_payment_method to Ukrainian
