### ISSUE TITLE
Authorize MIS using api-key only

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#4234]
**As a** MIS
**I want** to be able to access some endpoints (that doesn't belong to ehealth-user) having `api-key` only without `authorization` token
**So that** my code won't be dependent on human-factor and user availability (currently user should pass auth flow every two weeks) and I won't be forced to simulate user presence and store his credentials.

Kong plugin
 - [X] add api-key-endpoint as analog of current url-template works with api-key only
 - [x] change kong corresponding routes  to use api key verification or token verification
Mithril
  - [X] check if token exists in headers use token verification
  - [X] check api-key if no token exists in headers

**Comment by lymychp** [comment]
[test-cases](https://edenlab.atlassian.net/wiki/spaces/EH/pages/728170734/api-key+test+cases)

**Comment by marinakr** [comment]
@AlexKovalevych please help  with kong

**Comment by marinakr** [comment]
Before test, please ensure client has broker_scope legal_entity:write

**Comment by lymychp** [comment]
It shouldn’t be dependent on the broker scopes. Client type scopes should be checked instead

**Comment by marinakr** [comment]
@lymychp according to the code broker_scopes + scopes will be checked. Are you definitely sure to return empty broker scope?

**Comment by marinakr** [comment]
https://github.com/edenlabllc/mithril.api/pull/388

**Comment by lymychp** [comment]
Yes, in case if we do authorize using api-key, only client-type scopes should be checked

**Comment by lymychp** [comment]
@svetavedmed please update test collection for the below endpoints `api-key` should be used instead of token
GET /api/events/id

GET /api/events

POST /api/legal_entities

**Comment by svetavedmed** [comment]
on update legal_entity_v1 error
```
{
                "entry": "$.updated_by",
                "entry_type": "json_data_property",
                "rules": [
                    {
                        "description": "can't be blank",
                        "params": [],
                        "rule": "required"
                    }
                ]
            }
```

**Comment by lymychp** [comment]
tested on dev
