### ISSUE TITLE
Suspend contract by NHS

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#4305]
As NHS Admin 
I want suspend contract manually 
So that MSP should update contract
[confluence](https://edenlab.atlassian.net/wiki/x/pAAbKw)
[schema](https://github.com/edenlabllc/ehealth.schema/blob/master/__schema__/contracts.graphql)

- [x] add new field 'reason'
- [x] create migration for 'status_reason' 
      if 'status_reason' not like 'auto_%' move to 'reason'

- [x] REST changes
- on [terminate contract](https://uaehealthapi.docs.apiary.io/#reference/public.-contracts/contracts/private.-terminate-contract) 
      - validate 'status_reason' is in dictionary.contract_status_reason; 
      - add text field 'reason'
- on [get contract details](https://uaehealthapi.docs.apiary.io/#reference/public.-contracts/contracts/public.-get-contract-details) 
[update contract employees response](https://uaehealthapi.docs.apiary.io/#reference/public.-contracts/contracts/public.-update-contract-employees)
[terminate contract respinse](https://uaehealthapi.docs.apiary.io/#reference/public.-contracts/contracts/private.-terminate-contract)
[prolongate contract response](https://uaehealthapi.docs.apiary.io/#reference/public.-contracts/contracts/private.-prolongate-contract)
add 'reason' to response
- [x] add info to event manager

**Comment by svetavedmed** [comment]
- [ ] event type not a `StatusChangeEvent`, but `StateChangeEvent`
