### ISSUE TITLE
Release 8.12 to demo

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#4344]
# New release deployment preperation checklist
- [x] prepare release notes that should include list of all the tickets or PRs that are going to be delivered with this release. 
    - [x] [ehealth.api](https://github.com/edenlabllc/ehealth.api/milestone/44) 
    - [x] [ehealth.web](https://github.com/edenlabllc/ehealth.web/milestone/21)
- [x] prepare all the release specific chekpoints: what should be checked in addition to the postman collection tests for this specific release @IrinaRevutska @AlekzandrV @svetavedmed
- [x] update postman test collection @svetavedmed
- [x] prepare list of all the DB scripts that should be executed and that were not included in the migrations (configurations, scopes, etc.) @AlekzandrV @AlexKovalevych
- [x] create PR with the new version of API specs in the repo 
     - [x] [api-spec](https://github.com/ehealth-ua/api-spec/pull/567)
     - [x] [medical_events.specs](https://github.com/ehealth-ua/medical_events.specs/pull/4/files)
- [x] prepare the chart env. values for demo @liubenokvlad 
- [ ] prepare strategy for all the mass migrations that should be performed with the release @vsirius @AlexKovalevych 

# todo checklist that should be used for any eHealth deployment

- [x] define required versions of repo to the destination env.
  - [ ] ehealth.web @ephor
  - [ ] BE services @AlexKovalevych
- [x] apply the required versions of repo to the destination env.
  - [ ] ehealth.api
  - [ ] mpi.api
  - [ ] ael.api
  - [ ] digital_signature.api
  - [ ] man.api
  - [ ] mithril.api
  - [ ] ops.api
  - [ ] uaddresses.api
  - [ ] otp_verification.api
  - [ ] ehealth.web
- [x] IL.dictionaries - add/update if any.
- [x] PRM.global_parameters - add/update if any. IDs should be the same
~~- [x] uaddresses - add/update records if any. IDs should be the same~~
- [x] kong - ensure that all new released endpoints has been configured
- [ ] Mithril config
  - [ ] client_types - add/update if any changes.
  - [ ] roles - add/update if any changes.
  - [ ] user_roles - for admin fronts
  - [ ] clients for mithril.admin, nhs.admin, uaddresses.admin
  - [ ] tokens - generate new tokens with new scopes in case if new endpoints are released
  - [ ] approvals - generate or copy MIS approvals
- [x] man templates - add/update if any. IDs should be the same
~~- [ ] DS - migrate certificates if any~~
- [ ] NHS admin config
  - [ ] set/change configuration values in case if new configuration is added or system is deployed to new environment firtst time
  - [ ] apply new logs parsing patterns if any @liubenokvlad

# post-release check-list (WIP)
- [ ] cluster metrics
- [ ] service metrics
- [ ] API health-checks
- [ ] merge PR with the new version of API specs in the repo https://github.com/ehealth-ua/api-spec
- [ ] login/sanity check of NHS admin
- [ ] sanity check of [nhs.portal](https://portal.ehealth.gov.ua/)
- [ ] manual sanity check of new deployed features (should be taken from the Release Notes)
  - [ ] deduplication
  - [ ] check merged_ids
- [ ] check backups
- [ ] check logs in kibana
  - [ ] check that new applied parsing patterns works well (if any)
- [ ] check graphana monitoring metrics
- [ ] check reports and fraud DB replication status
  - [ ] overall replication status
  - [ ] every table status
- [ ] check dictionaries
- [ ] check scopes
