### ISSUE TITLE
Return DateTime with timezone

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#4354]
Models should deserialize timestamp fields to `DateTime`. 

Checklist:
- [x] ehealth.api (#4427, #4430)
- [x] mpi.api (No changes needed)
- [x] ops.api (edenlabllc/ops.api#196, edenlabllc/ops.api#197)
- [x] uaddresses.api (edenlabllc/uaddresses.api#82)
- [x] report.api (edenlabllc/report.api#182, edenlabllc/report.api#183)
- [x] event_manager.api (edenlabllc/event_manager.api#18, edenlabllc/event_manager.api#19)
- [x] man.api (edenlabllc/man.api#18)
- [x] mithril.api (edenlabllc/mithril.api#364, edenlabllc/mithril.api#367)
- [x] otp_verification.api (edenlabllc/otp_verification.api#73)
