### ISSUE TITLE
create contract request by NHS

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#4475]
- [conf](https://edenlab.atlassian.net/wiki/x/PIUVKw)
- graphQL - create contract request mutation

**Comment by svetavedmed** [comment]
- [ ] on create contract error  “message”: “Employee division must be unique”, we should use Employee w/o end_date olny.
- [ ] after contract request create there is no `assignee`

**Comment by svetavedmed** [comment]
- [ ] empty NHS fields after create contract request
```
issueCity: null
miscellaneous: null
nhsContractPrice: null
nhsLegalEntity: null
nhsPaymentMethod: null
nhsSigner: null
nhsSignerBase: null
previousRequest: null
```

**Comment by svetavedmed** [comment]
- [ ] no documents in any type of contracts. Like there are no links for contract request even create_from_draft
- [ ] null in BD contract_request.data for new contract_request cretae_from_contract. It is created in status `Approved` and should be created with data
