### ISSUE TITLE
NHS Admin Panel

### ISSUE THREAD

**Issue by mmiliaieva** [edenlabllc/ehealth.api#498]
As NHS Admin  
I want to see/control e-health data and processes  
So that is necessary to develop NHS admin panel  
- [x] Verify legal_entity #499 
- [x] Search legal_entity and see details  #500
- [x] List of individuals (party) by legal_entity #502
- [x] List of not approved employee requests #503
- [x] Search employee and see details #504
