### ISSUE TITLE
Service program NHS admin management

### ISSUE THREAD

**Issue by novohatnya** [edenlabllc/ehealth.api#5122]
I as NHS admin 
want to create program services
that connects medical program with services and service groups
so I can create and update program services and related entities

- [ ] Create migration for PRM DB [#6495 (edenlabllc/ehealth.api#5037)](https://zube.io/edenlabllc/e-health/c/6495) 
- [x] Create GraphQL schema [#6346 (edenlabllc/ehealth.api#4938)](https://zube.io/edenlabllc/e-health/c/6346)
- [ ] Implement Services for GraphQL [#6479](https://zube.io/edenlabllc/e-health/c/6479) [#6480](https://zube.io/edenlabllc/e-health/c/6480) [#6481](https://zube.io/edenlabllc/e-health/c/6481) 
- [ ] Implement Service Groups for GraphQL [#6482](https://zube.io/edenlabllc/e-health/c/6482) [#6483](https://zube.io/edenlabllc/e-health/c/6483) [#6484](https://zube.io/edenlabllc/e-health/c/6484) [#6485](https://zube.io/edenlabllc/e-health/c/6485) [#6486](https://zube.io/edenlabllc/e-health/c/6486) 
- [ ] Implement Program Services for GraphQL [#6487](https://zube.io/edenlabllc/e-health/c/6487) [#6488](https://zube.io/edenlabllc/e-health/c/6488) [#6489](https://zube.io/edenlabllc/e-health/c/6489) [#6490](https://zube.io/edenlabllc/e-health/c/6490) 
- [ ] Add `type` for medical program for GraphQL [#6492](https://zube.io/edenlabllc/e-health/c/6492) [#6493](https://zube.io/edenlabllc/e-health/c/6493) 
- [ ] Add field `type` for Medical Program in admin [#6499 (edenlabllc/ehealth.web#930)](https://zube.io/edenlabllc/e-health/c/6499)  [#6500 (edenlabllc/ehealth.web#931)](https://zube.io/edenlabllc/e-health/c/6500) 
- [ ] Create pages for Services in admin [#6496 (edenlabllc/ehealth.web#932)](https://zube.io/edenlabllc/e-health/c/6496) [#6498 (edenlabllc/ehealth.web#933)](https://zube.io/edenlabllc/e-health/c/6498) 
- [ ] Create pages for Service Group in admin [#6503 (edenlabllc/ehealth.web#934)](https://zube.io/edenlabllc/e-health/c/6503) [#6518 (edenlabllc/ehealth.web#939)](https://zube.io/edenlabllc/e-health/c/6518)  [#6519 (edenlabllc/ehealth.web#940)](https://zube.io/edenlabllc/e-health/c/6519) [#6520 (edenlabllc/ehealth.web#941)](https://zube.io/edenlabllc/e-health/c/6520)  [#6521 (edenlabllc/ehealth.web#942)](https://zube.io/edenlabllc/e-health/c/6521) 
- [ ] Create pages for Program Services in admin [#6513 (edenlabllc/ehealth.web#937)](https://zube.io/edenlabllc/e-health/c/6513)  [#6514 (edenlabllc/ehealth.web#938)](https://zube.io/edenlabllc/e-health/c/6514) [#6523 (edenlabllc/ehealth.web#944)](https://zube.io/edenlabllc/e-health/c/6523) [#6524 (edenlabllc/ehealth.web#945)](https://zube.io/edenlabllc/e-health/c/6524) [#6525 (edenlabllc/ehealth.web#946)](https://zube.io/edenlabllc/e-health/c/6525)
