### ISSUE TITLE
UAddresses admin

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#526]
As a NHS admin
I want to be able to 
- [x] see list of regions
- [x] see list of districts
- [x] see list of settlements
- [x] see list of streets
- [x] add/update region
- [x] add/update district
- [x] add/update street

**Comment by lymychp** [comment]
http://uaddresses.dev.ehealth.world

**Comment by warehousman** [comment]
Помилка
Не вказан идентифікатор додатку для авторизації

**Comment by alexeybondarenko** [comment]
@warehousman это ошибка компонента авторизации. уже задеплоил фикс

**Comment by AlekzandrV** [comment]
1. При смене области, не обновляются каскадные зависимые справочники
2. Предложение - добавить лоадер при получении списка каскадных справочников. На текущий момент не понятен прогресс, когда значения подтянулись. При выборе области я успеваю 2-3 раза нажать на район - прежде чем список появится
[Uploading Screen Shot 2017-07-31 at 11.32.27.png...]
