### ISSUE TITLE
search Streets endpoint tuning

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#597]
- [x] validate spec
- [x] ensure that implementation is according to the spec
- [x] test

related to #273

**Comment by AlekzandrV** [comment]
As a MIS, NHS and Uaddresses Admin
I want to get streets from uaddresses

- [ ] Search streets by settlement_id API
- [ ] Clean streets table (https://github.com/Nebo15/uaddresses.api/pull/15)
- [ ] Use query params to filter response
- [ ] Add correct paging to response

**Comment by lymychp** [comment]
paging should be replaced with another ticket
