### ISSUE TITLE
Add seed attribute to declaration

### ISSUE THREAD

**Issue by DPashchenko** [edenlabllc/ehealth.api#669]
1. Add migration to OPS.declarations
    - [x] seed (string, not null)
2. Change method SignDeclarationRequest:
    - [x] when comparing data from request with IL.declaration_request.data, remove the attribute `seed` from the reconciliation condition
    - [x] when insert new record to OPS.declarations, ~add setting `seed` = `prv9s21ZrQH1` (constant)~ set `OPS.declarations.seed` value to `$.seed` from Request

**Comment by gmile** [comment]
Migration added in https://github.com/edenlabllc/ops.api/commit/e9333d4ce99fb1c071941d2c64531e09cabc09bb

**Comment by AlexKovalevych** [comment]
As discussed, we should use static seed for now

**Comment by TarasenkoA** [comment]
seed added
check work in declaration request
insert in db - ok
