### ISSUE TITLE
Pharmacy registration

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#698]
As a Pharmacy Owner
I want be able to register legal_entity (pharmacy) in eHealth system
So that i can start working on reimbursement program

- [x] Update legal_entity (pharmacy) DM #699
- [x] Update Create legal entity WS #700
- [x] Update Get legal entity list WS #701
- [x] Update Get legal entity details WS #702
- [x] Update roles and scopes for new legal entity type
- [x] Add/Update dictionaries (clinet_types etc)
- [x] Improve validation rules (schema, dictionary validation etc)
- [x] Update deactivate legal entity WS #704

**Comment by lymychp** [comment]
pharmacy_owner should have different set of scopes from owner.
Possibly - new employee_type - owner.

**Comment by svetavedmed** [comment]
#### Update roles and scopes for new legal entity type
**mithril.roles**

insert into roles VALUES
           ('2beccbb1-eeec-4eae-834b-ea7c12388f1b'
           ,'PHARMACY_OWNER'
           ,'employee:read employee:write employee:details employee:deactivate employee_request:approve employee_request:read employee_request:write employee_request:reject legal_entity:read otp:write otp:read declaration:read division:read division:write division:details division:activate division:deactivate'
           ,now()
           ,now());

insert into roles VALUES
           ('f189aec7-1939-4f21-9ba7-7b7b66b233e3'
           ,'PHARMACIST'
           ,'employee:read employee_request:approve employee_request:read employee_request:reject legal_entity:read declaration:read division:read'
           ,now()
           ,now());
update dictionaries set values=('{"MIS": "Medical Information system", "MSP": "заклад з надання медичних послуг", "PHARMACY": "Аптека"}') where name='LEGAL_ENTITY_TYPE';

#### Add/Update dictionaries (clinet_types etc)
**il.dictionaries**

update dictionaries set values=('{"MIS": "Medical Information system", "MSP": "заклад з надання медичних послуг", "PHARMACY": "Аптека"}') where name='LEGAL_ENTITY_TYPE';

**Comment by svetavedmed** [comment]
#### Improve validation rules (schema, dictionary validation etc)
https://github.com/edenlabllc/ehealth.api/pull/1013
