### ISSUE TITLE
Update Create legal entity WS

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#700]
Update Create legal entity WS according to requirements

Requirements: [https://docs.google.com/document..](https://docs.google.com/document/d/15qqew84E9PdDb0LS6mhCagOLqcnNa6wmxenR5kHrUPg/edit)

- [x] Update WS [spec](http://docs.ehealthapi1.apiary.io/#reference/public.-medical-service-provider-integration-layer/legal-entities/create/update-legal-entity)
- [x] Update process diagram [Pharmacy registration](https://edenlab.atlassian.net/wiki/spaces/EH/pages/3068930/Pharmacy+registration), [IL.Process](https://edenlab.atlassian.net/wiki/spaces/EH/pages/1112394)
- [x] Implement
- [x] Deploy
- [x] Improve test scenarios 

Development:
- [x] Add new attribute to ukr_med_registry to manage different types of legal_entities https://github.com/Nebo15/ehealth.api/pull/709
- [x] Update existing records - set type = MSP
- [x] Rename dictionary KVEDS_ALLOWED to KVEDS_ALLOWED_MSP
- [x] Add dictionary KVEDS_ALLOWED_PHARMACY
- [x] Provide KVEDS_ALLOWED_PHARMACY content @warehousman 
- [x] Update process logic according to process changes (KVEDs validation, ukr_med_registry)
- [x] Add conditional flow to Create employee request. Create employee type PHARMACY_OWNER for legal entity PHARMACY, and employee_type OWNER for legal entity type MSP

**Comment by kmakarenko** [comment]
Mandatory KVED pharcy is 47.73 Роздрібна торгівля фармацевтичними товарами в спеціалізованих магазинах

**Comment by svetavedmed** [comment]
Improve test scenarios
https://edenlab.atlassian.net/wiki/spaces/EH/pages/14581764/Register+Pharmacy+Test
