### ISSUE TITLE
Update Get legal entity list WS

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#701]
Update Get legal entity list WS according to requirements

Requirements: [https://docs.google.com/document..](https://docs.google.com/document/d/15qqew84E9PdDb0LS6mhCagOLqcnNa6wmxenR5kHrUPg/edit)

- [x] Update WS [spec](http://docs.ehealthapi1.apiary.io/#reference/public.-medical-service-provider-integration-layer/legal-entities/get-legal-entities)
- [x] Update WS logic [Get Pharmacies](https://edenlab.atlassian.net/wiki/spaces/EH/pages/3079899/Get+pharmacy+list)
- [x] Implement
- [x] Deploy
- [x] Improve test scenarios 

Development:

- [x] Implement filtering by PHARMACY type

**Comment by svetavedmed** [comment]
[tests](https://edenlab.atlassian.net/wiki/x/BIDe) made on DEV in Postman
