### ISSUE TITLE
Update Get legal entity details WS

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#702]
Update Get legal entity details WS according to requirements

Requirements: [https://docs.google.com/document..](https://docs.google.com/document/d/15qqew84E9PdDb0LS6mhCagOLqcnNa6wmxenR5kHrUPg/edit)

- [x] Update WS [spec](http://docs.ehealthapi1.apiary.io/#reference/public.-medical-service-provider-integration-layer/legal-entities/get-legal-entity-by-id)
- [x] Update WS logic:
       - MIS context
       - Pharmacy context
       - NHS context
- [x] Implement
- [x] Deploy
- [x] Improve test scenarios
