### ISSUE TITLE
Update deactivate legal entity WS

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#704]
Update deactivate legal entity WS according to requirements

Requirements: [https://docs.google.com/document..](https://docs.google.com/document/d/15qqew84E9PdDb0LS6mhCagOLqcnNa6wmxenR5kHrUPg/edit)

- [x] Update WS [spec](http://docs.ehealthapi1.apiary.io/#reference/public.-medical-service-provider-integration-layer/legal-entities/deactivate-legal-entity-tbd)
- [x] Update WS logic:
       - context
- [x] Implement
- [x] Improve test scenarios

**Comment by svetavedmed** [comment]
#### Improve test scenarios
https://edenlab.atlassian.net/wiki/spaces/EH/pages/14581764/Register+Pharmacy+Test
