### ISSUE TITLE
auth.web client details clean up

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#730]
- [x] actualize scopes for the `eHealth_Auth` client_type
- [x] update wiki page
- [ ] create new client with the `eHealth_Auth` client_type
- [x] change settings for the auth.web - use new client

**Comment by lymychp** [comment]
done
