### ISSUE TITLE
Employee registration

### ISSUE THREAD

**Issue by EdwardVoloshin** [edenlabllc/ehealth.api#738]
As a Pharmacy Owner
I want be able to register same employees (pharmacy) in eHealth system
So that i can start working on reimbursement program

Input:
- need NEW employee_type - PHARMACIST
- need NEW employee_type - PHARMACY_OWNER

Tasks:
- [x] Update Employee DM #739
- [x] Update Create Employee_Request WS #742 
- [x] Update Approve Employee_Request #764
- [x] Update Get employee Request by ID WS - **Nothing** todo!
- [x] Update Get employees List WS - **Nothing** todo!
- [x] Update Get Employee Details #777
- [x] Update Deactivate Employee #778
- [x] Update roles and scopes for new employee type #779

**Comment by lymychp** [comment]
if we do not manage to deploy this to prod before doctors are registered - data migration should be included.
