### ISSUE TITLE
Update employee (pharmacy) DM

### ISSUE THREAD

**Issue by EdwardVoloshin** [edenlabllc/ehealth.api#739]
Update Employee (pharmacy) DM according to requirements and HL7 standards

Requirements: [https://docs.google.com/document/d/15...](https://docs.google.com/document/d/15qqew84E9PdDb0LS6mhCagOLqcnNa6wmxenR5kHrUPg/edit)
HL7: https://www.hl7.org/fhir/practitioner.html

 - [x] Update ERD
 - [x] Create HL7 vs ERD (Practitioner vs Employee) mapping [(HL7comparison)](https://edenlab.atlassian.net/wiki/spaces/EH/pages/3081072/HL7+comparison#HL7comparison-Practitioner)
 - [x] Discuss to change entity "employee_doctor" #776
 - [x] Implement changes
 - [x] Deploy to DEV
 - [ ] Test

Development:
 - [x] Add new entity which links & restrict employee_type which are available in LE with some legal_entity_type.  Proposal entity name - "employee_type_legal_entity_type_links". Task #756

**Comment by lymychp** [comment]
instead of new table creation - have decide to use config.
