### ISSUE TITLE
 Update Create Employee_Request WS

### ISSUE THREAD

**Issue by EdwardVoloshin** [edenlabllc/ehealth.api#742]
Update Create employee request WS according to requirements

Requirements: [Реімбурсація - вимоги](https://docs.google.com/document/d/15qqew84E9PdDb0LS6mhCagOLqcnNa6wmxenR5kHrUPg/edit)
additional: [27072017_обговорення специфікації_ 1](https://docs.google.com/document/d/1kqm7g_hd8PsKwzXc-vI-lvh6vrVC1SyGB3wvMHl39ss/edit?ts=597ed4b1)
- [x] Update WS spec #762 
- [x] Update process diagram [Employee registration](https://edenlab.atlassian.net/wiki/spaces/EH/pages/3192059/Employee+Pharmacy+registration), [IL.Process](https://edenlab.atlassian.net/wiki/spaces/EH/pages/3192059/Employee+Pharmacy+registration)
- [x] Implement
- [x] Deploy
- [x] Improve test scenarios

Development:
- [x] Add new value at dictionary "EMPLOYEE_TYPE": 
"PHARMACIST": "фармацевт"
"PHARMACY_OWNER": "керівник"

- [x] Add new value at dictionary "POSITION": 
"P14": "Старший провізор"
"P15": "Провізор"
"P16": "Фармацевт"
"P17": "Лаборант"
"P18": "Заступники з числа фармацевтів (завідувача, начальника)"
"P19": "Завідувач аптечного пункту"

- [x] Add new value at dictionary "SPECIALITY_TYPE":  
"PHARMACIST": "Фармацевт",
"PHARMACIST2": "Провізор",

**Comment by svetavedmed** [comment]
#### Improve test scenarios
https://edenlab.atlassian.net/wiki/spaces/EH/pages/14680089/Employee+Pharmacy+Request
