### ISSUE TITLE
Create_employee_request - add expired date

### ISSUE THREAD

**Issue by TarasenkoA** [edenlabllc/ehealth.api#770]
Endpoint:
```
/api/employee_requests
```

As NHS admin I need to change status of employee request if this request don't approved after some period (global parameter).

 - [x] add column "expired_date" in 'employee_requests' table [erd](https://github.com/edenlabllc/ehealth.api/blob/master/specs/database_schema/prm.erd)

 - [x] when user creates employee request set value of 'employee_requests.expired_date' to:

    ```sql
    now() + global_parameters.employee_request_expiration
    ```

 - [x] add in response body parameter 'expired_date' and set value from db for this request.
 - [x] create Job for employee_requests:

    ```sql
    update employee_requests
       set status = 'EXPIRED'
     where status not in ('APPROVED', 'REJECTED', 'EXPIRED')
       and expired_day = now()
    ```

All entries that match the condition - change status on EXPIRED

 - [x] in response `approve_employee_request` id declaration request in status EXPIRED - send error 403 and description: 'Employee request is expired'.

**Comment by TarasenkoA** [comment]
Declaration_request should be deleted when expired_day reached.

**Comment by gmile** [comment]
> add column "expired_date" in 'employee_requests' table

@TarasenkoA fyi, there's is no such column in ERD yet

**Comment by AlexKovalevych** [comment]
As discussed, no need in `expired_date` field for now, we will expire declaration requests comparing with `inserted_at` field

**Comment by AlekzandrV** [comment]
There are 3447 employee_requests in status NEW in IL.DB older then config parameter (29 DAYS)
```
SELECT count(1)
FROM employee_requests
  WHERE inserted_at < DATE '2017-08-22' - 29
  AND status = 'NEW';
```

**Comment by AlekzandrV** [comment]
Expire (DELETE) REJECTED employee_requests as well

**Comment by AlekzandrV** [comment]
Employee request auto termination works incorrect. There are several employee requests in DB in status  REJECTED older then 29 DAYS

PRM.global_parameters
```
SELECT id, parameter, value
FROM global_parameters
WHERE parameter like 'employee%';
```
id | parameter | value
---|----------------|--------
519b8a6c-2086-43e4-b18f-7ca4bd95c718 | employee_request_expiration | 29
15665bc4-1cda-4a8d-abb2-f313e902b1c4 | employee_request_term_unit | DAYS

IL.employee_requests
```
SELECT status, count(1) as count
FROM employee_requests
  WHERE inserted_at < current_date - 29
GROUP BY status;
```
status | count
---------|--------
APPROVED | 84
EXPIRED | 89
REJECTED | 11
