### ISSUE TITLE
Update Get Employee Details WS

### ISSUE THREAD

**Issue by EdwardVoloshin** [edenlabllc/ehealth.api#777]
Update Get Employee Details WS according to requirements

Requirements: [Реімбурсація - вимоги](https://docs.google.com/document/d/15qqew84E9PdDb0LS6mhCagOLqcnNa6wmxenR5kHrUPg/edit)

- [x] Update WS [spec](https://edenlab.atlassian.net/wiki/spaces/EH/pages/953422/IL.Employee+details)
- [x] Update Apiary [spec](http://docs.uaehealthapi.apiary.io/reference/public.-medical-service-provider-integration-layer/employees/get-employee-details)
- [x] Implement
- [x] Deploy
- [x] Improve test scenarios
- [x] Development:

 Add new cases into responcse structure for employee_type: PHARMACIST, PHARMACY_OWNER

**Comment by EdwardVoloshin** [comment]
Please review

**Comment by svetavedmed** [comment]
There is no education/qualification/speciality/science_degree data for Pharmacist get details by id, though for Doctor it is. Current response is the same as for HR/OWNER/PHARMACY_OWNER. Should be changed.

response for doctor
```
{
    "meta": {
        "url": "http://dev.ehealth.world/api/employees/c550cf0a-3808-4a9f-93b9-c3c565b419c7",
        "type": "object",
        "request_id": "0l5t9ocgj37nm29t8pt618n1775rlgvm",
        "code": 200
    },
    "data": {
        "status": "APPROVED",
        "start_date": "2017-03-02",
        "position": "P8",
        "party": {
            "tax_id": "3067305998",
            "second_name": "Миколайович133333",
            "phones": [
                {
                    "type": "MOBILE",
                    "number": "+380503410870"
                }
            ],
            "last_name": "Іванов133333",
            "id": "9b92b6c5-30a9-4ea8-a8b8-97855dda2dc7",
            "gender": "MALE",
            "first_name": "Петро1333",
            "documents": [
                {
                    "type": "PASSPORT",
                    "number": "120518"
                }
            ],
            "birth_date": "1956-08-25"
        },
        "legal_entity": {
            "type": "MSP",
            "status": "ACTIVE",
            "short_name": "Клиника 12",
            "public_name": "Клиника 13",
            "owner_property_type": "STATE",
            "name": "Клиника 12",
            "mis_verified": "NOT_VERIFIED",
            "legal_form": "140",
            "id": "d521ea0a-f634-46db-8d59-1f5ff9c03aed",
            "edrpou": "38782323"
        },
        "id": "c550cf0a-3808-4a9f-93b9-c3c565b419c7",
        "end_date": null,
        "employee_type": "DOCTOR",
        "doctor": {
            "specialities": [
                {
                    "valid_to_date": "2017-08-05",
                    "speciality_officio": true,
                    "speciality": "PEDIATRICIAN",
                    "qualification_type": "AWARDING",
                    "level": "FIRST",
                    "certificate_number": "AB/21331",
                    "attestation_name": "Академія Богомольця",
                    "attestation_date": "2017-08-05"
                }
            ],
            "science_degree": {
                "speciality": "THERAPIST",
                "issued_date": "2017-08-05",
                "institution_name": "Академія Богомольця",
                "diploma_number": "DD123543",
                "degree": "CANDIDATE_OF_SCIENCE",
                "country": "UA",
                "city": "Київ"
            },
            "qualifications": [
                {
                    "type": "STAZHUVANNYA",
                    "speciality": "Педіатр",
                    "issued_date": "2017-08-05",
                    "institution_name": "Академія Богомольця",
                    "certificate_number": "2017-08-05"
                }
            ],
            "educations": [
                {
                    "speciality": "Педіатр",
                    "issued_date": "2017-08-05",
                    "institution_name": "Академія Богомольця",
                    "diploma_number": "DD123543",
                    "degree": "MASTER",
                    "country": "UA",
                    "city": "Київ"
                }
            ]
        },
        "division": {
            "type": "CLINIC",
            "status": "ACTIVE",
            "name": "Бориспільське відділення Клініки Борис",
            "mountain_group": false,
            "legal_entity_id": "f41ebb33-e9d0-4ef4-8e92-ee719d16554e",
            "id": "af11a7b0-7c89-4156-8725-02783199fcc5"
        }
    }
}
```

response for Pharmacist
```
{
    "meta": {
        "url": "http://dev.ehealth.world/api/employees/f9833a0c-2ca7-4520-bb21-b3e81b0f808a",
        "type": "object",
        "request_id": "d4lp9s5h19rbs5timcudg7m4ea95j681",
        "code": 200
    },
    "data": {
        "status": "APPROVED",
        "start_date": "2017-03-02",
        "position": "P16",
        "party": {
            "tax_id": "3067305998",
            "second_name": "Ивановна",
            "phones": [
                {
                    "type": "MOBILE",
                    "number": "+380503410870"
                }
            ],
            "last_name": "Кпивошеева",
            "id": "c80bf9af-156c-4265-a54e-ae2fcd880e98",
            "gender": "FEMALE",
            "first_name": "Галина",
            "documents": [
                {
                    "type": "PASSPORT",
                    "number": "120518"
                }
            ],
            "birth_date": "1976-08-25"
        },
        "legal_entity": {
            "type": "PHARMACY",
            "status": "ACTIVE",
            "short_name": "13",
            "public_name": "13",
            "owner_property_type": "STATE",
            "name": "Больница №13",
            "mis_verified": "NOT_VERIFIED",
            "legal_form": "140",
            "id": "1540179c-72ce-4bb7-97ab-8b3a6f8705b1",
            "edrpou": "38782373"
        },
        "id": "f9833a0c-2ca7-4520-bb21-b3e81b0f808a",
        "end_date": null,
        "employee_type": "HR",
        "division": {
            "type": "DRUGSTORE",
            "status": "ACTIVE",
            "name": "Бориспільське відділення Клініки Odessa",
            "mountain_group": false,
            "legal_entity_id": "f41ebb33-e9d0-4ef4-8e92-ee719d16554e",
            "id": "1dc7ddaf-a353-4363-b5c6-c2ddf4b5b150"
        }
    }
}
```
