### ISSUE TITLE
New division types for pharmacy

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#876]
TO DO

- [x] Add new values to Dictionary `Division_type`
- DRUGSTORE | Аптека
- DRUGSTORE_POINT | Аптечний пункт
- [x] Create Mapping in IL for relationse between `Division_type` & `legal_entity_type` according [table](https://docs.google.com/spreadsheets/d/12uHMP7yyYQ_m9o9nuhUMLRnCfl2xl3CxDVs9YyWp1tw/edit?usp=sharing)
- [x] Update [spec: Create division](https://edenlab.atlassian.net/wiki/spaces/EH/pages/27394067/IL.Create+Division)
- [x] Implement changes for EP: Create Division 
- [x] Improve test scenarios  

#699

**Comment by lymychp** [comment]
relationse between `Division_type` & `legal_entity_type` should be in the config

**Comment by svetavedmed** [comment]
test scenarios were made in Postman
