### ISSUE TITLE
Declaration number

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#918]
As a NHS Admin
I want to get valid and correct declaration number in printout form

- [x] Add field to IL.declaration_request to store declaration number
- [x] Generate declaration number on Create declaration request
- [x] Add generated declaration number to MAN call
- [x] Modify Sign declaration request - create declaration with `ID = Generated declaration number`
- [x] Do not return declaration number in responses (Create, Get, Approve) and do not include it in request validation logic

#916

**Comment by AlekzandrV** [comment]
Tested
