### ISSUE TITLE
[Declarations] Offline verification

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#928]
As a NHS Verificator
I want to view and verify declarations that was created with authentication method OFFLINE

- [x] Modify "Декларації на розгляді" page:
       * Invoke `/api/declarations?status=pending_verification` method to show list (scope `declaration:read`)
- [x] Modify `Детально` page:
       * Invoke `/api/declarations/:id` (scope `declaration:read`)
<img width="1305" alt="screenshot at aug 28 17-19-55" src="https://user-images.githubusercontent.com/12275915/29777761-c981406c-8c15-11e7-8530-4221d64ee627.png">

- [x] Change mapping for Reject/Approve buttons
       * Reject - `/api/declarations/:id/actions/reject` (scope `declaration:reject`)
       * Approve - `/api/declarations/:id/actions/approve` (scope `declaration:approve`)
<img width="1366" alt="screenshot at aug 28 17-20-46" src="https://user-images.githubusercontent.com/12275915/29777766-cf64339a-8c15-11e7-8dac-14354da572ad.png">

- [x] Change Get images [endpoint](http://docs.uaehealthapi.apiary.io/#reference/internal.-il-db/get-declaration-documents-list/get-declaration-documents-list) (scope `declaration_documents:read`)
