### ISSUE TITLE
Declaration auto-approve

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#930]
As a NHS Admin
I want declarations (OPS.DB) with OFFLINE authentication method to be automatically approved according to the global parameters configuration.

- [x] Read global_parameter `verification_request_expiration`
- [x] Calculate pending verification period for declarations:
       * status = pending_verification
       * now() < inserted_at + `verification_request_expiration`
- [x] Update status to 'active'

**Comment by AlekzandrV** [comment]
Replace hardcoded terminator with QUANTUM and CRON-like syntax
