### ISSUE TITLE
Modify declaration request images list

### ISSUE THREAD

**Issue by AlekzandrV** [edenlabllc/ehealth.api#931]
Change declaration request images list API according to [spec](http://docs.uaehealthapi.apiary.io/#reference/internal.-il-db/get-declaration-images-list/get-declaration-images-list):

- [x] Change route on GW - set `/api/declarations/:id/documents`
- [x] Update scope on GW - set `declaration_documents:read`
- [x] Change API logic: 
       * search declaration request in *IL.declaration_requests* using `declaration_id` from URI
       * get documents list from *IL.declaration_requests.documents*
       * refresh access links in AEL for all documents in list

**Comment by AlekzandrV** [comment]
Tested
