### ISSUE TITLE
review HR and admin scopes

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#943]
- [ ] check what scopes should be added/removed
- [ ] adjust it on dev
- [ ] create migrations for demo

**Comment by lymychp** [comment]
declaration_request:write is missing for HR

**Comment by lymychp** [comment]
scopes has been reviewed by PO and applied to all the envs
