### ISSUE TITLE
Administration Innms & Medications

### ISSUE THREAD

**Issue by EdwardVoloshin** [edenlabllc/ehealth.api#958]
As a NHS Admin  
I want administrative Substances, Innms, Medications.  
So that program reimbursement can be start worked.

**Substances**
- [x] Create Substance #980 
- [x] Get Substance by ID #1051
- [x] Get List Substances #1052

**Innms**
- [x] Create Innm #960 
- [x] Deactivate Innm #961
- [x] Get INNM by ID #1053
- [x] Get List INNMs #1054

**Medications**
- [x] Create Medication #962
- [x] Deactivate Medication #979 
- [x] Get Medication by ID #1055
- [x] Get List Medications #1056
 
**Medical Program**
- [x] Create Medical Program #1095
- [x] Deactivate Medical Program #1096
- [x] Get Medical Program by ID #1097
- [x] Get Medical Program List #1098 

**Program Medication**
- [x] Create Program Medication #1108
- [x] Update Program Medication #1109 
- [x] Get Program Medication by ID #1110
- [x] Get Program Medication List #1111
