### ISSUE TITLE
EP: Create Innm

### ISSUE THREAD

**Issue by EdwardVoloshin** [edenlabllc/ehealth.api#960]
Create Innm entity WS 
- [x] Create WS [spec](https://edenlab.atlassian.net/wiki/spaces/EH/pages/25166468/Create+INNM)
- [x] Implement
- [x] Deploy
- [x] Improve test scenarios

**Bugs**:
- [x] 1. In ingredients part there is only one is_active_substance=true.
- [x] 2. Verify MEDICATION_UNIT for ingredients.dosage
- [x] 3. Checking is_active='true' for ingredients
- [x] 4. One and only one ingredient must have "is_active_substance": true
- [x] 5. Substances can't be duplicated in inmm. If id is mentioned more then ones error has to be shown
- [x] 6. Verify MEDICATION_FORM for ingredients.form

**Comment by danakonovalenko** [comment]
In ingredients part there is only one is_active_substance=true.

# Steps to reproduce

## Request
```
{
  "name": "Амідарон1",
  "form": "PILL",
  "ingredients": [
    {
      "id": "0c477ded-453f-4edf-9a73-f282673340c8",
      "dosage": {
        "numerator_unit": "MG111",
        "numerator_value": 200,
        "denumerator_unit": "PILL111",
        "denumerator_value": 1
      },
      "is_active_substance": true
    },
    {
      "id": "ad762ce9-f169-454c-8404-5a94363879c3",
      "dosage": {
        "numerator_unit": "MG111",
        "numerator_value": 200,
        "denumerator_unit": "PILL111",
        "denumerator_value": 1
      },
      "is_active_substance": true
    }  
  ]
}
```
## Response
201 - created.

**Comment by danakonovalenko** [comment]
For dosage units dictionary must be used and verified (Dictionary MEDICATION_UNIT):

```
"dosage": {
                    "numerator_value": 200,
                    "numerator_unit": "MG111",
                    "denumerator_value": 1,
                    "denumerator_unit": "PILL111"
                }
```
Next values should be added to dictionary and merged.
```
medications | medication_unit | ml | мілілітр
medications | medication_unit | mg | міліграм
medications | medication_unit | mkg | мікрограм
medications | medication_unit | dose | доза
medications | medication_unit | ie | міжнародна одиниця
medications | medication_unit | pill | таблетка
medications | medication_unit | ampoule | ампула
medications | medication_unit | container | контейнер
medications | medication_unit | bottle | пляшка
medications | medication_unit | vial | шприц
medications | medication_unit | aerosol | аерозоль
```
@PavelVesnin

**Comment by danakonovalenko** [comment]
3. To create new innm the substance must be active (is_active='true'), otherwise the error must be shown.

## Request
```
{
  "name": "Амідарон-1",
  "form": "PILL",
  "ingredients": [
    {
      "id": "eb9a77e4-31c8-4bd3-894a-ee931db5e4e8",
      "dosage": {
        "numerator_unit": "MG",
        "numerator_value": 200,
        "denumerator_unit": "PILLeb9a77e4-31c8-4bd3-894a-ee931db5e4e8",
        "denumerator_value": 1
      },
      "is_active_substance": true
    }
  ]
}
```
I received 201 created, tough for "id": "eb9a77e4-31c8-4bd3-894a-ee931db5e4e8" is_active=false

**Comment by danakonovalenko** [comment]
## 4

One and only one ingredient must have "is_active_substance": true. If all ingredients have "is_active_substance": false the innm can't be created
```
{
  "name": "Амідарон",
  "form": "PILL",
  "ingredients": [
    {
      "id": "25fa47ce-46a1-4399-a466-f970694de254",
      "dosage": {
        "numerator_unit": "MG111",
        "numerator_value": 200,
        "denumerator_unit": "PILL111",
        "denumerator_value": 1
      },
      "is_active_substance": false
    }
  ]
}
```
I received 201 created

**Comment by svetavedmed** [comment]
## 5
Substances can't be duplicated in inmm. If id is mentioned more then ones error has to be shown 
### Request
```
{
  "name": "Амідарон1",
  "form": "PILL",
  "ingredients": [
    {
      "id": "0c477ded-453f-4edf-9a73-f282673340c8",
      "dosage": {
        "numerator_unit": "MG",
        "numerator_value": 200,
        "denumerator_unit": "PILL",
        "denumerator_value": 1
      },
      "is_active_substance": true
    },
    {
      "id": "0c477ded-453f-4edf-9a73-f282673340c8",
      "dosage": {
        "numerator_unit": "MG",
        "numerator_value": 200,
        "denumerator_unit": "PILL",
        "denumerator_value": 1
      },
      "is_active_substance": false
    }  
  ]
}
``` 
I received 201 created

**Comment by PavelVesnin** [comment]
2. - create in Dictionaries service entry with type MEDICATION_UNIT

**Comment by svetavedmed** [comment]
### 6.
 For Form MEDICATION_UNIT has to be used and verified. As it is done for dosage.

### Request
```
{
  "name": "Амідарон",
  "form": "77765543",
  "ingredients": [
    {
      "id": "0c477ded-453f-4edf-9a73-f282673340c8",
      "dosage": {
        "numerator_unit": "MG",
        "numerator_value": 200,
        "denumerator_unit": "PILL",
        "denumerator_value": 1
      },
      "is_active_substance": true
    }
  ]
}
```
Error 422 should be shown. I received 201 created
