### ISSUE TITLE
EP: Create Medication

### ISSUE THREAD

**Issue by EdwardVoloshin** [edenlabllc/ehealth.api#962]
Create Medication entity WS according to requirements

Requirements: [вимоги](https://docs.google.com/document/d/15qqew84E9PdDb0LS6mhCagOLqcnNa6wmxenR5kHrUPg/edit?usp=sharing)

- [x] Create WS [spec](https://edenlab.atlassian.net/wiki/spaces/EH/pages/13697025/Create+Medication)
- [x] Implement
- [x] Deploy
- [ ] Improve test scenarios

## Bugs
- [x] 1. In ingredients part there is only one is_active_substance=true
- [x] 2. Only one ingredients and status "is_active_substance": false 
- [x] 3. Dictionary MEDICATION_UNIT for Dosage
- [x] 4. Create medication with 2 same innm_id in ingredients
- [x] 5. Create medication using medication_id in ingredients
- [x] 6. Create medication using inactive substance_id
- [x] 7. Multiplicity for package quantity check
- [x] 8. Dictionary MEDICATION_FORM for "form"
- [x] 9. Denumerator unit from Ingredients.dosage  must be equal Numerator unit from Container

**Comment by danakonovalenko** [comment]
## 1. 
In ingredients part there is only one is_active_substance=true.

Request
```
{
  "name": "Амідарон12",
  "manufacturer": {
    "name": "ПАТ \"Київський вітамінний завод\"",
    "country": "UA"
  },
  "code_atc": "A01BD01",
  "form": "PILL",
  "container": {
    "numerator_unit": "PILL",
    "numerator_value": 1,
    "denumerator_unit": "PILL",
    "denumerator_value": 1
  },
  "package_qty": 30,
  "package_min_qty": 10,
  "certificate": "UA/4514/01/01",
  "certificate_expired_at": "2021-02-09",
  "ingredients": [
    {
      "id": "a5403498-812c-4dec-a145-dd43a981c8c0",
      "dosage": {
        "numerator_unit": "MG",
        "numerator_value": 200,
        "denumerator_unit": "PILL",
        "denumerator_value": 1
      },
      "is_active_substance": true
    },
    {
      "id": "ef7d68d0-37b5-42ec-8560-62e6814070f4",
      "dosage": {
        "numerator_unit": "MG",
        "numerator_value": 0.5,
        "denumerator_unit": "PILL",
        "denumerator_value": 1
      },
      "is_active_substance": true
    }
  ]
}
````
Response
201 Created

## 2. 
One and only one ingredient must have "is_active_substance": true. If all ingredients have "is_active_substance": false the innm can't be created

Request 

```
{
  "name": "Амідарон1-",
  "manufacturer": {
    "name": "ПАТ \"Київський вітамінний завод\"",
    "country": "UA"
  },
  "code_atc": "A01BD01",
  "form": "PILL",
  "container": {
    "numerator_unit": "PILL",
    "numerator_value": 1,
    "denumerator_unit": "PILL",
    "denumerator_value": 1
  },
  "package_qty": 30,
  "package_min_qty": 10,
  "certificate": "UA/4514/01/01",
  "certificate_expired_at": "2021-02-09",
  "ingredients": [
    {
      "id": "ef7d68d0-37b5-42ec-8560-62e6814070f4",
      "dosage": {
        "numerator_unit": "MG",
        "numerator_value": 0.5,
        "denumerator_unit": "PILL",
        "denumerator_value": 1
      },
      "is_active_substance": false
    }
  ]
}
```
Response 

201 Created

## 3. 
For dosage units dictionary must be used and verified (Dictionary MEDICATION_UNIT):

```
"dosage": {
                    "numerator_value": 200,
                    "numerator_unit": "MG111",
                    "denumerator_value": 1,
                    "denumerator_unit": "PILL111"
                }
```
Response 

201 Created

## 4. 
Create medication with 2 same innm_id in ingredients

Request 

```
{
  "name": "Амідарон1-",
  "manufacturer": {
    "name": "ПАТ \"Київський вітамінний завод\"",
    "country": "UA"
  },
  "code_atc": "A01BD01",
  "form": "PILL",
  "container": {
    "numerator_unit": "PILL",
    "numerator_value": 1,
    "denumerator_unit": "PILL",
    "denumerator_value": 1
  },
  "package_qty": 30,
  "package_min_qty": 10,
  "certificate": "UA/4514/01/01",
  "certificate_expired_at": "2021-02-09",
  "ingredients": [
    {
      "id": "ef7d68d0-37b5-42ec-8560-62e6814070f4",
      "dosage": {
        "numerator_unit": "MG",
        "numerator_value": 0.5,
        "denumerator_unit": "PILL",
        "denumerator_value": 1
      },
      "is_active_substance": true
    },
    {
      "id": "ef7d68d0-37b5-42ec-8560-62e6814070f4",
      "dosage": {
        "numerator_unit": "MG",
        "numerator_value": 0.5,
        "denumerator_unit": "PILL",
        "denumerator_value": 1
      },
      "is_active_substance": true
    }
  ]
}
```
Response 

201 Created

## 5.

While creating medication I used medication_id in ingredients, not innm_id and received 201.
 
```
{
  "name": "Амідарон1-",
  "manufacturer": {
    "name": "ПАТ \"Київський вітамінний завод\"",
    "country": "UA"
  },
  "code_atc": "A01BD01",
  "form": "PILL",
  "container": {
    "numerator_unit": "PILL",
    "numerator_value": 1,
    "denumerator_unit": "PILL",
    "denumerator_value": 1
  },
  "package_qty": 30,
  "package_min_qty": 10,
  "certificate": "UA/4514/01/01",
  "certificate_expired_at": "2021-02-09",
  "ingredients": [
    {
      "id": "960a457c-ee16-4ec7-9a10-8e581164a795",
      "dosage": {
        "numerator_unit": "MG",
        "numerator_value": 0.5,
        "denumerator_unit": "PILL",
        "denumerator_value": 1
      },
      "is_active_substance": true
    }
  ]
}
``` 
Response
 
201 Created

## 6. 

While creating medication I used inactive substance in ingredients and received 201.

```
{
  "name": "Амідарон",
  "manufacturer": {
    "name": "ПАТ \"Київський вітамінний завод\"",
    "country": "UA"
  },
  "code_atc": "C01BD01",
  "form": "PILL",
  "container": {
    "numerator_unit": "PILL",
    "numerator_value": 1,
    "denumerator_unit": "PILL",
    "denumerator_value": 1
  },
  "package_qty": 30,
  "package_min_qty": 10,
  "certificate": "UA/4514/01/01",
  "certificate_expired_at": "2021-02-09",
  "ingredients": [
    {
      "id": "ef7d68d0-37b5-42ec-8560-62e6814070f4",
      "dosage": {
        "numerator_unit": "MG",
        "numerator_value": 200,
        "denumerator_unit": "PILL",
        "denumerator_value": 1
      },
      "is_active_substance": true
    }
  ]
}
```

**Comment by PavelVesnin** [comment]
3. - You should create a row in Dictionaries with type MEDICATION_UNIT

**Comment by danakonovalenko** [comment]
7. While creating medication multiplicity must be checked. I created medication with  "package_qty": 30,
 "package_min_qty": 9
which is impossible and received 201 Created.
