### ISSUE TITLE
EP: Get Drugs

### ISSUE THREAD

**Issue by EdwardVoloshin** [edenlabllc/ehealth.api#964]
Get Drugs WS according to requirements

Requirements: [вимоги](https://docs.google.com/document/d/15qqew84E9PdDb0LS6mhCagOLqcnNa6wmxenR5kHrUPg/edit?usp=sharing)
[BP](https://edenlab.atlassian.net/wiki/spaces/EH/pages/3380784/Create+Medication+Request+BP)

- [x] Create WS [spec](https://edenlab.atlassian.net/wiki/spaces/EH/pages/3380878/Get+Drugs+Dictionary)
- [x] Implement
- [x] Deploy
- [x] Improve [test scenarios](https://edenlab.atlassian.net/wiki/spaces/EH/pages/40599768/Get+Drugs+Tests)

Bugs
- [x] 1. Receive 500 with filtering by innm_id
- [x] 2. don't filter by innm_dosage_id
- [x] 4. Receive 500 filtering by innm_dosage_form

**Comment by svetavedmed** [comment]
### 1. Receive 500 with filtering by innm_id
Log in as Doctor
#### Request
GET {{host}}/api/drugs?innm_id=8d6f095a-6d15-4fe7-9d4e-6a679287889b

**Comment by svetavedmed** [comment]
### 2. don't filter by innm_dosage_id
Log in as Doctor
### Request
{{host}}/api/drugs?innm_dosage_id=52a7dab5-31ac-4465-b782-03e5b9006e2a
### Response
"total_entries": 21

**Comment by svetavedmed** [comment]
### 3. Paging don't work correctly 
GET {{host}}/api/drugs?innm_name=Будесонід

In response I receive 4 arrays of data, but  total_entries = 1. 

#### Response
```
{
    "paging": {
        "total_pages": 1,
        "total_entries": 1,
        "page_size": 50,
        "page_number": 1
    },
    "meta": {
        "url": "http://dev.ehealth.world/api/drugs",
        "type": "list",
        "request_id": "15p46pqb0htpk3q7a7mppd3gj3cit7pp",
        "code": 200
    },
    "data": [
        {
            "packages": [
                {
                    "package_qty": 100,
                    "package_min_qty": 100,
                    "container_dosage": {
                        "numerator_value": 1,
                        "numerator_unit": "DOSE",
                        "denumerator_value": 1,
                        "denumerator_unit": "AEROSOL"
                    }
                },
                {
                    "package_qty": 200,
                    "package_min_qty": 200,
                    "container_dosage": {
                        "numerator_value": 1,
                        "numerator_unit": "DOSE",
                        "denumerator_value": 1,
                        "denumerator_unit": "AEROSOL"
                    }
                }
            ],
            "name": "Будесонід 200 MKG Порошок для інгаляцій",
            "innm": {
                "sctid": null,
                "name_original": "Budesonide",
                "name": "Будесонід",
                "id": "fcadd9e5-cf91-45aa-b7fb-ffd706b59d01"
            },
            "id": "116fb004-6f54-4c6c-a106-4f21cfd97e55",
            "form": "INHALATION_POWDER",
            "dosage": {
                "numerator_value": 200,
                "numerator_unit": "MKG",
                "denumerator_value": 1,
                "denumerator_unit": "DOSE"
            }
        },
        {
            "packages": [
                {
                    "package_qty": 20,
                    "package_min_qty": 5,
                    "container_dosage": {
                        "numerator_value": 1,
                        "numerator_unit": "ML",
                        "denumerator_value": 1,
                        "denumerator_unit": "CONTAINER"
                    }
                }
            ],
            "name": "Будесонід 0.5 MG Суспензія для розпилення",
            "innm": {
                "sctid": null,
                "name_original": "Budesonide",
                "name": "Будесонід",
                "id": "fcadd9e5-cf91-45aa-b7fb-ffd706b59d01"
            },
            "id": "13cdb91d-8f4e-41bf-bb9f-9411b3ead549",
            "form": "NEBULISER_SUSPENSION",
            "dosage": {
                "numerator_value": 0.5,
                "numerator_unit": "MG",
                "denumerator_value": 1,
                "denumerator_unit": "ML"
            }
        },
        {
            "packages": [
                {
                    "package_qty": 200,
                    "package_min_qty": 200,
                    "container_dosage": {
                        "numerator_value": 1,
                        "numerator_unit": "DOSE",
                        "denumerator_value": 1,
                        "denumerator_unit": "AEROSOL"
                    }
                }
            ],
            "name": "Будесонід 200 MKG інгаляція під тиском",
            "innm": {
                "sctid": null,
                "name_original": "Budesonide",
                "name": "Будесонід",
                "id": "fcadd9e5-cf91-45aa-b7fb-ffd706b59d01"
            },
            "id": "52a7dab5-31ac-4465-b782-03e5b9006e2a",
            "form": "PRESSURISED_INHALATION",
            "dosage": {
                "numerator_value": 200,
                "numerator_unit": "MKG",
                "denumerator_value": 1,
                "denumerator_unit": "DOSE"
            }
        },
        {
            "packages": [
                {
                    "package_qty": 200,
                    "package_min_qty": 200,
                    "container_dosage": {
                        "numerator_value": 1,
                        "numerator_unit": "DOSE",
                        "denumerator_value": 1,
                        "denumerator_unit": "AEROSOL"
                    }
                }
            ],
            "name": "Будесонід 100 MKG Порошок для інгаляцій",
            "innm": {
                "sctid": null,
                "name_original": "Budesonide",
                "name": "Будесонід",
                "id": "fcadd9e5-cf91-45aa-b7fb-ffd706b59d01"
            },
            "id": "f2ac4807-71f0-4bdd-b54a-2474dab03a8c",
            "form": "INHALATION_POWDER",
            "dosage": {
                "numerator_value": 100,
                "numerator_unit": "MKG",
                "denumerator_value": 1,
                "denumerator_unit": "DOSE"
            }
        }
    ]
}
```
For example, in division list paging work correctly
```
{
    "paging": {
        "total_pages": 1,
        "total_entries": 2,
        "page_size": 15,
        "page_number": 1
    },
    "meta": {
        "url": "http://dev.ehealth.world/api/divisions",
        "type": "list",
        "request_id": "hl4b3044gv8al7nu2rve8da7nhs0bkmf",
        "code": 200
    },
    "data": [
        {
            "type": "CLINIC",
            "status": "ACTIVE",
            "phones": [
                {
                    "type": "MOBILE",
                    "number": "+380503410870"
                }
            ],
            "name": "Бориспільське відділення Клініки Борис",
            "mountain_group": false,
            "location": null,
            "legal_entity_id": "443e901e-b365-45d2-be14-083ee0aba657",
            "id": "6525d607-04e7-4fc8-8c6c-39849624ddbc",
            "external_id": "3213213",
            "email": "sp.virny+51@gmail.com",
            "addresses": [
                {
                    "zip": "02090",
                    "type": "REGISTRATION",
                    "street_type": "STREET",
                    "street": "вул. Ніжинська",
                    "settlement_type": "CITY",
                    "settlement_id": "707dbc55-cb6b-4aaa-97c1-2a1e03476100",
                    "settlement": "СОРОКИ-ЛЬВІВСЬКІ",
                    "region": "ПУСТОМИТІВСЬКИЙ",
                    "country": "UA",
                    "building": "15",
                    "area": "ЛЬВІВСЬКА",
                    "apartment": "23"
                }
            ]
        },
        {
            "type": "CLINIC",
            "status": "ACTIVE",
            "phones": [
                {
                    "type": "MOBILE",
                    "number": "+380503410870"
                }
            ],
            "name": "Бориспільське відділення Клініки Борис",
            "mountain_group": false,
            "location": null,
            "legal_entity_id": "443e901e-b365-45d2-be14-083ee0aba657",
            "id": "b5fe1184-cee2-4948-a9b9-d0389dece95a",
            "external_id": "3213213",
            "email": "sp.virny+51@gmail.com",
            "addresses": [
                {
                    "zip": "02090",
                    "type": "REGISTRATION",
                    "street_type": "STREET",
                    "street": "вул. Ніжинська",
                    "settlement_type": "CITY",
                    "settlement_id": "707dbc55-cb6b-4aaa-97c1-2a1e03476100",
                    "settlement": "СОРОКИ-ЛЬВІВСЬКІ",
                    "region": "ПУСТОМИТІВСЬКИЙ",
                    "country": "UA",
                    "building": "15",
                    "area": "ЛЬВІВСЬКА",
                    "apartment": "23"
                }
            ]
        }
    ]
}
```

**Comment by svetavedmed** [comment]
### 4. Receive 500 filtering by innm_dosage_form

Log in as Doctor
GET {{host}}/api/drugs?innm_dosage_form=TABLET
