### ISSUE TITLE
Manage Medication request

### ISSUE THREAD

**Issue by EdwardVoloshin** [edenlabllc/ehealth.api#965]
As a MSP Doctor
I want be able to manage Medication requests (Create, Sign, Qualify, Get list, Recall, etc)
So that i can serve patients and prescribe drugs for treatment [Medication request BP](https://edenlab.atlassian.net/wiki/spaces/EH/pages/3380784/Create+Medication+Request+BP),  [Requirements](https://docs.google.com/document/d/15qqew84E9PdDb0LS6mhCagOLqcnNa6wmxenR5kHrUPg/edit?usp=sharing)
  
- [x] Create  Request Request #966 
- [x] Generate `Request number` for Medication Request #1114
- [x] Generate  `Verification code` for Medication Request #1115
- [x] Qualify Medication Request Request #967
- [x] Qualify Medication Request by ID #974
- [x] AUTO Terminate Medication Request Request #968
- [x] Reject Medication Request Request #969
- [x] Get Medication Request Request by ID #970
- [x] Get Medication Request Request List #971
- [x] Sign Medication Request Request #973
- [x] Get Medication request by ID #975
- [x] Get Medication requests List #976
- [x] Reject Medication request #977
- [x]  AUTO Terminate  Medication request #978
- [x] Resend Medication Request  #1085

**Comment by AlekzandrV** [comment]
@EdwardVoloshin Specify new feature "Resend verification code". Feature allowed only for persons with authentication method = SMS
