### ISSUE TITLE
EP: PreQualify Medication request

### ISSUE THREAD

**Issue by EdwardVoloshin** [edenlabllc/ehealth.api#967]
PreQualify Medication request WS 

- [x] Create WS [spec](https://edenlab.atlassian.net/wiki/x/AQB1)
- [x] Implement
- [x] Deploy
- [x] Improve test scenarios

Bugs
- [x] It can be only 1 Medication request (ACTIVE, COMPLETED)  per one innm for the one patient at defined period of time.

**Comment by svetavedmed** [comment]
1. It can be only 1 Medication request (ACTIVE, COMPLETED) per one innm for the one patient at defined period of time.
medication_request id='8305c3ec-1240-4e11-9162-2c0e168198fc'

id|created_at|started_at|ended_at|person_id|employee_id|medication_id|medical_program_id
--|---------------|-------------|--------------|------------|----------------|-------------------|-------------
8305c3ec-1240-4e11-9162-2c0e168198fc|2017-10-17|2017-10-17|2017-10-25|806e4d6e-da29-4433-a79f-7affc5e160aa|7495ddf8-95d4-4e10-9763-1ad7f29b1ec9|837f5c7b-cb1b-47f4-ae29-64fb2b7db576|3c7d7a7f-82c2-4f5c-806e-f1f5b55164a2

request
```
curl -X POST \
  https://dev.ehealth.world/api/medication_request_requests/prequalify \
  -H 'authorization: Bearer a3dDV2F3KzhLYmVrc1AvdytmbE1GUT09' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: 471ff143-9a40-bade-9411-3c651904edc6' \
  -d '{
 "medication_request_request":
 {
  "person_id": "806e4d6e-da29-4433-a79f-7affc5e160aa",
  "employee_id": "7495ddf8-95d4-4e10-9763-1ad7f29b1ec9",
  "division_id": "824a8cd9-f52d-43ec-b998-a625776d9bac",
  "created_at": "2017-10-17",
  "started_at": "2017-10-17",
  "ended_at": "2017-10-25",
  "dispense_valid_from": "2017-10-17",
  "dispense_valid_to": "2017-10-25",
  "medication_id": "837f5c7b-cb1b-47f4-ae29-64fb2b7db576",
  "medication_qty": 10
 },
 "programs": [
    {
      "id": "3c7d7a7f-82c2-4f5c-806e-f1f5b55164a2"
    }
  ]
}

'
```
response
```
{
    "meta": {
        "url": "http://dev.ehealth.world/api/medication_request_requests/prequalify",
        "type": "list",
        "request_id": "pvqgjeboepu0b5oh1umru58tc8du006g",
        "code": 200
    },
    "data": [
        {
            "status": "VALID",
            "program_name": "Доступні ліки",
            "program_id": "3c7d7a7f-82c2-4f5c-806e-f1f5b55164a2"
        }
    ]
}
```
